## Task 1: Define the Problem

In [1]:
# df_data = pd.read_csv("hf://datasets/lukebarousse/data_jobs/data_jobs.csv")

Using the Generated messay dataset,

1.   Clean the data
2.   Exploratory Data Analysis
3.   Use train test model to predict data analysis salaries

## Task 2: Install The Needed Libraries

In [2]:
import pandas as pd
import numpy as np
import random
import re
import statistics


# Data Visualization
import seaborn as sns
import matplotlib.pyplot as plt
import plotly as pl

In [3]:
# Import Test Train Split

# Import sklearn Model 1
# Import sklearn Model 2
# Import sklearn Model 3
# Import sklearn Model 4

In [4]:
# allows me to view the whole list of columns
# Set option to display all rows (if your output from isna().sum() is very long)
pd.set_option('display.max_rows', None)

# Setting df head to all show all columns
pd.set_option('display.max_columns', None)

## Task 3: Load the Data

In [5]:
random.seed(42)
num_rows = 2500  # Generates 2,500 rows

# 1. Define "Messy" Data Pools
job_titles = [
    "Data Analyst", "DATA ANALYST", "Sr. Data Analyst", "Senior Data Analyst", "Data Analyst II",
    "Jr. Data Analyst", "Junior Data Analyst", "Data Analytics Specialist", "BI Analyst",
    "Data Analyst - Remote", "Product Data Analyst", "Marketing Data Analyst", "Data Analyst!!!"
]

salaries = [
    "$60,000 - $80,000", "$90,000", "110000", "120k", "85k - 105k", "70000 USD", "€65,000", "%50,000", "65000"
    "Competitive", "DOE", "Negotiable", "$50/hr", "140,000.00", "80-90k", np.nan, "95000"
]

locations = ["New York, NY", "San Francisco, CA", "Dallas, TX", "Remote", "US", "London, UK", "Austin, TX", "Anywhere", np.nan,"Houston,TX", "Huntsville,AL"]
remote_options = ["Yes", "No", "Hybrid", "True", "False", "1", "0", "Partial", "Temporarily Remote", ]
sizes = ["10000+", "501-1000", "1-10", "Large", "Medium", "Startup", "Unknown", "500"]
experience = ["Entry-level", "Senior", "Junior", "Principal", "0-2 years", "5+ years", "Sr.", "Jr", "SE", "MI", "EN", "0-5 yrs"]
employment = ["Full-time", "Part-time", "Contract", "Temporary", "FT", "PT", "C2C", "W2", "Freelance"]
skills_pool = ["SQL", "Python", "Excel", "Tableau", "Power BI", "R", "AWS", "Google Cloud", "Azure", ""]

# 2. Helper Function for Messy Skills
def get_messy_skills():
    if random.random() < 0.05: return np.nan
    selected = random.sample(skills_pool, k=random.randint(2, 5))
    separator = random.choice([", ", ",", ";", " | ", "/", " and "])
    # Randomly return as a string list representation or just text
    return str(selected) if random.random() < 0.5 else separator.join(selected)

# 2.5 Generate 1–3 locations per row
def get_random_locations(max_locations=3):
    # Filter out NaN properly
    valid_locations = [loc for loc in locations if pd.notna(loc)]

    k = random.randint(1, max_locations)          # Choose 1 to 3
    selected = random.sample(valid_locations, k)
    return ", ".join(selected)


# 3. Generate Data Frame
mdata = {
    "job_title": [random.choice(job_titles) for _ in range(num_rows)],
    "salary": [random.choice(salaries) for _ in range(num_rows)],


    "location": [get_random_locations() for _ in range(num_rows)],
    "compnay_size": [random.choice(sizes) for _ in range(num_rows)],
    "expereince_level": [random.choice(experience) for _ in range(num_rows)],
    "employment_type": [random.choice(employment) for _ in range(num_rows)],
    "skills": [get_messy_skills() for _ in range(num_rows)]
}

df = pd.DataFrame(mdata)

# 4. Inject Chaos (Shuffling values between columns)
for i in range(num_rows):
    if random.random() < 0.01: # 1% chance to shuffle row values
        cols = list(df.columns)
        shuffled = [df.at[i, c] for c in cols]
        random.shuffle(shuffled)
        for idx, c in enumerate(cols):
            df.at[i, c] = shuffled[idx]

# Save to CSV
df.to_csv("messy_data_analyst_jobs.csv", index=False)
mdata = pd.read_csv("/content/messy_data_analyst_jobs.csv")
print("Dataset generated: messy_data_analyst_jobs.csv")

Dataset generated: messy_data_analyst_jobs.csv

In [6]:
# creating a backup of the csv file from messy_data_analyst_jobs
mdata.to_csv('backup_mdata.csv', index=False)
bdata = pd.read_csv('/content/backup_mdata.csv')

## Perform Data Exploratory Analysis (EDA)

In [7]:
# Display all columns in the dataset
mdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_title         2500 non-null   object
 1   salary            2357 non-null   object
 2   location          2499 non-null   object
 3   compnay_size      2499 non-null   object
 4   expereince_level  2498 non-null   object
 5   employment_type   2500 non-null   object
 6   skills            2389 non-null   object
dtypes: object(7)
memory usage: 136.8+ KB

In [8]:
# get first view of the dataset
mdata.head(5)

,job_title,salary,location,compnay_size,expereince_level,employment_type,skills
0,Product Data Analyst,120k,"Austin, TX, Huntsville,AL, US",Startup,Sr.,Part-time,Google Cloud;Excel;AWS;
1,DATA ANALYST,65000Competitive,"Huntsville,AL, New York, NY, Dallas, TX",501-1000,Sr.,Contract,"Python,Excel,,Google Cloud,SQL"
2,Data Analyst,65000Competitive,"Anywhere, Huntsville,AL, New York, NY",Unknown,Jr,Part-time,R/Tableau/AWS/Excel/
3,Marketing Data Analyst,NaN,"Houston,TX",501-1000,0-5 yrs,Freelance,Google Cloud;Azure
4,Data Analyst II,"€65,000","Remote, New York, NY",500,Jr,Freelance,"['Power BI', 'Azure', 'Excel', 'Google Cloud']"

In [9]:
mdata.tail(5)

,job_title,salary,location,compnay_size,expereince_level,employment_type,skills
2495,Sr. Data Analyst,65000Competitive,"US, Remote",Unknown,Sr.,Part-time,R | SQL
2496,Data Analytics Specialist,"%50,000","New York, NY, Dallas, TX",1-10,0-5 yrs,Contract,"['Google Cloud', '']"
2497,BI Analyst,$50/hr,"Houston,TX",Startup,Entry-level,PT,"['', 'Power BI', 'AWS', 'Python']"
2498,Junior Data Analyst,110000,"London, UK, New York, NY, Remote",Large,5+ years,W2,Excel;Python;Tableau;Power BI;SQL
2499,BI Analyst,"$90,000","San Francisco, CA, New York, NY",Unknown,Jr,Full-time,"['Azure', 'Power BI', 'R', 'Excel']"

In [10]:
# View only the location column
mdata.loc[:,'location'].head(20)

0                   Austin, TX, Huntsville,AL, US
1         Huntsville,AL, New York, NY, Dallas, TX
2           Anywhere, Huntsville,AL, New York, NY
3                                      Houston,TX
4                            Remote, New York, NY
5               Houston,TX, Huntsville,AL, Remote
6            Dallas, TX, New York, NY, London, UK
7                                    New York, NY
8                               San Francisco, CA
9                          Austin, TX, London, UK
10              Austin, TX, Huntsville,AL, Remote
11    New York, NY, San Francisco, CA, Houston,TX
12                     US, Houston,TX, London, UK
13                                     US, Remote
14                   Remote, Anywhere, Austin, TX
15                   New York, NY, US, Dallas, TX
16                  Houston,TX, San Francisco, CA
17              San Francisco, CA, Houston,TX, US
18                  San Francisco, CA, Houston,TX
19                                 Houston,TX, US
Name: location, dtype: object

In [11]:
# viewing multiple columns
mdata[["salary", "job_title", "location"]].head(15)

,salary,job_title,location
0,120k,Product Data Analyst,"Austin, TX, Huntsville,AL, US"
1,65000Competitive,DATA ANALYST,"Huntsville,AL, New York, NY, Dallas, TX"
2,65000Competitive,Data Analyst,"Anywhere, Huntsville,AL, New York, NY"
3,NaN,Marketing Data Analyst,"Houston,TX"
4,"€65,000",Data Analyst II,"Remote, New York, NY"
5,DOE,Senior Data Analyst,"Houston,TX, Huntsville,AL, Remote"
6,95000,Senior Data Analyst,"Dallas, TX, New York, NY, London, UK"
7,"€65,000",Sr. Data Analyst,"New York, NY"
8,120k,Marketing Data Analyst,"San Francisco, CA"
9,85k - 105k,DATA ANALYST,"Austin, TX, London, UK"
10,110000,Product Data Analyst,"Austin, TX, Huntsville,AL, Remote"
11,NaN,Marketing Data Analyst,"New York, NY, San Francisco, CA, Houston,TX"
12,70000 USD,BI Analyst,"US, Houston,TX, London, UK"
13,NaN,DATA ANALYST,"US, Remote"
14,110000,Data Analyst - Remote,"Remote, Anywhere, Austin, TX"

In [12]:
# Look through all skills
mdata['skills'].head(15)

0                            Google Cloud;Excel;AWS;
1                     Python,Excel,,Google Cloud,SQL
2                               R/Tableau/AWS/Excel/
3                                 Google Cloud;Azure
4     ['Power BI', 'Azure', 'Excel', 'Google Cloud']
5                                   Azure;R;Power BI
6                                     SQL;;AWS;Excel
7            ['R', 'Excel', 'Tableau', 'AWS', 'SQL']
8     Power BI and Azure and Google Cloud and R and
9          AWS and Tableau and Azure and R and Excel
10    ['Excel', 'SQL', 'Tableau', 'AWS', 'Power BI']
11                             ['Google Cloud', 'R']
12                                              ,AWS
13                                   SQL;AWS;Tableau
14                                Power BI,Tableau,R
Name: skills, dtype: object

## Data Cleaning

#### Clean the Skills Column

starting with the skills column
pretending that I don't know all values in the skills column
1. I need to find all values in the skills columns, then put them into a list
2. Start cleaning the the skills column,
   - start removing the special character such as `[` and `]`
   - remove all `NaN` and `Na` values and replace them with `None`

In [13]:
# Initial skills list
skills_list = ['R', 'AWS', 'Azure', 'SQL', 'Python', 'Excel', 'BI',
               'Google Cloud', 'Tableau']

# Use a set for fast duplicate checking
skills_set = set(skills_list)

# Iterate through the column and add new skills
for value in mdata['skills']:
    if pd.isna(value):           # Skip empty/NaN values
        continue
    if value in skills_list:
        skills_list.set.discard("[ ","]")
        continue
    # Only add if it doesn't exist
        skills_set.add(value)
        skills_list.append(value)   # Keep the ordered list if you want

print(skills_list)
print(f"\nTotal unique skills: {len(skills_list)}")  # We now have all the skills that in skills columns

['R', 'AWS', 'Azure', 'SQL', 'Python', 'Excel', 'BI', 'Google Cloud', 'Tableau']

Total unique skills: 9

In [14]:
# Create a function to filiter out the special character
def clean_skills(text):
  if pd.isna(text):
    return None     # returns a None value
  text = str(text)
  text = text.replace('[', '').replace(']', '').strip()   # remove '[' and ']' removes white space
  text = text.replace("'", "").replace('"', '')            # remove ' ' and " " removes white space
  text = text.replace('|', ',').strip()                    # remove '|' and replace with  ,
  text = text.replace('//', ',')                           # remove '/' and replace with  ,
  text = text.replace('/', ',')                            # remove '/' and replace with  ,
  text = text.replace('and', ',').strip()                  # remove 'and' removes white space
  text = text.replace(',,', ',')                           # remove any extra ',,' and replace with ','
  text = text.replace(';;', ',')                           # remove any extra ',,' and replace with ','
  text = text.replace(';', ',')                            # remove any extra ',,' and replace with ','
  return text

# Apply the function to the column
# mdata['skills'] = mdata['skills'].apply(clean_skills)
bdata['skills'] = bdata['skills'].apply(clean_skills)

In [15]:
# show the cleaned column in mdata
print(mdata['skills'])

0                                 Google Cloud;Excel;AWS;
1                          Python,Excel,,Google Cloud,SQL
2                                    R/Tableau/AWS/Excel/
3                                      Google Cloud;Azure
4          ['Power BI', 'Azure', 'Excel', 'Google Cloud']
5                                        Azure;R;Power BI
6                                          SQL;;AWS;Excel
7                 ['R', 'Excel', 'Tableau', 'AWS', 'SQL']
8          Power BI and Azure and Google Cloud and R and
9               AWS and Tableau and Azure and R and Excel
10         ['Excel', 'SQL', 'Tableau', 'AWS', 'Power BI']
11                                  ['Google Cloud', 'R']
12                                                   ,AWS
13                                        SQL;AWS;Tableau
14                                     Power BI,Tableau,R
15                                                    NaN
16                                       Azure and Python
17                    ['Azure', 'Python', 'AWS', 'Excel']
18                         ['Power BI', '', 'AWS', 'SQL']
19          Python and Google Cloud and Tableau and Azure
20                    Tableau | Python | Excel | Power BI
21                                    Azure/AWS//Power BI
22                                           Power BI | R
23        ['Python', 'Power BI', 'Google Cloud', 'R', '']
24                                                    NaN
25                             Power BI/Excel//Python/AWS
26                                         Azure/Tableau/
27                              ['Azure', 'Google Cloud']
28                                Excel and Azure and SQL
29                             ['Excel', 'Python', 'SQL']
30                                         SQL and Python
31                            Python/SQL/Azure/Power BI/R
32      ['AWS', 'Python', 'SQL', 'Power BI', 'Google C...
33                                    ['Power BI', 'SQL']
34                    ['Tableau', 'Python', 'SQL', 'AWS']
35                                 Tableau | R | Power BI
36                                                   SQL,
37                                   AWS;Excel;SQL;Azure;
38        ['Python', 'R', 'SQL', 'Azure', 'Google Cloud']
39               ['AWS', 'Power BI', 'Python', 'SQL', '']
40                                  ['Python', 'Tableau']
41                 ['Python', 'AWS', 'Power BI', 'Azure']
42                                         ['R', 'Azure']
43                   Azure and Excel and AWS and Power BI
44                         ['AWS', 'Google Cloud', 'SQL']
45                                 Google Cloud and Azure
46                                                  R;SQL
47                        Google Cloud, Python, , Tableau
48                                         Python | Excel
49          ['Google Cloud', 'Azure', 'Excel', 'Tableau']
50                                                     ,R
51                              ['R', 'Azure', '', 'SQL']
52                              ['Excel', 'Google Cloud']
53                                       Python and Azure
54                          ['Power BI', 'Python', 'AWS']
55                                        /Google Cloud/R
56                      ['R', 'Power BI', 'Excel', 'SQL']
57        ['SQL', 'R', 'AWS', 'Google Cloud', 'Power BI']
58                             R and Google Cloud and SQL
59                                             Python,AWS
60      ['Power BI', 'SQL', 'Google Cloud', 'Python', ...
61                                  Azure and Excel and R
62                                    Python/Google Cloud
63                  ['Excel', 'Power BI', 'Google Cloud']
64                                       ['AWS', 'Azure']
65                         ['Azure', 'SQL', 'Python', '']
66                                                    NaN
67                            Python, , R, Azure, Tableau
68                                                    NaN
69                 ['SQL', 'Excel', 'Tableau', '', 'AWS']
70                    SQL and  and Google Cloud and Excel
71                   ['Azure', 'R', 'Power BI', 'Python']
72        ['AWS', 'Azure', 'Tableau', '', 'Google Cloud']
73                                 Python/AWS//Power BI/R
74                                  Power BI,Azure,Python
75                                    ['SQL', 'Power BI']
76                            Tableau,Excel,Python,,Azure
77       ['Google Cloud', 'Power BI', 'Tableau', 'Excel']
78                           ['Azure', 'AWS', 'SQL', 'R']
79                            ['Power BI', '', 'Tableau']
80                                          AWS,Power BI,
81                                          Google Cloud;
82                     ['', 'R', 'Azure', 'SQL', 'Excel']
83                                                   /SQL
84                 ['Python', 'SQL', 'Google Cloud', 'R']
85                                                    NaN
86                                        Tableau, Python
87      Python and SQL and Excel and Google Cloud and AWS
88                                          ['Excel', '']
89                            Tableau, R, Power BI, Azure
90                                               Excel |
91                                   SQL |  | Excel | AWS
92                                        ['Python', 'R']
93                        R and Power BI and Google Cloud
94      ['Power BI', 'SQL', 'Google Cloud', 'Azure', '...
95                                              ['R', '']
96                                            ['SQL', '']
97                           Power BI and SQL and Tableau
98                        ['R', 'Excel', 'SQL', 'Python']
99                                     Python//Power BI/R
100                                        ,Excel,R,Azure
101                      ['Excel', 'SQL', 'R', 'Tableau']
102                    | SQL | Azure | Tableau | Power BI
103                                        Python | Azure
104                           ['Tableau', 'Google Cloud']
105                                Tableau/Power BI/Azure
106                                    ['SQL', '', 'AWS']
107                                      ['R', '', 'SQL']
108                                   Python,Google Cloud
109                          ['AWS', 'Excel', 'Power BI']
110                                                Excel,
111                                        Python and SQL
112                                  SQL/R/Tableau//Azure
113                  ['Tableau', 'SQL', 'Excel', 'Azure']
114                               ['', 'SQL', 'Power BI']
115     ['R', 'Azure', 'Google Cloud', 'Excel', 'Power...
116         ['Power BI', 'Excel', 'AWS', 'SQL', 'Python']
117                      ['SQL', 'Excel', 'Google Cloud']
118                      ['Google Cloud', '', 'SQL', 'R']
119                                       ['Python', 'R']
120                                       Excel | Tableau
121                                             Python/R/
122                                       ['R', 'Python']
123        ['Tableau', 'Azure', 'R', 'Excel', 'Power BI']
124                 and Google Cloud and Azure and Python
125                                          ['SQL', 'R']
126                                      Python/Azure/AWS
127                         Excel, Azure, Power BI, , AWS
128                         ['Excel', 'Google Cloud', '']
129                Azure and Excel and Tableau and Python
130                                           Power BI |
131                                     Azure | Python |
132                                  ['SQL', 'Excel', '']
133                                        Power BI,Excel
134        ['Google Cloud', 'R', 'Excel', 'Azure', 'SQL']
135                                      Azure;Python;AWS
136             ['Tableau', 'SQL', 'Azure', 'Excel', 'R']
137                       Google Cloud/R/AWS/Power BI/SQL
138                                      ['SQL', 'Excel']
139                               Google Cloud | Power BI
140                                                   NaN
141                                   Python,SQL,Power BI
142                                     Python,AWS,Azure,
143                             Python, AWS, Google Cloud
144                  ['AWS', '', 'Google Cloud', 'Azure']
145                            ['Python', 'Azure', 'AWS']
146                    ['Power BI', '', 'SQL', 'Tableau']
147                  ['', 'Tableau', 'Azure', 'Power BI']
148     ['Excel', 'Google Cloud', 'Tableau', 'Python',...
149                                ['Python', 'Power BI']
150                                              R;Azure;
151                                    Azure/Google Cloud
152                      Excel, Tableau, Power BI, AWS, R
153                         Power BI,Tableau,Azure,,Excel
154                    ['Google Cloud', 'Excel', 'R', '']
155                        ['Power BI', 'Tableau', 'SQL']
156                            Azure;Google Cloud;AWS;SQL
157       AWS | Power BI | Google Cloud | Excel | Tableau
158                        ['R', 'Tableau', '', 'Python']
159                  ['AWS', '', 'Azure', 'Google Cloud']
160                              ['Python', 'Excel', 'R']
161                                                    /R
162                                             R | Excel
163                         ['', 'AWS', 'Azure', 'Excel']
164                   ['SQL', 'Google Cloud', 'Power BI']
165                                 ['Power BI', 'Excel']
166                                 ['Power BI', 'Azure']
167                                   AWS;Python;Power BI
168                                      Google Cloud,AWS
169                                                  SQL/
170              ['Azure', 'R', 'Excel', 'Python', 'SQL']
171                                 ['Azure', 'Power BI']
172                               Excel;AWS;Google Cloud;
173                       SQL,Python,Google Cloud,Azure,R
174                                             Azure;AWS
175                                   Google Cloud,,Azure
176           ['AWS', 'Tableau', 'Azure', 'Google Cloud']
177                                             R | Excel
178                           R, Azure, SQL, Google Cloud
179                       ['Excel', 'Python', 'Power BI']
180                              ['Python', 'AWS', 'SQL']
181                                           Tableau/AWS
182                Excel | SQL | Tableau | Azure | Python
183                             ['Azure', 'AWS', 'Excel']
184     ['Tableau', 'R', 'Excel', 'Azure', 'Google Clo...
185                                   Tableau,Excel,Azure
186                       Tableau;;Excel;SQL;Google Cloud
187                             ['R', 'Tableau', 'Excel']
188                              SQL, Google Cloud, AWS,
189                               AWS/Google Cloud/Python
190                              ['AWS', 'SQL', 'Python']
191                                               R,Azure
192                       Python and Google Cloud and AWS
193                  AWS | Google Cloud | Tableau | Excel
194                                   Tableau,Excel,Azure
195                                             ;Power BI
196                                    ['Excel', '', 'R']
197                                        Tableau,R,SQL,
198     ['Tableau', 'Python', 'Azure', 'Power BI', 'SQL']
199                 ['Python', 'Tableau', 'SQL', 'Azure']
200                                    Python, Azure, R,
201               ['Excel', 'AWS', 'SQL', 'Power BI', '']
202                                   R;AWS;Python;Excel;
203                                                   NaN
204                                   ['Excel', 'Python']
205                          ['Python', '', 'R', 'Excel']
206                                                  /AWS
207       ['Azure', 'Google Cloud', 'R', 'AWS', 'Python']
208                                                   NaN
209                             ['Excel', 'AWS', '', 'R']
210                  Python, Excel, , Google Cloud, Azure
211      ['', 'AWS', 'Google Cloud', 'Power BI', 'Azure']
212                                                   NaN
213             ['Tableau', 'Python', 'Excel', '', 'AWS']
214                        Excel and Google Cloud and AWS
215                    ['', 'Azure', 'Google Cloud', 'R']
216                                   , Power BI, Tableau
217          R and Power BI and Tableau and SQL and Azure
218        ['Excel', 'Tableau', 'Python', 'Google Cloud']
219                   ['SQL', 'R', 'Google Cloud', 'AWS']
220     ['Power BI', 'Google Cloud', 'SQL', 'R', 'Azure']
221     ['AWS', 'Power BI', 'Azure', 'Google Cloud', 'R']
222     ['', 'Google Cloud', 'Power BI', 'SQL', 'Table...
223                                     ['Power BI', 'R']
224                             Tableau/Google Cloud//SQL
225                   , Excel, Google Cloud, Tableau, SQL
226                       ['Excel', 'AWS', 'Tableau', '']
227                                    SQL,Excel,R,Azure,
228                                AWS, Power BI, Tableau
229                                     | AWS | R | Excel
230                  ['Power BI', '', 'Tableau', 'Excel']
231                                  /Python/AWS/Power BI
232                      ['Power BI', '', 'Google Cloud']
233                     Power BI, SQL, Excel, Python, AWS
234                                 /Google Cloud/Tableau
235                                            BI Analyst
236              ['Excel', 'SQL', '', 'Azure', 'Tableau']
237               ['Tableau', 'Power BI', 'AWS', 'Excel']
238                                ['SQL', 'Tableau', '']
239                       ['AWS', 'Python', 'Excel', 'R']
240                                        ['Excel', 'R']
241          ['R', 'AWS', '', 'Power BI', 'Google Cloud']
242                              Google Cloud, SQL, AWS,
243                                     ['Power BI', 'R']
244                         ['AWS', '', 'Tableau', 'SQL']
245                           SQL,Tableau,Power BI,Python
246                           ['SQL', 'Tableau', 'Azure']
247        ['Tableau', 'Python', 'SQL', 'Excel', 'Azure']
248                                 Azure;SQL;;Power BI;R
249                           ['AWS', 'SQL', 'Excel', '']
250            Google Cloud,Power BI,Python,Tableau,Excel
251                            SQL;Excel;Tableau;Power BI
252                                   AWS |  | R | Python
253                                        Tableau//Excel
254                                  ['SQL', 'Excel', '']
255                                       ['Tableau', '']
256                AWS and Google Cloud and Azure and SQL
257                        Google Cloud,R,SQL,Tableau,AWS
258                                  R;Tableau;SQL;Python
259                                     Excel and Tableau
260             Excel and Tableau and SQL and Python and
261                                    ['Excel', 'Azure']
262                            ['Python', 'Google Cloud']
263                              ['Power BI', 'SQL', 'R']
264             Power BI | Azure | Google Cloud | R | SQL
265                                  Power BI/AWS/Python/
266                   ['SQL', 'AWS', 'R', 'Google Cloud']
267     ['Excel', 'Google Cloud', '', 'Azure', 'Power ...
268                                             ['', 'R']
269                      Azure,Excel,Tableau,Google Cloud
270                                   ['Excel', 'Python']
271                             ['Azure', 'Google Cloud']
272             ['', 'SQL', 'Python', 'Tableau', 'Azure']
273                                                   NaN
274                                            , Excel, R
275                    ['R', 'Excel', '', 'Google Cloud']
276                   ['Google Cloud', 'AWS', 'Power BI']
277                              ['SQL', 'R', 'Power BI']
278                    R,Power BI,AWS,Google Cloud,Python
279                                                   NaN
280                      ['Tableau', 'Power BI', 'Azure']
281                                 ['Power BI', 'Azure']
282               ['SQL', 'Power BI', 'Google Cloud', '']
283                         Azure,R,Python,Power BI,Excel
284                         and Excel and AWS and Tableau
285                     AWS | Tableau | Power BI | Python
286                                    ['Excel', 'R', '']
287                   ['Azure', 'Python', 'Excel', 'AWS']
288                       ['Excel', 'Power BI', 'Python']
289               Tableau;SQL;Excel;Power BI;Google Cloud
290           Tableau and AWS and  and Google Cloud and R
291                             ['', 'Power BI', 'Excel']
292                               and Azure and SQL and R
293                          ['Python', 'Tableau', 'SQL']
294                                    Excel,Python,Azure
295                                     Python/R/Power BI
296                        Azure | Excel | AWS | Power BI
297                ['SQL', 'Python', 'Azure', 'Power BI']
298                 ['Power BI', '', 'Excel', 'AWS', 'R']
299      ['Google Cloud', 'Azure', '', 'Python', 'Excel']
300                 ['AWS', 'Power BI', '', 'R', 'Excel']
301                              Tableau, Power BI, Excel
302        ['Excel', '', 'Python', 'Google Cloud', 'AWS']
303               ['Excel', 'Power BI', 'Tableau', 'AWS']
304                            ['Python', 'Google Cloud']
305                       /Power BI/Python/R/Google Cloud
306                                    ['SQL', 'Tableau']
307                                                   NaN
308                                            SQL;;Azure
309                 ['Tableau', 'Azure', 'AWS', 'Python']
310                          Excel,Power BI,Tableau,Azure
311                                                   NaN
312                               ['AWS', 'Excel', 'SQL']
313                   Excel,Google Cloud,AWS,Python,Azure
314                                     Azure,AWS,Tableau
315                                        ['Azure', 'R']
316             Excel | AWS | Google Cloud | SQL | Python
317                                     ['SQL', 'Python']
318                                      Tableau, , Excel
319                          R and Excel and Google Cloud
320        ['R', 'SQL', 'AWS', 'Tableau', 'Google Cloud']
321                                                   NaN
322                                          /Excel/SQL/R
323                    ['Tableau', 'Python', 'Excel', '']
324                       Azure/Python/R/Power BI/Tableau
325                    ['R', 'Google Cloud', 'Excel', '']
326                                        AWS and  and R
327          ['Excel', 'R', 'Python', 'Google Cloud', '']
328                                  ['R', '', 'Tableau']
329                                 Google Cloud,Power BI
330      ['Power BI', 'Google Cloud', 'Excel', 'AWS', '']
331                    Python, Google Cloud, AWS, Tableau
332     Power BI and Google Cloud and  and Azure and E...
333                          Power BI/Python/Tableau/AWS/
334     ['Tableau', 'Power BI', 'Google Cloud', 'Azure...
335                                          AWS/Power BI
336                                        SQL;Excel;AWS;
337                                             Excel,AWS
338                                                   NaN
339                                      ['SQL', 'Azure']
340                              Azure/Python/Tableau/SQL
341                                    SQL;R;Google Cloud
342                         and Google Cloud and Power BI
343       ['Tableau', 'SQL', 'Excel', '', 'Google Cloud']

#### Clean the Location Column

after configuring the data to only show between 1 to 3 location. Its already clean. Nothing has to be done here.

In [16]:
mdata['location'].head(15)

0                   Austin, TX, Huntsville,AL, US
1         Huntsville,AL, New York, NY, Dallas, TX
2           Anywhere, Huntsville,AL, New York, NY
3                                      Houston,TX
4                            Remote, New York, NY
5               Houston,TX, Huntsville,AL, Remote
6            Dallas, TX, New York, NY, London, UK
7                                    New York, NY
8                               San Francisco, CA
9                          Austin, TX, London, UK
10              Austin, TX, Huntsville,AL, Remote
11    New York, NY, San Francisco, CA, Houston,TX
12                     US, Houston,TX, London, UK
13                                     US, Remote
14                   Remote, Anywhere, Austin, TX
Name: location, dtype: object

#### After Cleaning the Skills & Location

In [17]:
# Current view of the dataset
mdata.head(50)

,job_title,salary,location,compnay_size,expereince_level,employment_type,skills
0,Product Data Analyst,120k,"Austin, TX, Huntsville,AL, US",Startup,Sr.,Part-time,Google Cloud;Excel;AWS;
1,DATA ANALYST,65000Competitive,"Huntsville,AL, New York, NY, Dallas, TX",501-1000,Sr.,Contract,"Python,Excel,,Google Cloud,SQL"
2,Data Analyst,65000Competitive,"Anywhere, Huntsville,AL, New York, NY",Unknown,Jr,Part-time,R/Tableau/AWS/Excel/
3,Marketing Data Analyst,NaN,"Houston,TX",501-1000,0-5 yrs,Freelance,Google Cloud;Azure
4,Data Analyst II,"€65,000","Remote, New York, NY",500,Jr,Freelance,"['Power BI', 'Azure', 'Excel', 'Google Cloud']"
5,Senior Data Analyst,DOE,"Houston,TX, Huntsville,AL, Remote",1-10,Jr,Part-time,Azure;R;Power BI
6,Senior Data Analyst,95000,"Dallas, TX, New York, NY, London, UK",Medium,Sr.,Contract,SQL;;AWS;Excel
7,Sr. Data Analyst,"€65,000","New York, NY",10000+,Jr,W2,"['R', 'Excel', 'Tableau', 'AWS', 'SQL']"
8,Marketing Data Analyst,120k,"San Francisco, CA",501-1000,5+ years,W2,Power BI and Azure and Google Cloud and R and
9,DATA ANALYST,85k - 105k,"Austin, TX, London, UK",10000+,5+ years,Freelance,AWS and Tableau and Azure and R and Excel
10,Product Data Analyst,110000,"Austin, TX, Huntsville,AL, Remote",500,5+ years,Freelance,"['Excel', 'SQL', 'Tableau', 'AWS', 'Power BI']"
11,Marketing Data Analyst,NaN,"New York, NY, San Francisco, CA, Houston,TX",Large,EN,PT,"['Google Cloud', 'R']"
12,BI Analyst,70000 USD,"US, Houston,TX, London, UK",Startup,Sr.,Part-time,",AWS"
13,DATA ANALYST,NaN,"US, Remote",Unknown,Junior,Full-time,SQL;AWS;Tableau
14,Data Analyst - Remote,110000,"Remote, Anywhere, Austin, TX",500,0-5 yrs,PT,"Power BI,Tableau,R"
15,Junior Data Analyst,Negotiable,"New York, NY, US, Dallas, TX",Medium,SE,Temporary,NaN
16,Data Analyst,$50/hr,"Houston,TX, San Francisco, CA",Large,Principal,FT,Azure and Python
17,Data Analyst,110000,"San Francisco, CA, Houston,TX, US",10000+,Principal,Freelance,"['Azure', 'Python', 'AWS', 'Excel']"
18,DATA ANALYST,DOE,"San Francisco, CA, Houston,TX",10000+,Principal,C2C,"['Power BI', '', 'AWS', 'SQL']"
19,Senior Data Analyst,DOE,"Houston,TX, US",10000+,0-5 yrs,FT,Python and Google Cloud and Tableau and Azure
20,Senior Data Analyst,70000 USD,"Anywhere, Austin, TX, Huntsville,AL",Large,Principal,Full-time,Tableau | Python | Excel | Power BI
21,BI Analyst,70000 USD,"London, UK",Unknown,MI,Part-time,Azure/AWS//Power BI
22,Data Analyst - Remote,$50/hr,"Anywhere, New York, NY",10000+,Principal,Full-time,Power BI | R
23,Data Analyst,"%50,000","San Francisco, CA, US",500,0-5 yrs,FT,"['Python', 'Power BI', 'Google Cloud', 'R', '']"
24,BI Analyst,120k,"Austin, TX",10000+,EN,Contract,NaN
25,Senior Data Analyst,"€65,000","Remote, Huntsville,AL, London, UK",Unknown,MI,FT,Power BI/Excel//Python/AWS
26,Marketing Data Analyst,85k - 105k,"London, UK, Houston,TX",Unknown,5+ years,C2C,Azure/Tableau/
27,Product Data Analyst,"%50,000","New York, NY, US, Remote",1-10,Jr,Contract,"['Azure', 'Google Cloud']"
28,Marketing Data Analyst,95000,"San Francisco, CA, Austin, TX",Unknown,SE,FT,Excel and Azure and SQL
29,BI Analyst,"$60,000 - $80,000","London, UK, San Francisco, CA, Dallas, TX",Unknown,Sr.,PT,"['Excel', 'Python', 'SQL']"
30,Junior Data Analyst,$50/hr,"London, UK, Huntsville,AL",1-10,5+ years,C2C,SQL and Python
31,Senior Data Analyst,$50/hr,"Huntsville,AL",501-1000,EN,Part-time,Python/SQL/Azure/Power BI/R
32,Data Analytics Specialist,NaN,"Dallas, TX, Remote",500,0-2 years,Freelance,"['AWS', 'Python', 'SQL', 'Power BI', 'Google C..."
33,Data Analyst - Remote,85k - 105k,"Remote, Huntsville,AL",501-1000,Principal,PT,"['Power BI', 'SQL']"
34,Data Analyst II,110000,"Remote, US, Huntsville,AL",Startup,Sr.,Part-time,"['Tableau', 'Python', 'SQL', 'AWS']"
35,Data Analyst!!!,110000,Remote,Startup,Junior,W2,Tableau | R | Power BI
36,Data Analyst,DOE,"Huntsville,AL",Large,Jr,FT,"SQL,"
37,Data Analyst!!!,"140,000.00","Dallas, TX, San Francisco, CA",Startup,Senior,FT,AWS;Excel;SQL;Azure;
38,Data Analyst!!!,95000,"San Francisco, CA",Unknown,SE,C2C,"['Python', 'R', 'SQL', 'Azure', 'Google Cloud']"
39,Sr. Data Analyst,80-90k,"Anywhere, New York, NY, Houston,TX",10000+,EN,Full-time,"['AWS', 'Power BI', 'Python', 'SQL', '']"
40,Marketing Data Analyst,80-90k,"London, UK, Huntsville,AL",Large,Jr,Full-time,"['Python', 'Tableau']"
41,Junior Data Analyst,110000,"Huntsville,AL, US",Large,0-2 years,FT,"['Python', 'AWS', 'Power BI', 'Azure']"
42,Jr. Data Analyst,85k - 105k,"Dallas, TX, Houston,TX",501-1000,MI,PT,"['R', 'Azure']"
43,Data Analyst II,Negotiable,"Austin, TX, Remote",10000+,Sr.,Contract,Azure and Excel and AWS and Power BI
44,Sr. Data Analyst,110000,"Dallas, TX, New York, NY, Austin, TX",Large,Entry-level,Part-time,"['AWS', 'Google Cloud', 'SQL']"
45,Senior Data Analyst,NaN,"Houston,TX, New York, NY",Unknown,Principal,Contract,Google Cloud and Azure
46,Data Analyst!!!,NaN,"London, UK, Austin, TX, Dallas, TX",10000+,Principal,Freelance,R;SQL
47,Jr. Data Analyst,$50/hr,"San Francisco, CA, Houston,TX",10000+,5+ years,Part-time,"Google Cloud, Python, , Tableau"
48,DATA ANALYST,85k - 105k,"London, UK, New York, NY",Large,SE,PT,Python | Excel
49,DATA ANALYST,70000 USD,Remote,10000+,Junior,Part-time,"['Google Cloud', 'Azure', 'Excel', 'Tableau']"

#### Clean the Salary Column

In [18]:
# Current view of the salary column
mdata['salary'].head(225)

0                   120k
1       65000Competitive
2       65000Competitive
3                    NaN
4                €65,000
5                    DOE
6                  95000
7                €65,000
8                   120k
9             85k - 105k
10                110000
11                   NaN
12             70000 USD
13                   NaN
14                110000
15            Negotiable
16                $50/hr
17                110000
18                   DOE
19                   DOE
20             70000 USD
21             70000 USD
22                $50/hr
23               %50,000
24                  120k
25               €65,000
26            85k - 105k
27               %50,000
28                 95000
29     $60,000 - $80,000
30                $50/hr
31                $50/hr
32                   NaN
33            85k - 105k
34                110000
35                110000
36                   DOE
37            140,000.00
38                 95000
39                80-90k
40                80-90k
41                110000
42            85k - 105k
43            Negotiable
44                110000
45                   NaN
46                   NaN
47                $50/hr
48            85k - 105k
49             70000 USD
50            85k - 105k
51                80-90k
52               $90,000
53                  120k
54            85k - 105k
55                   DOE
56             70000 USD
57             70000 USD
58            Negotiable
59               %50,000
60                $50/hr
61                   DOE
62                110000
63      65000Competitive
64               €65,000
65      65000Competitive
66            85k - 105k
67                   DOE
68                110000
69             70000 USD
70            85k - 105k
71             70000 USD
72            Negotiable
73               $90,000
74     $60,000 - $80,000
75                110000
76               $90,000
77      65000Competitive
78               €65,000
79                80-90k
80     $60,000 - $80,000
81                 95000
82                   DOE
83                   DOE
84                 95000
85               %50,000
86            140,000.00
87                   DOE
88                   NaN
89                110000
90               $90,000
91             70000 USD
92                   NaN
93                80-90k
94                 95000
95                   NaN
96               €65,000
97            Negotiable
98            85k - 105k
99            Negotiable
100           Negotiable
101               $50/hr
102           140,000.00
103           85k - 105k
104               $50/hr
105                 120k
106           Negotiable
107              %50,000
108                  NaN
109                 120k
110     65000Competitive
111                  NaN
112              %50,000
113           85k - 105k
114                 120k
115              $90,000
116                  DOE
117           140,000.00
118               80-90k
119              %50,000
120            70000 USD
121           Negotiable
122           Negotiable
123              €65,000
124            70000 USD
125                95000
126                  NaN
127                95000
128                  DOE
129                95000
130    $60,000 - $80,000
131               110000
132           140,000.00
133                  NaN
134              %50,000
135              €65,000
136               $50/hr
137              $90,000
138              $90,000
139                  DOE
140                95000
141                95000
142                  DOE
143    $60,000 - $80,000
144                 120k
145               80-90k
146           85k - 105k
147     65000Competitive
148               $50/hr
149           140,000.00
150               $50/hr
151              $90,000
152           140,000.00
153              $90,000
154              €65,000
155               $50/hr
156                  DOE
157               110000
158           140,000.00
159                  NaN
160     65000Competitive
161                 120k
162           85k - 105k
163                 120k
164           140,000.00
165               $50/hr
166           Negotiable
167               $50/hr
168           85k - 105k
169              €65,000
170           140,000.00
171              $90,000
172              $90,000
173              $90,000
174           85k - 105k
175           Negotiable
176                95000
177                  NaN
178           85k - 105k
179           85k - 105k
180           Negotiable
181           Negotiable
182            70000 USD
183           140,000.00
184                  DOE
185           Negotiable
186                95000
187                  DOE
188                95000
189    $60,000 - $80,000
190               $50/hr
191           Negotiable
192                 120k
193               80-90k
194                  DOE
195    $60,000 - $80,000
196                95000
197     65000Competitive
198              %50,000
199              $90,000
200                95000
201            70000 USD
202           140,000.00
203           85k - 105k
204              %50,000
205              $90,000
206                 120k
207              €65,000
208    $60,000 - $80,000
209                  NaN
210           Negotiable
211               80-90k
212           85k - 105k
213               80-90k
214              €65,000
215               80-90k
216                95000
217              $90,000
218           85k - 105k
219              €65,000
220           Negotiable
221                95000
222           140,000.00
223           Negotiable
224            70000 USD
Name: salary, dtype: object

In [19]:
bdata['salary'].head(225)

0                   120k
1       65000Competitive
2       65000Competitive
3                    NaN
4                €65,000
5                    DOE
6                  95000
7                €65,000
8                   120k
9             85k - 105k
10                110000
11                   NaN
12             70000 USD
13                   NaN
14                110000
15            Negotiable
16                $50/hr
17                110000
18                   DOE
19                   DOE
20             70000 USD
21             70000 USD
22                $50/hr
23               %50,000
24                  120k
25               €65,000
26            85k - 105k
27               %50,000
28                 95000
29     $60,000 - $80,000
30                $50/hr
31                $50/hr
32                   NaN
33            85k - 105k
34                110000
35                110000
36                   DOE
37            140,000.00
38                 95000
39                80-90k
40                80-90k
41                110000
42            85k - 105k
43            Negotiable
44                110000
45                   NaN
46                   NaN
47                $50/hr
48            85k - 105k
49             70000 USD
50            85k - 105k
51                80-90k
52               $90,000
53                  120k
54            85k - 105k
55                   DOE
56             70000 USD
57             70000 USD
58            Negotiable
59               %50,000
60                $50/hr
61                   DOE
62                110000
63      65000Competitive
64               €65,000
65      65000Competitive
66            85k - 105k
67                   DOE
68                110000
69             70000 USD
70            85k - 105k
71             70000 USD
72            Negotiable
73               $90,000
74     $60,000 - $80,000
75                110000
76               $90,000
77      65000Competitive
78               €65,000
79                80-90k
80     $60,000 - $80,000
81                 95000
82                   DOE
83                   DOE
84                 95000
85               %50,000
86            140,000.00
87                   DOE
88                   NaN
89                110000
90               $90,000
91             70000 USD
92                   NaN
93                80-90k
94                 95000
95                   NaN
96               €65,000
97            Negotiable
98            85k - 105k
99            Negotiable
100           Negotiable
101               $50/hr
102           140,000.00
103           85k - 105k
104               $50/hr
105                 120k
106           Negotiable
107              %50,000
108                  NaN
109                 120k
110     65000Competitive
111                  NaN
112              %50,000
113           85k - 105k
114                 120k
115              $90,000
116                  DOE
117           140,000.00
118               80-90k
119              %50,000
120            70000 USD
121           Negotiable
122           Negotiable
123              €65,000
124            70000 USD
125                95000
126                  NaN
127                95000
128                  DOE
129                95000
130    $60,000 - $80,000
131               110000
132           140,000.00
133                  NaN
134              %50,000
135              €65,000
136               $50/hr
137              $90,000
138              $90,000
139                  DOE
140                95000
141                95000
142                  DOE
143    $60,000 - $80,000
144                 120k
145               80-90k
146           85k - 105k
147     65000Competitive
148               $50/hr
149           140,000.00
150               $50/hr
151              $90,000
152           140,000.00
153              $90,000
154              €65,000
155               $50/hr
156                  DOE
157               110000
158           140,000.00
159                  NaN
160     65000Competitive
161                 120k
162           85k - 105k
163                 120k
164           140,000.00
165               $50/hr
166           Negotiable
167               $50/hr
168           85k - 105k
169              €65,000
170           140,000.00
171              $90,000
172              $90,000
173              $90,000
174           85k - 105k
175           Negotiable
176                95000
177                  NaN
178           85k - 105k
179           85k - 105k
180           Negotiable
181           Negotiable
182            70000 USD
183           140,000.00
184                  DOE
185           Negotiable
186                95000
187                  DOE
188                95000
189    $60,000 - $80,000
190               $50/hr
191           Negotiable
192                 120k
193               80-90k
194                  DOE
195    $60,000 - $80,000
196                95000
197     65000Competitive
198              %50,000
199              $90,000
200                95000
201            70000 USD
202           140,000.00
203           85k - 105k
204              %50,000
205              $90,000
206                 120k
207              €65,000
208    $60,000 - $80,000
209                  NaN
210           Negotiable
211               80-90k
212           85k - 105k
213               80-90k
214              €65,000
215               80-90k
216                95000
217              $90,000
218           85k - 105k
219              €65,000
220           Negotiable
221                95000
222           140,000.00
223           Negotiable
224            70000 USD
Name: salary, dtype: object

In [20]:
def clean_salary(text):
    if pd.isna(text):
        return 0

    text = str(text).strip()

    # Special cases for Words
    if any(x in text.upper() for x in ['DOE', 'Negotiable', 'Competitive']):
        return 0


    replacements = [
        # ('NaN', '0'),
        ('65000Competitive', '65000'),
        ('€', ''),
        ('$', ''),
        ('%', ''),
        ('120K', '120000'),
        ('120k', '120000'),
        ('70000 USD', '70000'),
        ('$50/hr', '104000'),     # 50 * 2080
        (',', ''),
        ('K', '000'),
        ('k', '000'),
    ]
    for old, new in replacements:
        text = text.replace(old, new)

    # Keep only digits
    text = ''.join(filter(str.isdigit, text))

    try:
        return int(text) if text else 0
    except:
        return 0

# Apply the function to the column
bdata['salary'] = mdata['salary'].apply(clean_salary)

In [21]:
# Special Case : for two number stuck together
double_values = ['85000105000', '6000080000']

# Create a function that targets column
def concatenated_salary(salary):
    salary_str = str(salary).strip()

    if salary_str == '85000105000':
        num1 = 85000
        num2 = 105000
        val = statistics.median([num1, num2])
        return val

    elif salary_str == '6000080000':
        num1 = 60000
        num2 = 80000
        val = statistics.median([num1, num2])
        return val
    else:
        return salary_str

# Apply the fix
bdata['salary'] = bdata['salary'].apply(concatenated_salary)

In [22]:
bdata.head(10)

,job_title,salary,location,compnay_size,expereince_level,employment_type,skills
0,Product Data Analyst,120000,"Austin, TX, Huntsville,AL, US",Startup,Sr.,Part-time,"Google Cloud,Excel,AWS,"
1,DATA ANALYST,65000,"Huntsville,AL, New York, NY, Dallas, TX",501-1000,Sr.,Contract,"Python,Excel,Google Cloud,SQL"
2,Data Analyst,65000,"Anywhere, Huntsville,AL, New York, NY",Unknown,Jr,Part-time,"R,Tableau,AWS,Excel,"
3,Marketing Data Analyst,0,"Houston,TX",501-1000,0-5 yrs,Freelance,"Google Cloud,Azure"
4,Data Analyst II,65000,"Remote, New York, NY",500,Jr,Freelance,"Power BI, Azure, Excel, Google Cloud"
5,Senior Data Analyst,0,"Houston,TX, Huntsville,AL, Remote",1-10,Jr,Part-time,"Azure,R,Power BI"
6,Senior Data Analyst,95000,"Dallas, TX, New York, NY, London, UK",Medium,Sr.,Contract,"SQL,AWS,Excel"
7,Sr. Data Analyst,65000,"New York, NY",10000+,Jr,W2,"R, Excel, Tableau, AWS, SQL"
8,Marketing Data Analyst,120000,"San Francisco, CA",501-1000,5+ years,W2,"Power BI , Azure , Google Cloud , R ,"
9,DATA ANALYST,95000.0,"Austin, TX, London, UK",10000+,5+ years,Freelance,"AWS , Tableau , Azure , R , Excel"

In [23]:
bdata.tail(15)

,job_title,salary,location,compnay_size,expereince_level,employment_type,skills
2485,BI Analyst,90000,"Remote, New York, NY",1-10,Jr,Full-time,"SQL,Tableau"
2486,Jr. Data Analyst,70000,"Houston,TX, London, UK, New York, NY",Startup,Principal,Part-time,"Python,SQL,Google Cloud,"
2487,Junior Data Analyst,14000000,US,10000+,Entry-level,W2,"R, Power BI, Excel"
2488,Jr. Data Analyst,70000.0,"Austin, TX, London, UK",Unknown,MI,Freelance,"Azure , Tableau , Excel , , AWS"
2489,Product Data Analyst,110000,"Dallas, TX",Medium,5+ years,C2C,", Azure, R"
2490,Data Analyst II,95000.0,"San Francisco, CA, Houston,TX",1-10,Entry-level,W2,"Azure,Excel"
2491,Senior Data Analyst,95000,"Remote, Houston,TX, US",10000+,EN,W2,"Excel, Google Cloud, AWS"
2492,DATA ANALYST,8090000,"Huntsville,AL, New York, NY",500,5+ years,Freelance,"Power BI , Excel"
2493,Data Analyst,110000,"San Francisco, CA, Anywhere, US",Unknown,EN,Contract,"Tableau, Python, R, Power BI, Azure"
2494,Marketing Data Analyst,110000,"New York, NY, Huntsville,AL, London, UK",Large,5+ years,Temporary,"Python, Tableau, R"
2495,Sr. Data Analyst,65000,"US, Remote",Unknown,Sr.,Part-time,"R , SQL"
2496,Data Analytics Specialist,50000,"New York, NY, Dallas, TX",1-10,0-5 yrs,Contract,"Google Cloud,"
2497,BI Analyst,50,"Houston,TX",Startup,Entry-level,PT,", Power BI, AWS, Python"
2498,Junior Data Analyst,110000,"London, UK, New York, NY, Remote",Large,5+ years,W2,"Excel,Python,Tableau,Power BI,SQL"
2499,BI Analyst,90000,"San Francisco, CA, New York, NY",Unknown,Jr,Full-time,"Azure, Power BI, R, Excel"

In [24]:
bdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_title         2500 non-null   object
 1   salary            2500 non-null   object
 2   location          2499 non-null   object
 3   compnay_size      2499 non-null   object
 4   expereince_level  2498 non-null   object
 5   employment_type   2500 non-null   object
 6   skills            2389 non-null   object
dtypes: object(7)
memory usage: 136.8+ KB

### Cleaning the Experience Level

Cleaning the expereince level we will

Assigning each level a number of experience
1. Pr = 4  (Highest)
2. Sr = 3
3. Mi = 2
4. Jr = 1  (Lowest)

Things to be done in the `expereince_level` column
1.   Remove any special character from the column
2.   Create a new column and assign numbers to new column called `experience_level_values`, this new column will be use for training our model
3.   Convert `5+ years` to `Mid`
4.   Convert `Principal` to `Pr`
5.   Convert `0-5 years` to `Jr`
6.   Convert `0-2 years` to Jr
8.   Convert `SE` to `Sr`
9.   Convert `MI` to `Mi`

In [25]:
# Rename the 'compnay_size' to 'company_size' & 'expereince_level' to 'experience_level'
bdata.rename(columns={'compnay_size': 'company_size', 'expereince_level': 'experience_level'}, inplace=True)  # Set inplace= True to save the changes

In [26]:
# 1. Reload bdata to fix the 'Series' overwrite issue
# bdata = pd.read_csv('/content/backup_mdata.csv')

# 2. We assign the result back to the specific column, not the whole dataframe variable
bdata['experience_level'] = bdata['experience_level'].replace({
    '0-5 yrs': 'Jr',
    '5+ years': 'Mi',
    '0-2 years': 'Jr',
    'Principal': 'Pr',
    'Sr.': 'Sr',
    'SE': 'Sr',
    'MI': 'Mi',
    'EN': 'None',
    'Junior': 'Jr',
    'Senior': 'Sr',
    'Nan': 'None',
    'Entry-level': 'Jr'
})

# 3. View the results
bdata['experience_level'].head(35)

0       Sr
1       Sr
2       Jr
3       Jr
4       Jr
5       Jr
6       Sr
7       Jr
8       Mi
9       Mi
10      Mi
11    None
12      Sr
13      Jr
14      Jr
15      Sr
16      Pr
17      Pr
18      Pr
19      Jr
20      Pr
21      Mi
22      Pr
23      Jr
24    None
25      Mi
26      Mi
27      Jr
28      Sr
29      Sr
30      Mi
31    None
32      Jr
33      Pr
34      Sr
Name: experience_level, dtype: object

In [27]:
bdata.head(15)

,job_title,salary,location,company_size,experience_level,employment_type,skills
0,Product Data Analyst,120000,"Austin, TX, Huntsville,AL, US",Startup,Sr,Part-time,"Google Cloud,Excel,AWS,"
1,DATA ANALYST,65000,"Huntsville,AL, New York, NY, Dallas, TX",501-1000,Sr,Contract,"Python,Excel,Google Cloud,SQL"
2,Data Analyst,65000,"Anywhere, Huntsville,AL, New York, NY",Unknown,Jr,Part-time,"R,Tableau,AWS,Excel,"
3,Marketing Data Analyst,0,"Houston,TX",501-1000,Jr,Freelance,"Google Cloud,Azure"
4,Data Analyst II,65000,"Remote, New York, NY",500,Jr,Freelance,"Power BI, Azure, Excel, Google Cloud"
5,Senior Data Analyst,0,"Houston,TX, Huntsville,AL, Remote",1-10,Jr,Part-time,"Azure,R,Power BI"
6,Senior Data Analyst,95000,"Dallas, TX, New York, NY, London, UK",Medium,Sr,Contract,"SQL,AWS,Excel"
7,Sr. Data Analyst,65000,"New York, NY",10000+,Jr,W2,"R, Excel, Tableau, AWS, SQL"
8,Marketing Data Analyst,120000,"San Francisco, CA",501-1000,Mi,W2,"Power BI , Azure , Google Cloud , R ,"
9,DATA ANALYST,95000.0,"Austin, TX, London, UK",10000+,Mi,Freelance,"AWS , Tableau , Azure , R , Excel"
10,Product Data Analyst,110000,"Austin, TX, Huntsville,AL, Remote",500,Mi,Freelance,"Excel, SQL, Tableau, AWS, Power BI"
11,Marketing Data Analyst,0,"New York, NY, San Francisco, CA, Houston,TX",Large,None,PT,"Google Cloud, R"
12,BI Analyst,70000,"US, Houston,TX, London, UK",Startup,Sr,Part-time,",AWS"
13,DATA ANALYST,0,"US, Remote",Unknown,Jr,Full-time,"SQL,AWS,Tableau"
14,Data Analyst - Remote,110000,"Remote, Anywhere, Austin, TX",500,Jr,PT,"Power BI,Tableau,R"

In [28]:
# Map new values
mapping = {'Pr': 4, 'Sr': 3, 'Mi': 2, 'Jr': 1}

# # Create a new column in bdata and map values to 'expereince_level_values`
bdata['experience_level_value'] = bdata['experience_level'].map(mapping).fillna(0).astype(int)

In [29]:
# Shows the new column
# bdata['expereince_level_value'].tail(25)

In [30]:
# Show the current view of the table so far
bdata.head(10)

,job_title,salary,location,company_size,experience_level,employment_type,skills,experience_level_value
0,Product Data Analyst,120000,"Austin, TX, Huntsville,AL, US",Startup,Sr,Part-time,"Google Cloud,Excel,AWS,",3
1,DATA ANALYST,65000,"Huntsville,AL, New York, NY, Dallas, TX",501-1000,Sr,Contract,"Python,Excel,Google Cloud,SQL",3
2,Data Analyst,65000,"Anywhere, Huntsville,AL, New York, NY",Unknown,Jr,Part-time,"R,Tableau,AWS,Excel,",1
3,Marketing Data Analyst,0,"Houston,TX",501-1000,Jr,Freelance,"Google Cloud,Azure",1
4,Data Analyst II,65000,"Remote, New York, NY",500,Jr,Freelance,"Power BI, Azure, Excel, Google Cloud",1
5,Senior Data Analyst,0,"Houston,TX, Huntsville,AL, Remote",1-10,Jr,Part-time,"Azure,R,Power BI",1
6,Senior Data Analyst,95000,"Dallas, TX, New York, NY, London, UK",Medium,Sr,Contract,"SQL,AWS,Excel",3
7,Sr. Data Analyst,65000,"New York, NY",10000+,Jr,W2,"R, Excel, Tableau, AWS, SQL",1
8,Marketing Data Analyst,120000,"San Francisco, CA",501-1000,Mi,W2,"Power BI , Azure , Google Cloud , R ,",2
9,DATA ANALYST,95000.0,"Austin, TX, London, UK",10000+,Mi,Freelance,"AWS , Tableau , Azure , R , Excel",2

### Cleaning the Company Size

To clean the company size column, we


1.  Rename `compnay_size` to `company_size`
2.  Come up with a way to distinguish the length of the company size
3.  Remove any special character from column such as `-`,`+`,`
4.  Remove any words such as `Startup`,`Unknown`,`Medium` and `Large`

In [31]:
bdata['company_size'].head(100)

0      Startup
1     501-1000
2      Unknown
3     501-1000
4          500
5         1-10
6       Medium
7       10000+
8     501-1000
9       10000+
10         500
11       Large
12     Startup
13     Unknown
14         500
15      Medium
16       Large
17      10000+
18      10000+
19      10000+
20       Large
21     Unknown
22      10000+
23         500
24      10000+
25     Unknown
26     Unknown
27        1-10
28     Unknown
29     Unknown
30        1-10
31    501-1000
32         500
33    501-1000
34     Startup
35     Startup
36       Large
37     Startup
38     Unknown
39      10000+
40       Large
41       Large
42    501-1000
43      10000+
44       Large
45     Unknown
46      10000+
47      10000+
48       Large
49      10000+
50    501-1000
51      10000+
52        1-10
53         500
54        1-10
55      Medium
56      10000+
57     Startup
58     Startup
59       Large
60      Medium
61        1-10
62     Unknown
63         500
64    501-1000
65    501-1000
66    501-1000
67      Medium
68       Large
69         500
70     Startup
71       Large
72         500
73      Medium
74     Startup
75      Medium
76       Large
77      Medium
78     Startup
79    501-1000
80      10000+
81     Startup
82     Unknown
83         500
84      Medium
85    501-1000
86       Large
87        1-10
88       Large
89      Medium
90       Large
91    501-1000
92     Startup
93        1-10
94      10000+
95       Large
96         500
97         500
98    501-1000
99      10000+
Name: company_size, dtype: object

In [32]:
# Create a function to clean the Company Column
def clean_company_size(company_size):

    # Map any words such as 'Startup', 'Unknown','Medium' and 'Large'
    mapping = {
        '501-1000': 'Large',
        '500': 'Small',
        '1-10': 'Startup',
        '10000+': 'Huge'
    }
    # Return the mapped value or the original if not in mapping
    return mapping.get(str(company_size), company_size)

# Apply the function to bdata dataframe
bdata['company_size'] = bdata['company_size'].apply(clean_company_size)

In [33]:
# Create a new column called 'company_size_value' based on `company_size'
# Map new values
mapping = {'Unknown': 0, 'Startup': 1, 'Medium': 2, 'Large': 3, 'Huge': 4}

# # Create a new column in bdata and map values to 'expereince_level_values`
bdata['company_size_value'] = bdata['company_size'].map(mapping).fillna(0).astype(int)

In [34]:
bdata.head(15)

,job_title,salary,location,company_size,experience_level,employment_type,skills,experience_level_value,company_size_value
0,Product Data Analyst,120000,"Austin, TX, Huntsville,AL, US",Startup,Sr,Part-time,"Google Cloud,Excel,AWS,",3,1
1,DATA ANALYST,65000,"Huntsville,AL, New York, NY, Dallas, TX",Large,Sr,Contract,"Python,Excel,Google Cloud,SQL",3,3
2,Data Analyst,65000,"Anywhere, Huntsville,AL, New York, NY",Unknown,Jr,Part-time,"R,Tableau,AWS,Excel,",1,0
3,Marketing Data Analyst,0,"Houston,TX",Large,Jr,Freelance,"Google Cloud,Azure",1,3
4,Data Analyst II,65000,"Remote, New York, NY",Small,Jr,Freelance,"Power BI, Azure, Excel, Google Cloud",1,0
5,Senior Data Analyst,0,"Houston,TX, Huntsville,AL, Remote",Startup,Jr,Part-time,"Azure,R,Power BI",1,1
6,Senior Data Analyst,95000,"Dallas, TX, New York, NY, London, UK",Medium,Sr,Contract,"SQL,AWS,Excel",3,2
7,Sr. Data Analyst,65000,"New York, NY",Huge,Jr,W2,"R, Excel, Tableau, AWS, SQL",1,4
8,Marketing Data Analyst,120000,"San Francisco, CA",Large,Mi,W2,"Power BI , Azure , Google Cloud , R ,",2,3
9,DATA ANALYST,95000.0,"Austin, TX, London, UK",Huge,Mi,Freelance,"AWS , Tableau , Azure , R , Excel",2,4
10,Product Data Analyst,110000,"Austin, TX, Huntsville,AL, Remote",Small,Mi,Freelance,"Excel, SQL, Tableau, AWS, Power BI",2,0
11,Marketing Data Analyst,0,"New York, NY, San Francisco, CA, Houston,TX",Large,None,PT,"Google Cloud, R",0,3
12,BI Analyst,70000,"US, Houston,TX, London, UK",Startup,Sr,Part-time,",AWS",3,1
13,DATA ANALYST,0,"US, Remote",Unknown,Jr,Full-time,"SQL,AWS,Tableau",1,0
14,Data Analyst - Remote,110000,"Remote, Anywhere, Austin, TX",Small,Jr,PT,"Power BI,Tableau,R",1,0

### Cleaning Employment Type

To clean the `employment_type` column

1. Generate a list of `employment_type` to convert to number values
2. Convert `FT` to `Full Time`
3. Convert `C2C` to
4. Convert `PT` to `Part-time`
5. Convert `W2` to `Reguler`

In [35]:
bdata.head(25)

,job_title,salary,location,company_size,experience_level,employment_type,skills,experience_level_value,company_size_value
0,Product Data Analyst,120000,"Austin, TX, Huntsville,AL, US",Startup,Sr,Part-time,"Google Cloud,Excel,AWS,",3,1
1,DATA ANALYST,65000,"Huntsville,AL, New York, NY, Dallas, TX",Large,Sr,Contract,"Python,Excel,Google Cloud,SQL",3,3
2,Data Analyst,65000,"Anywhere, Huntsville,AL, New York, NY",Unknown,Jr,Part-time,"R,Tableau,AWS,Excel,",1,0
3,Marketing Data Analyst,0,"Houston,TX",Large,Jr,Freelance,"Google Cloud,Azure",1,3
4,Data Analyst II,65000,"Remote, New York, NY",Small,Jr,Freelance,"Power BI, Azure, Excel, Google Cloud",1,0
5,Senior Data Analyst,0,"Houston,TX, Huntsville,AL, Remote",Startup,Jr,Part-time,"Azure,R,Power BI",1,1
6,Senior Data Analyst,95000,"Dallas, TX, New York, NY, London, UK",Medium,Sr,Contract,"SQL,AWS,Excel",3,2
7,Sr. Data Analyst,65000,"New York, NY",Huge,Jr,W2,"R, Excel, Tableau, AWS, SQL",1,4
8,Marketing Data Analyst,120000,"San Francisco, CA",Large,Mi,W2,"Power BI , Azure , Google Cloud , R ,",2,3
9,DATA ANALYST,95000.0,"Austin, TX, London, UK",Huge,Mi,Freelance,"AWS , Tableau , Azure , R , Excel",2,4
10,Product Data Analyst,110000,"Austin, TX, Huntsville,AL, Remote",Small,Mi,Freelance,"Excel, SQL, Tableau, AWS, Power BI",2,0
11,Marketing Data Analyst,0,"New York, NY, San Francisco, CA, Houston,TX",Large,None,PT,"Google Cloud, R",0,3
12,BI Analyst,70000,"US, Houston,TX, London, UK",Startup,Sr,Part-time,",AWS",3,1
13,DATA ANALYST,0,"US, Remote",Unknown,Jr,Full-time,"SQL,AWS,Tableau",1,0
14,Data Analyst - Remote,110000,"Remote, Anywhere, Austin, TX",Small,Jr,PT,"Power BI,Tableau,R",1,0
15,Junior Data Analyst,0,"New York, NY, US, Dallas, TX",Medium,Sr,Temporary,None,3,2
16,Data Analyst,50,"Houston,TX, San Francisco, CA",Large,Pr,FT,"Azure , Python",4,3
17,Data Analyst,110000,"San Francisco, CA, Houston,TX, US",Huge,Pr,Freelance,"Azure, Python, AWS, Excel",4,4
18,DATA ANALYST,0,"San Francisco, CA, Houston,TX",Huge,Pr,C2C,"Power BI, , AWS, SQL",4,4
19,Senior Data Analyst,0,"Houston,TX, US",Huge,Jr,FT,"Python , Google Cloud , Tableau , Azure",1,4
20,Senior Data Analyst,70000,"Anywhere, Austin, TX, Huntsville,AL",Large,Pr,Full-time,"Tableau , Python , Excel , Power BI",4,3
21,BI Analyst,70000,"London, UK",Unknown,Mi,Part-time,"Azure,AWS,Power BI",2,0
22,Data Analyst - Remote,50,"Anywhere, New York, NY",Huge,Pr,Full-time,"Power BI , R",4,4
23,Data Analyst,50000,"San Francisco, CA, US",Small,Jr,FT,"Python, Power BI, Google Cloud, R,",1,0
24,BI Analyst,120000,"Austin, TX",Huge,None,Contract,None,0,4

In [36]:
bdata['employment_type'].head(45)

0     Part-time
1      Contract
2     Part-time
3     Freelance
4     Freelance
5     Part-time
6      Contract
7            W2
8            W2
9     Freelance
10    Freelance
11           PT
12    Part-time
13    Full-time
14           PT
15    Temporary
16           FT
17    Freelance
18          C2C
19           FT
20    Full-time
21    Part-time
22    Full-time
23           FT
24     Contract
25           FT
26          C2C
27     Contract
28           FT
29           PT
30          C2C
31    Part-time
32    Freelance
33           PT
34    Part-time
35           W2
36           FT
37           FT
38          C2C
39    Full-time
40    Full-time
41           FT
42           PT
43     Contract
44    Part-time
Name: employment_type, dtype: object

In [37]:
bdata['employment_type'].tail(50)

2450                                           Full-time
2451                                                 C2C
2452                                            Contract
2453                                            Contract
2454                                           Part-time
2455                                            Contract
2456                                            Contract
2457                                                  FT
2458                                            Contract
2459                                                  W2
2460                                                 C2C
2461                                                  W2
2462                                                  W2
2463                                                  FT
2464                                                 C2C
2465                                            Contract
2466                                                  PT
2467                                           Part-time
2468                                                 C2C
2469                                           Full-time
2470                                           Part-time
2471                                           Part-time
2472                                            Contract
2473                                                  FT
2474                                           Part-time
2475                                           Part-time
2476                                                  PT
2477                                           Freelance
2478                                                  FT
2479    ['Excel', 'AWS', 'Google Cloud', 'Azure', 'SQL']
2480                                           Freelance
2481                                                 C2C
2482                                           Full-time
2483                                           Full-time
2484                                           Freelance
2485                                           Full-time
2486                                           Part-time
2487                                                  W2
2488                                           Freelance
2489                                                 C2C
2490                                                  W2
2491                                                  W2
2492                                           Freelance
2493                                            Contract
2494                                           Temporary
2495                                           Part-time
2496                                            Contract
2497                                                  PT
2498                                                  W2
2499                                           Full-time
Name: employment_type, dtype: object

In [38]:
# Create a function for employment_type
def clean_employment_type(employment_type):
    # Mapping from abbreviations to full names
    mapping = {
        'FT': 'Full-time',
        'PT': 'Part-time',
        'W2': 'Regular',
        'C2C': 'Contract'
    }

    # First apply mapping (if it exists)
    cleaned = mapping.get(employment_type, employment_type)

    # Allowed values after cleaning
    allowed_types = ['Full-time', 'Part-time', 'Regular', 'Contract', 'Freelance', 'Temporary']


    # If value (after mapping) is allowed, keep it. Otherwise return None.
    if cleaned in allowed_types:
        return cleaned
    else:
        return None

# Apply the function
bdata['employment_type'] = bdata['employment_type'].apply(clean_employment_type)

### Quick Check on the Dataframe

Everything seems to be in order, we are almost done.

In [42]:
bdata.head(25)

,job_title,salary,location,company_size,experience_level,employment_type,skills,experience_level_value,company_size_value
0,Product Data Analyst,120000,"Austin, TX, Huntsville,AL, US",Startup,Sr,Part-time,"Google Cloud,Excel,AWS,",3,1
1,DATA ANALYST,65000,"Huntsville,AL, New York, NY, Dallas, TX",Large,Sr,Contract,"Python,Excel,Google Cloud,SQL",3,3
2,Data Analyst,65000,"Anywhere, Huntsville,AL, New York, NY",Unknown,Jr,Part-time,"R,Tableau,AWS,Excel,",1,0
3,Marketing Data Analyst,0,"Houston,TX",Large,Jr,Freelance,"Google Cloud,Azure",1,3
4,Data Analyst II,65000,"Remote, New York, NY",Small,Jr,Freelance,"Power BI, Azure, Excel, Google Cloud",1,0
5,Senior Data Analyst,0,"Houston,TX, Huntsville,AL, Remote",Startup,Jr,Part-time,"Azure,R,Power BI",1,1
6,Senior Data Analyst,95000,"Dallas, TX, New York, NY, London, UK",Medium,Sr,Contract,"SQL,AWS,Excel",3,2
7,Sr. Data Analyst,65000,"New York, NY",Huge,Jr,Regular,"R, Excel, Tableau, AWS, SQL",1,4
8,Marketing Data Analyst,120000,"San Francisco, CA",Large,Mi,Regular,"Power BI , Azure , Google Cloud , R ,",2,3
9,DATA ANALYST,95000.0,"Austin, TX, London, UK",Huge,Mi,Freelance,"AWS , Tableau , Azure , R , Excel",2,4
10,Product Data Analyst,110000,"Austin, TX, Huntsville,AL, Remote",Small,Mi,Freelance,"Excel, SQL, Tableau, AWS, Power BI",2,0
11,Marketing Data Analyst,0,"New York, NY, San Francisco, CA, Houston,TX",Large,None,Part-time,"Google Cloud, R",0,3
12,BI Analyst,70000,"US, Houston,TX, London, UK",Startup,Sr,Part-time,",AWS",3,1
13,DATA ANALYST,0,"US, Remote",Unknown,Jr,Full-time,"SQL,AWS,Tableau",1,0
14,Data Analyst - Remote,110000,"Remote, Anywhere, Austin, TX",Small,Jr,Part-time,"Power BI,Tableau,R",1,0
15,Junior Data Analyst,0,"New York, NY, US, Dallas, TX",Medium,Sr,Temporary,None,3,2
16,Data Analyst,50,"Houston,TX, San Francisco, CA",Large,Pr,Full-time,"Azure , Python",4,3
17,Data Analyst,110000,"San Francisco, CA, Houston,TX, US",Huge,Pr,Freelance,"Azure, Python, AWS, Excel",4,4
18,DATA ANALYST,0,"San Francisco, CA, Houston,TX",Huge,Pr,Contract,"Power BI, , AWS, SQL",4,4
19,Senior Data Analyst,0,"Houston,TX, US",Huge,Jr,Full-time,"Python , Google Cloud , Tableau , Azure",1,4
20,Senior Data Analyst,70000,"Anywhere, Austin, TX, Huntsville,AL",Large,Pr,Full-time,"Tableau , Python , Excel , Power BI",4,3
21,BI Analyst,70000,"London, UK",Unknown,Mi,Part-time,"Azure,AWS,Power BI",2,0
22,Data Analyst - Remote,50,"Anywhere, New York, NY",Huge,Pr,Full-time,"Power BI , R",4,4
23,Data Analyst,50000,"San Francisco, CA, US",Small,Jr,Full-time,"Python, Power BI, Google Cloud, R,",1,0
24,BI Analyst,120000,"Austin, TX",Huge,None,Contract,None,0,4

### Creating A New Employment Type Column

Create a new int column and mapping employment types to numbers


1.  Full-time = 1
2.  Part-time = 2
3.  Regular = 3
4.  Contract = 4
5.  Temporary = 5
6.  Freelance = 6

In [41]:
bdata['employment_type'].head(25)

0     Part-time
1      Contract
2     Part-time
3     Freelance
4     Freelance
5     Part-time
6      Contract
7       Regular
8       Regular
9     Freelance
10    Freelance
11    Part-time
12    Part-time
13    Full-time
14    Part-time
15    Temporary
16    Full-time
17    Freelance
18     Contract
19    Full-time
20    Full-time
21    Part-time
22    Full-time
23    Full-time
24     Contract
Name: employment_type, dtype: object

In [43]:
# Create a new column called 'employment_type_value' based on `employment_type'

# Map new values
mapping = {'Full-time': 1, 'Part-time': 2, 'Regular': 3, 'Contract': 4, 'Temporary': 5, 'Freelance': 6}


# Create a new column in bdata and map values to 'expereince_level_values`
bdata['employment_type_value'] = bdata['employment_type'].map(mapping).fillna(0).astype(int)

In [44]:
bdata.head(25)

,job_title,salary,location,company_size,experience_level,employment_type,skills,experience_level_value,company_size_value,employment_type_value
0,Product Data Analyst,120000,"Austin, TX, Huntsville,AL, US",Startup,Sr,Part-time,"Google Cloud,Excel,AWS,",3,1,2
1,DATA ANALYST,65000,"Huntsville,AL, New York, NY, Dallas, TX",Large,Sr,Contract,"Python,Excel,Google Cloud,SQL",3,3,4
2,Data Analyst,65000,"Anywhere, Huntsville,AL, New York, NY",Unknown,Jr,Part-time,"R,Tableau,AWS,Excel,",1,0,2
3,Marketing Data Analyst,0,"Houston,TX",Large,Jr,Freelance,"Google Cloud,Azure",1,3,6
4,Data Analyst II,65000,"Remote, New York, NY",Small,Jr,Freelance,"Power BI, Azure, Excel, Google Cloud",1,0,6
5,Senior Data Analyst,0,"Houston,TX, Huntsville,AL, Remote",Startup,Jr,Part-time,"Azure,R,Power BI",1,1,2
6,Senior Data Analyst,95000,"Dallas, TX, New York, NY, London, UK",Medium,Sr,Contract,"SQL,AWS,Excel",3,2,4
7,Sr. Data Analyst,65000,"New York, NY",Huge,Jr,Regular,"R, Excel, Tableau, AWS, SQL",1,4,3
8,Marketing Data Analyst,120000,"San Francisco, CA",Large,Mi,Regular,"Power BI , Azure , Google Cloud , R ,",2,3,3
9,DATA ANALYST,95000.0,"Austin, TX, London, UK",Huge,Mi,Freelance,"AWS , Tableau , Azure , R , Excel",2,4,6
10,Product Data Analyst,110000,"Austin, TX, Huntsville,AL, Remote",Small,Mi,Freelance,"Excel, SQL, Tableau, AWS, Power BI",2,0,6
11,Marketing Data Analyst,0,"New York, NY, San Francisco, CA, Houston,TX",Large,None,Part-time,"Google Cloud, R",0,3,2
12,BI Analyst,70000,"US, Houston,TX, London, UK",Startup,Sr,Part-time,",AWS",3,1,2
13,DATA ANALYST,0,"US, Remote",Unknown,Jr,Full-time,"SQL,AWS,Tableau",1,0,1
14,Data Analyst - Remote,110000,"Remote, Anywhere, Austin, TX",Small,Jr,Part-time,"Power BI,Tableau,R",1,0,2
15,Junior Data Analyst,0,"New York, NY, US, Dallas, TX",Medium,Sr,Temporary,None,3,2,5
16,Data Analyst,50,"Houston,TX, San Francisco, CA",Large,Pr,Full-time,"Azure , Python",4,3,1
17,Data Analyst,110000,"San Francisco, CA, Houston,TX, US",Huge,Pr,Freelance,"Azure, Python, AWS, Excel",4,4,6
18,DATA ANALYST,0,"San Francisco, CA, Houston,TX",Huge,Pr,Contract,"Power BI, , AWS, SQL",4,4,4
19,Senior Data Analyst,0,"Houston,TX, US",Huge,Jr,Full-time,"Python , Google Cloud , Tableau , Azure",1,4,1
20,Senior Data Analyst,70000,"Anywhere, Austin, TX, Huntsville,AL",Large,Pr,Full-time,"Tableau , Python , Excel , Power BI",4,3,1
21,BI Analyst,70000,"London, UK",Unknown,Mi,Part-time,"Azure,AWS,Power BI",2,0,2
22,Data Analyst - Remote,50,"Anywhere, New York, NY",Huge,Pr,Full-time,"Power BI , R",4,4,1
23,Data Analyst,50000,"San Francisco, CA, US",Small,Jr,Full-time,"Python, Power BI, Google Cloud, R,",1,0,1
24,BI Analyst,120000,"Austin, TX",Huge,None,Contract,None,0,4,4