## Task 1: Define the Problem

Everything from a junior data analyst to a Sr.Data Analyst, what is the optimized salary for entry-level data Analyst.

https://geosalary.com

Using the Generated messay dataset,

1.   Clean the data
2.   Exploratory Data Analysis
3.   Use train test model to predict data analysis salaries

## Task 2: Install The Needed Libraries

In [ ]:
import pandas as pd
import numpy as np
import random
import re
import statistics

# Machine Learning
from sklearn.model_selection import train_test_split

# Data Visualization
import seaborn as sns
import matplotlib.pyplot as plt
import plotly as pl

In [ ]:
# Ridge on log salary with target encoding and company size
# from sklearn.linear_model import RidgeCV
# from sklearn.model_selection import cross_val_score, KFold

# features = ['loc_te','company_size']  # add other engineered features
# X = df[features].fillna(0)
# y = df['log_salary']

# model = RidgeCV(alphas=[0.1,1,10,100], cv=5)
# model.fit(X, y)
# df['pred_ln'] = model.predict(X)
# df['pred_salary'] = np.exp(df['pred_ln'])

In [ ]:
# allows me to view the whole list of columns
# Set option to display all rows (if your output from isna().sum() is very long)
pd.set_option('display.max_rows', None)

# Setting df head to all show all columns
pd.set_option('display.max_columns', None)

## Task 3: Load the Data

In [ ]:
# read the csv file
mdata = pd.read_csv('messy_data_analyst_jobs.csv')

In [ ]:
# creating a backup of the csv file from messy_data_analyst_jobs
bdata = pd.read_csv('messy_data_analyst_jobs.csv')

In [ ]:
# Display all columns in the dataset
mdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_title         2499 non-null   object
 1   salary            2353 non-null   object
 2   location          2500 non-null   object
 3   remote_location   2500 non-null   object
 4   compnay_size      2499 non-null   object
 5   expereince_level  2500 non-null   object
 6   employment_type   2500 non-null   object
 7   skills            2387 non-null   object
dtypes: object(8)
memory usage: 156.4+ KB

In [ ]:
bdata.describe()

,job_title,salary,location,remote_location,compnay_size,expereince_level,employment_type,skills
count,2499,2353,2500,2500,2499,2500,2500,2387
unique,35,33,22,27,23,31,25,2028
top,Product Data Analyst,"140,000.00","['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Unknown,5+ years,Temporary,"['Google Cloud', 'AWS']"
freq,218,171,2476,296,330,231,293,8

In [ ]:
bdata['salary'].describe()

count           2353
unique            33
top       140,000.00
freq             171
Name: salary, dtype: object

In [ ]:
# get first view of the dataset
mdata.head(5)

,job_title,salary,location,remote_location,compnay_size,expereince_level,employment_type,skills
0,Sr.,"['New York, NY', 'San Francisco, CA', 'Dallas,...",120k,C2C,Large,Excel;R,Product Data Analyst,False
1,DATA ANALYST,65000Competitive,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,10000+,Sr.,Freelance,"['AWS', 'Python', 'Google Cloud', 'Power BI']"
2,Data Analyst,65000Competitive,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Large,Principal,Contract,"['Python', '', 'Excel']"
3,Marketing Data Analyst,NaN,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,EN,W2,Tableau | Azure | R | Python |
4,Data Analyst II,"€65,000","['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Entry-level,PT,Python and Tableau and Azure and Google Cloud ...

In [ ]:
mdata.tail(5)

,job_title,salary,location,remote_location,compnay_size,expereince_level,employment_type,skills
2495,Sr. Data Analyst,65000Competitive,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,500,5+ years,FT,"['SQL', 'Tableau', 'Excel']"
2496,Data Analytics Specialist,"%50,000","['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,1-10,Jr,Part-time,AWS | SQL | R | Python
2497,BI Analyst,$50/hr,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,501-1000,Junior,Temporary,"R,Excel"
2498,Junior Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Jr,Temporary,"['', 'AWS', 'Azure']"
2499,BI Analyst,"$90,000","['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,EN,Temporary,"['Tableau', 'R', 'AWS']"

In [ ]:
# View only the location column
mdata.loc[:,'location'].head(20)

0                                                  120k
1     ['New York, NY', 'San Francisco, CA', 'Dallas,...
2     ['New York, NY', 'San Francisco, CA', 'Dallas,...
3     ['New York, NY', 'San Francisco, CA', 'Dallas,...
4     ['New York, NY', 'San Francisco, CA', 'Dallas,...
5     ['New York, NY', 'San Francisco, CA', 'Dallas,...
6     ['New York, NY', 'San Francisco, CA', 'Dallas,...
7     ['New York, NY', 'San Francisco, CA', 'Dallas,...
8     ['New York, NY', 'San Francisco, CA', 'Dallas,...
9     ['New York, NY', 'San Francisco, CA', 'Dallas,...
10    ['New York, NY', 'San Francisco, CA', 'Dallas,...
11    ['New York, NY', 'San Francisco, CA', 'Dallas,...
12    ['New York, NY', 'San Francisco, CA', 'Dallas,...
13    ['New York, NY', 'San Francisco, CA', 'Dallas,...
14    ['New York, NY', 'San Francisco, CA', 'Dallas,...
15    ['New York, NY', 'San Francisco, CA', 'Dallas,...
16    ['New York, NY', 'San Francisco, CA', 'Dallas,...
17    ['New York, NY', 'San Francisco, CA', 'Dallas,...
18    ['New York, NY', 'San Francisco, CA', 'Dallas,...
19    ['New York, NY', 'San Francisco, CA', 'Dallas,...
Name: location, dtype: object

In [ ]:
# viewing multiple columns
mdata[["salary", "job_title", "location"]].head(15)

,salary,job_title,location
0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Sr.,120k
1,65000Competitive,DATA ANALYST,"['New York, NY', 'San Francisco, CA', 'Dallas,..."
2,65000Competitive,Data Analyst,"['New York, NY', 'San Francisco, CA', 'Dallas,..."
3,NaN,Marketing Data Analyst,"['New York, NY', 'San Francisco, CA', 'Dallas,..."
4,"€65,000",Data Analyst II,"['New York, NY', 'San Francisco, CA', 'Dallas,..."
5,DOE,Senior Data Analyst,"['New York, NY', 'San Francisco, CA', 'Dallas,..."
6,95000,Senior Data Analyst,"['New York, NY', 'San Francisco, CA', 'Dallas,..."
7,"€65,000",Sr. Data Analyst,"['New York, NY', 'San Francisco, CA', 'Dallas,..."
8,120k,Marketing Data Analyst,"['New York, NY', 'San Francisco, CA', 'Dallas,..."
9,85k - 105k,DATA ANALYST,"['New York, NY', 'San Francisco, CA', 'Dallas,..."
10,110000,Product Data Analyst,"['New York, NY', 'San Francisco, CA', 'Dallas,..."
11,NaN,Marketing Data Analyst,"['New York, NY', 'San Francisco, CA', 'Dallas,..."
12,70000 USD,BI Analyst,"['New York, NY', 'San Francisco, CA', 'Dallas,..."
13,NaN,DATA ANALYST,"['New York, NY', 'San Francisco, CA', 'Dallas,..."
14,110000,Data Analyst - Remote,"['New York, NY', 'San Francisco, CA', 'Dallas,..."

In [ ]:
# Look through all skills
mdata['skills'].head(15)

0                                                 False
1         ['AWS', 'Python', 'Google Cloud', 'Power BI']
2                               ['Python', '', 'Excel']
3                       Tableau | Azure | R | Python |
4     Python and Tableau and Azure and Google Cloud ...
5                                        ['Excel', 'R']
6                                     ['Python', 'AWS']
7          ['Tableau', 'Power BI', 'Python', '', 'AWS']
8               Google Cloud, Azure, Excel, Python, SQL
9                    ['', 'Azure', 'Excel', 'SQL', 'R']
10    Excel and Azure and R and Google Cloud and Tab...
11                          Tableau,Azure,,SQL,Power BI
12    ['SQL', 'R', 'Tableau', 'Power BI', 'Google Cl...
13    ['AWS', 'Python', 'Google Cloud', 'Tableau', 'R']
14                            ['AWS', 'Azure', 'Excel']
Name: skills, dtype: object

## Data Cleaning

#### Clean the Skills Column

starting with the skills column
pretending that I don't know all values in the skills column
1. I need to find all values in the skills columns, then put them into a list
2. Start cleaning the the skills column,
   - start removing the special character such as `[` and `]`
   - remove all `NaN` and `Na` values and replace them with `None`

In [ ]:
# Before Cleaning the Skills Column
bdata['skills'].head(10)

0                                                False
1        ['AWS', 'Python', 'Google Cloud', 'Power BI']
2                              ['Python', '', 'Excel']
3                      Tableau | Azure | R | Python |
4    Python and Tableau and Azure and Google Cloud ...
5                                       ['Excel', 'R']
6                                    ['Python', 'AWS']
7         ['Tableau', 'Power BI', 'Python', '', 'AWS']
8              Google Cloud, Azure, Excel, Python, SQL
9                   ['', 'Azure', 'Excel', 'SQL', 'R']
Name: skills, dtype: object

In [ ]:
# Initial skills list
skills_list = ['R', 'AWS', 'Azure', 'SQL', 'Python', 'Excel', 'BI',
               'Google Cloud', 'Tableau']

# Use a set for fast duplicate checking
skills_set = set(skills_list)

# Iterate through the column and add new skills
for value in mdata['skills']:
    if pd.isna(value):           # Skip empty/NaN values
        continue
    if value in skills_list:
        skills_list.set.discard("[ ","]")
        continue
    # Only add if it doesn't exist
        skills_set.add(value)
        skills_list.append(value)   # Keep the ordered list if you want

print(skills_list)
print(f"\nTotal unique skills: {len(skills_list)}")  # We now have all the skills that in skills columns

['R', 'AWS', 'Azure', 'SQL', 'Python', 'Excel', 'BI', 'Google Cloud', 'Tableau']

Total unique skills: 9

In [ ]:
# Create a function to filiter out the special character
def clean_skills(text):
  if pd.isna(text):
    return None     # returns a None value
  text = str(text)
  text = text.replace('[', '').replace(']', '').strip()   # remove '[' and ']' removes white space
  text = text.replace("'", "").replace('"', '')            # remove ' ' and " " removes white space
  text = text.replace('|', ',').strip()                    # remove '|' and replace with  ,
  text = text.replace('//', ',')                           # remove '/' and replace with  ,
  text = text.replace('/', ',')                            # remove '/' and replace with  ,
  text = text.replace('and', ',').strip()                  # remove 'and' removes white space
  text = text.replace(',,', ',')                           # remove any extra ',,' and replace with ','
  text = text.replace(';;', ',')                           # remove any extra ',,' and replace with ','
  text = text.replace(';', ',')                            # remove any extra ',,' and replace with ','
  return text

# Apply the function to the column
# mdata['skills'] = mdata['skills'].apply(clean_skills)
bdata['skills'] = bdata['skills'].apply(clean_skills)

In [ ]:
# show the cleaned column in mdata
print(mdata['skills'])

0                                                   False
1           ['AWS', 'Python', 'Google Cloud', 'Power BI']
2                                 ['Python', '', 'Excel']
3                         Tableau | Azure | R | Python |
4       Python and Tableau and Azure and Google Cloud ...
5                                          ['Excel', 'R']
6                                       ['Python', 'AWS']
7            ['Tableau', 'Power BI', 'Python', '', 'AWS']
8                 Google Cloud, Azure, Excel, Python, SQL
9                      ['', 'Azure', 'Excel', 'SQL', 'R']
10      Excel and Azure and R and Google Cloud and Tab...
11                            Tableau,Azure,,SQL,Power BI
12      ['SQL', 'R', 'Tableau', 'Power BI', 'Google Cl...
13      ['AWS', 'Python', 'Google Cloud', 'Tableau', 'R']
14                              ['AWS', 'Azure', 'Excel']
15                                                    NaN
16                                                 Excel,
17                                         Python, AWS, R
18             ['Python', 'Power BI', 'AWS', 'Azure', '']
19                               ['Python', 'Excel', 'R']
20                                          ['Azure', '']
21                              Azure, SQL, Excel, Python
22                                     Azure/AWS/Power BI
23                           ['', 'R', 'Python', 'Azure']
24                    SQL,Google Cloud,Python,Excel,Azure
25      ['Google Cloud', 'Tableau', 'Excel', 'SQL', 'P...
26                                          Google Cloud/
27                               and AWS and Google Cloud
28                                    R | Azure | Tableau
29                                                    NaN
30                                        Azure,SQL,AWS,R
31                                        SQL;Power BI;;R
32                  ['Google Cloud', 'SQL', 'Azure', 'R']
33                                  ['R', '', 'Power BI']
34              ['', 'AWS', 'Tableau', 'Python', 'Excel']
35                                     Azure,Power BI,AWS
36                                           ['R', 'AWS']
37                ['Excel', 'Azure', 'R', 'Google Cloud']
38             ['Excel', '', 'AWS', 'Power BI', 'Python']
39                  ['Python', 'Tableau', '', 'Power BI']
40       ['Azure', 'Power BI', 'AWS', 'Google Cloud', '']
41                           Power BI;;Tableau;SQL;Python
42                             ['Python', 'Google Cloud']
43                                                    NaN
44                     ['', 'Tableau', 'Power BI', 'AWS']
45        ['Power BI', 'Python', 'R', 'Excel', 'Tableau']
46                                          Tableau;Excel
47             Google Cloud | Azure | Python |  | Tableau
48                                                    NaN
49                 ['Excel', 'Python', 'Power BI', 'AWS']
50            ['AWS', 'Azure', 'Python', 'R', 'Power BI']
51                    ['Google Cloud', 'SQL', 'Power BI']
52                           AWS/Excel/Azure/Google Cloud
53                    ['AWS', 'SQL', 'R', '', 'Power BI']
54         ['Power BI', '', 'Excel', 'Python', 'Tableau']
55                                      Azure;R;AWS;Excel
56                              Excel/Azure//Google Cloud
57                  ['R', 'SQL', 'Excel', 'AWS', 'Azure']
58                           Tableau,,Python,Google Cloud
59                                              ['R', '']
60                        SQL | Azure | Tableau | R | AWS
61                                              Power BI;
62       ['AWS', 'Google Cloud', 'Excel', 'Tableau', 'R']
63               ['Power BI', 'AWS', 'Excel', 'R', 'SQL']
64                                   R, Power BI, Tableau
65                                     Azure,Python,Excel
66                          ['SQL', 'Power BI', 'Python']
67                                                    NaN
68                    ['AWS', 'Power BI', 'Google Cloud']
69                       ['SQL', 'Azure', 'Excel', 'AWS']
70                   ['Excel', '', 'R', 'Tableau', 'AWS']
71                          Google Cloud/Excel/AWS/Python
72                                   Azure | Google Cloud
73                                                AWS/SQL
74                              ['Google Cloud', 'Excel']
75         ['Tableau', 'Excel', 'SQL', 'Azure', 'Python']
76                             ['AWS', 'Excel', 'Python']
77                                       Power BI/Tableau
78                                             R//Tableau
79                   ['Azure', 'Power BI', '', 'Tableau']
80                     Tableau, Excel, AWS, Azure, Python
81                        | Google Cloud | Python | Azure
82               ['SQL', 'Excel', 'Azure', 'Tableau', '']
83      Azure and Google Cloud and Python and  and Tab...
84                                     Excel and  and SQL
85                              AWS, SQL, Tableau, Python
86                            ,Google Cloud,Azure,Excel,R
87                       Azure and R and Excel and Python
88                                            Tableau;SQL
89                                  Python;R;;Tableau;SQL
90                                            ,Python,SQL
91                 ['SQL', 'Python', 'Power BI', 'Azure']
92                                 ['SQL', 'Tableau', '']
93                                   /Google Cloud/Python
94                                          ['Excel', '']
95                            AWS/Google Cloud/Excel/SQL/
96                                      ['Python', 'AWS']
97                                      ['Python', 'SQL']
98               ['Tableau', '', 'Azure', 'SQL', 'Excel']
99                                    Azure | SQL | Excel
100                   ['Azure', 'Python', 'Excel', 'AWS']
101                                         Azure and AWS
102                                             ['', 'R']
103                                         SQL;Tableau;R
104                                       SQL and Tableau
105                           ['', 'Google Cloud', 'SQL']
106                                  Power BI;Tableau;AWS
107                        Power BI;Excel;Tableau;AWS;SQL
108                      ['SQL', 'Excel', 'Google Cloud']
109                       ['Google Cloud', 'Tableau', '']
110                            ['Google Cloud', 'Python']
111                  Tableau/Excel/Azure/AWS/Google Cloud
112                      R and Power BI and Excel and AWS
113                                                   NaN
114                          SQL, Tableau, , Google Cloud
115         ['Google Cloud', '', 'R', 'Tableau', 'Excel']
116                           R,Power BI,AWS,Google Cloud
117                                 ['Excel', 'Power BI']
118                                   ['Python', 'Azure']
119                                                   NaN
120                             Azure;Tableau;Python;;AWS
121                               ['AWS', 'Azure', 'SQL']
122                 Google Cloud, Python, Excel, Power BI
123            ['SQL', 'Google Cloud', 'Python', 'Azure']
124                    ['SQL', 'Google Cloud', 'Tableau']
125                                                   NaN
126                     Azure,Power BI,Google Cloud,Excel
127                                    ['SQL', '', 'AWS']
128          ['Google Cloud', 'AWS', 'Azure', 'Power BI']
129                                         R and Tableau
130     ['Excel', 'Google Cloud', 'Power BI', 'AWS', '...
131                                   ,Python,Tableau,AWS
132                                   ['SQL', 'Power BI']
133                          ['', 'SQL', 'Python', 'AWS']
134     ['Python', 'Power BI', 'SQL', 'Google Cloud', ...
135                                      ['', 'Power BI']
136                                        ['R', 'Excel']
137                                          and Power BI
138          ['', 'Azure', 'Google Cloud', 'R', 'Python']
139     ['Python', 'AWS', 'Azure', 'Power BI', 'Google...
140     ['Python', 'Excel', 'Tableau', 'Google Cloud',...
141                             ['Tableau', 'Excel', 'R']
142                 ['', 'Python', 'Google Cloud', 'AWS']
143                           ['Excel', 'AWS', '', 'SQL']
144                                         Python, , AWS
145                                       Power BI/Python
146                                  R,Azure,Google Cloud
147                 SQL, Azure, Power BI, R, Google Cloud
148                    Power BI |  | Excel | Python | SQL
149                                    | Google Cloud | R
150                                   ['SQL', 'Power BI']
151     ['Python', 'Excel', 'Tableau', 'Google Cloud',...
152                                         Excel | Azure
153                                         | AWS | Excel
154                             SQL,Power BI,,Azure,Excel
155                                           ['', 'AWS']
156                                                   NaN
157                   Excel and Google Cloud and Power BI
158                                              R, AWS,
159      Excel and Power BI and SQL and Azure and Tableau
160             ['AWS', 'Azure', 'Tableau', 'R', 'Excel']
161                         Excel,Python,Google Cloud,SQL
162                             ['Excel', 'R', 'Tableau']
163                                     SQL;Azure;Tableau
164                                              ,SQL,AWS
165                   ['Azure', 'Google Cloud', 'Python']
166                                       Power BI,Python
167                             ['R', 'Excel', 'Tableau']
168                                 AWS, SQL, R, Python,
169                                          ['AWS', 'R']
170                  Power BI, Google Cloud, Excel, Azure
171                               ['Tableau', 'Power BI']
172       ['Python', 'Google Cloud', 'Azure', 'R', 'SQL']
173                                         ['Azure', '']
174                            ['Python', 'Power BI', '']
175                                      ['Tableau', 'R']
176                                 Power BI/Azure/AWS//R
177             | Azure | Google Cloud | Excel | Power BI
178                                             ['R', '']
179                                        ['Python', '']
180                                    SQL,Google Cloud,R
181                                       ['R', 'Python']
182                                         Tableau/Azure
183                                 Tableau/AWS/Excel/SQL
184                               ['AWS', 'Google Cloud']
185              ['Excel', 'Power BI', 'Azure', 'Python']
186     ['Power BI', 'Azure', 'AWS', 'Tableau', 'Googl...
187                             Excel | SQL | Power BI |
188                          R;Azure;SQL;Power BI;Tableau
189                               ['Azure', 'SQL', 'AWS']
190                         ['AWS', '', 'Excel', 'Azure']
191                                      SQL;Python;AWS;R
192                                               SQL,AWS
193                       Power BI | Excel | Google Cloud
194     ['Power BI', 'AWS', 'Excel', 'Azure', 'Google ...
195                                                   NaN
196                                         Python//R/AWS
197                       SQL//Azure/Google Cloud/Tableau
198                           Azure,Excel,Tableau,AWS,SQL
199                     Google Cloud,SQL,Power BI,Tableau
200            ['Excel', 'AWS', 'Python', 'Google Cloud']
201                        Azure and Power BI and Tableau
202                                      ['AWS', 'R', '']
203                            ['R', 'Power BI', 'Excel']
204                                      Azure;R;Power BI
205                                        SQL;;AWS;Excel
206               ['R', 'Excel', 'Tableau', 'AWS', 'SQL']
207        Power BI and Azure and Google Cloud and R and
208                                     $60,000 - $80,000
209        ['Excel', 'SQL', 'Tableau', 'AWS', 'Power BI']
210                                 ['Google Cloud', 'R']
211                                                  ,AWS
212                                       SQL;AWS;Tableau
213                                    Power BI,Tableau,R
214                                                   NaN
215                                      Azure and Python
216                   ['Azure', 'Python', 'AWS', 'Excel']
217                        ['Power BI', '', 'AWS', 'SQL']
218         Python and Google Cloud and Tableau and Azure
219                   Tableau | Python | Excel | Power BI
220                                   Azure/AWS//Power BI
221                                          Power BI | R
222       ['Python', 'Power BI', 'Google Cloud', 'R', '']
223                                                   NaN
224                            Power BI/Excel//Python/AWS
225                                        Azure/Tableau/
226                             ['Azure', 'Google Cloud']
227                               Excel and Azure and SQL
228                            ['Excel', 'Python', 'SQL']
229                                        SQL and Python
230                           Python/SQL/Azure/Power BI/R
231     ['AWS', 'Python', 'SQL', 'Power BI', 'Google C...
232                                   ['Power BI', 'SQL']
233                   ['Tableau', 'Python', 'SQL', 'AWS']
234                                Tableau | R | Power BI
235                                                  SQL,
236                                  AWS;Excel;SQL;Azure;
237       ['Python', 'R', 'SQL', 'Azure', 'Google Cloud']
238              ['AWS', 'Power BI', 'Python', 'SQL', '']
239                                 ['Python', 'Tableau']
240                ['Python', 'AWS', 'Power BI', 'Azure']
241                                        ['R', 'Azure']
242                  Azure and Excel and AWS and Power BI
243                        ['AWS', 'Google Cloud', 'SQL']
244                                Google Cloud and Azure
245                                                 R;SQL
246                       Google Cloud, Python, , Tableau
247                                        Python | Excel
248         ['Google Cloud', 'Azure', 'Excel', 'Tableau']
249                                                    ,R
250                             ['R', 'Azure', '', 'SQL']
251                             ['Excel', 'Google Cloud']
252                                      Python and Azure
253                         ['Power BI', 'Python', 'AWS']
254                                       /Google Cloud/R
255                     ['R', 'Power BI', 'Excel', 'SQL']
256       ['SQL', 'R', 'AWS', 'Google Cloud', 'Power BI']
257                            R and Google Cloud and SQL
258                                            Python,AWS
259     ['Power BI', 'SQL', 'Google Cloud', 'Python', ...
260                                 Azure and Excel and R
261                                   Python/Google Cloud
262                 ['Excel', 'Power BI', 'Google Cloud']
263                                      ['AWS', 'Azure']
264                        ['Azure', 'SQL', 'Python', '']
265                                                   NaN
266                           Python, , R, Azure, Tableau
267                                                   NaN
268                ['SQL', 'Excel', 'Tableau', '', 'AWS']
269                   SQL and  and Google Cloud and Excel
270                  ['Azure', 'R', 'Power BI', 'Python']
271       ['AWS', 'Azure', 'Tableau', '', 'Google Cloud']
272                                Python/AWS//Power BI/R
273                                 Power BI,Azure,Python
274                                   ['SQL', 'Power BI']
275                           Tableau,Excel,Python,,Azure
276      ['Google Cloud', 'Power BI', 'Tableau', 'Excel']
277                          ['Azure', 'AWS', 'SQL', 'R']
278                           ['Power BI', '', 'Tableau']
279                                         AWS,Power BI,
280                                         Google Cloud;
281                    ['', 'R', 'Azure', 'SQL', 'Excel']
282                                                  /SQL
283                ['Python', 'SQL', 'Google Cloud', 'R']
284                                                   NaN
285                                       Tableau, Python
286     Python and SQL and Excel and Google Cloud and AWS
287                                         ['Excel', '']
288                           Tableau, R, Power BI, Azure
289                                              Excel |
290                                  SQL |  | Excel | AWS
291                                       ['Python', 'R']
292                       R and Power BI and Google Cloud
293     ['Power BI', 'SQL', 'Google Cloud', 'Azure', '...
294                                             ['R', '']
295                                           ['SQL', '']
296                          Power BI and SQL and Tableau
297                       ['R', 'Excel', 'SQL', 'Python']
298                                    Python//Power BI/R
299                                        ,Excel,R,Azure
300                      ['Excel', 'SQL', 'R', 'Tableau']
301                    | SQL | Azure | Tableau | Power BI
302                                        Python | Azure
303                           ['Tableau', 'Google Cloud']
304                                Tableau/Power BI/Azure
305                                    ['SQL', '', 'AWS']
306                                      ['R', '', 'SQL']
307                                   Python,Google Cloud
308                          ['AWS', 'Excel', 'Power BI']
309                                                Excel,
310                                        Python and SQL
311                                  SQL/R/Tableau//Azure
312                  ['Tableau', 'SQL', 'Excel', 'Azure']
313                               ['', 'SQL', 'Power BI']
314     ['R', 'Azure', 'Google Cloud', 'Excel', 'Power...
315         ['Power BI', 'Excel', 'AWS', 'SQL', 'Python']
316                      ['SQL', 'Excel', 'Google Cloud']
317                      ['Google Cloud', '', 'SQL', 'R']
318                                       ['Python', 'R']
319                                       Excel | Tableau
320                                             Python/R/
321                                       ['R', 'Python']
322        ['Tableau', 'Azure', 'R', 'Excel', 'Power BI']
323                 and Google Cloud and Azure and Python
324                                          ['SQL', 'R']
325                                      Python/Azure/AWS
326                         Excel, Azure, Power BI, , AWS
327                         ['Excel', 'Google Cloud', '']
328                Azure and Excel and Tableau and Python
329                                           Power BI |
330                                     Azure | Python |
331                                  ['SQL', 'Excel', '']
332                                        Power BI,Excel
333        ['Google Cloud', 'R', 'Excel', 'Azure', 'SQL']
334                                      Azure;Python;AWS
335             ['Tableau', 'SQL', 'Azure', 'Excel', 'R']
336                       Google Cloud/R/AWS/Power BI/SQL
337                                      ['SQL', 'Excel']
338                               Google Cloud | Power BI
339                                                   NaN
340                                   Python,SQL,Power BI
341                                     Python,AWS,Azure,
342                             Python, AWS, Google Cloud
343                  ['AWS', '', 'Google Cloud', 'Azure']

In [ ]:
# After cleaning the Skills Column
bdata['skills'].head(15)

0                                             False
1               AWS, Python, Google Cloud, Power BI
2                                   Python, , Excel
3                    Tableau , Azure , R , Python ,
4     Python , Tableau , Azure , Google Cloud , SQL
5                                          Excel, R
6                                       Python, AWS
7                  Tableau, Power BI, Python, , AWS
8           Google Cloud, Azure, Excel, Python, SQL
9                            , Azure, Excel, SQL, R
10       Excel , Azure , R , Google Cloud , Tableau
11                       Tableau,Azure,SQL,Power BI
12          SQL, R, Tableau, Power BI, Google Cloud
13            AWS, Python, Google Cloud, Tableau, R
14                                AWS, Azure, Excel
Name: skills, dtype: object

#### Clean the Location Column

after configuring the data to only show between 1 to 3 location. It needs to be clean

In [ ]:
mdata['location'].head(15)

0                                                  120k
1     ['New York, NY', 'San Francisco, CA', 'Dallas,...
2     ['New York, NY', 'San Francisco, CA', 'Dallas,...
3     ['New York, NY', 'San Francisco, CA', 'Dallas,...
4     ['New York, NY', 'San Francisco, CA', 'Dallas,...
5     ['New York, NY', 'San Francisco, CA', 'Dallas,...
6     ['New York, NY', 'San Francisco, CA', 'Dallas,...
7     ['New York, NY', 'San Francisco, CA', 'Dallas,...
8     ['New York, NY', 'San Francisco, CA', 'Dallas,...
9     ['New York, NY', 'San Francisco, CA', 'Dallas,...
10    ['New York, NY', 'San Francisco, CA', 'Dallas,...
11    ['New York, NY', 'San Francisco, CA', 'Dallas,...
12    ['New York, NY', 'San Francisco, CA', 'Dallas,...
13    ['New York, NY', 'San Francisco, CA', 'Dallas,...
14    ['New York, NY', 'San Francisco, CA', 'Dallas,...
Name: location, dtype: object

#### After Cleaning the Skills & Location

In [ ]:
# Current view of the dataset
mdata.head(50)

,job_title,salary,location,remote_location,compnay_size,expereince_level,employment_type,skills
0,Sr.,"['New York, NY', 'San Francisco, CA', 'Dallas,...",120k,C2C,Large,Excel;R,Product Data Analyst,False
1,DATA ANALYST,65000Competitive,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,10000+,Sr.,Freelance,"['AWS', 'Python', 'Google Cloud', 'Power BI']"
2,Data Analyst,65000Competitive,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Large,Principal,Contract,"['Python', '', 'Excel']"
3,Marketing Data Analyst,NaN,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,EN,W2,Tableau | Azure | R | Python |
4,Data Analyst II,"€65,000","['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Entry-level,PT,Python and Tableau and Azure and Google Cloud ...
5,Senior Data Analyst,DOE,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,1-10,MI,Part-time,"['Excel', 'R']"
6,Senior Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Startup,Principal,FT,"['Python', 'AWS']"
7,Sr. Data Analyst,"€65,000","['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Medium,Junior,W2,"['Tableau', 'Power BI', 'Python', '', 'AWS']"
8,Marketing Data Analyst,120k,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,MI,FT,"Google Cloud, Azure, Excel, Python, SQL"
9,DATA ANALYST,85k - 105k,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Unknown,MI,Temporary,"['', 'Azure', 'Excel', 'SQL', 'R']"
10,Product Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,501-1000,SE,W2,Excel and Azure and R and Google Cloud and Tab...
11,Marketing Data Analyst,NaN,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,500,Senior,FT,"Tableau,Azure,,SQL,Power BI"
12,BI Analyst,70000 USD,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,1-10,MI,Contract,"['SQL', 'R', 'Tableau', 'Power BI', 'Google Cl..."
13,DATA ANALYST,NaN,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,501-1000,MI,Contract,"['AWS', 'Python', 'Google Cloud', 'Tableau', 'R']"
14,Data Analyst - Remote,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,0-5 yrs,PT,"['AWS', 'Azure', 'Excel']"
15,Junior Data Analyst,Negotiable,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,501-1000,Sr.,Full-time,NaN
16,Data Analyst,$50/hr,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Medium,Entry-level,Part-time,"Excel,"
17,Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Startup,5+ years,Full-time,"Python, AWS, R"
18,DATA ANALYST,DOE,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,501-1000,MI,PT,"['Python', 'Power BI', 'AWS', 'Azure', '']"
19,Senior Data Analyst,DOE,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Startup,Principal,Freelance,"['Python', 'Excel', 'R']"
20,Senior Data Analyst,70000 USD,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,501-1000,Junior,W2,"['Azure', '']"
21,BI Analyst,70000 USD,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Startup,MI,PT,"Azure, SQL, Excel, Python"
22,Data Analyst - Remote,$50/hr,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,501-1000,EN,Contract,Azure/AWS/Power BI
23,Data Analyst,"%50,000","['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,10000+,Jr,PT,"['', 'R', 'Python', 'Azure']"
24,BI Analyst,120k,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,1-10,EN,C2C,"SQL,Google Cloud,Python,Excel,Azure"
25,Senior Data Analyst,"€65,000","['New York, NY', 'San Francisco, CA', 'Dallas,...",True,1-10,Senior,Freelance,"['Google Cloud', 'Tableau', 'Excel', 'SQL', 'P..."
26,Marketing Data Analyst,85k - 105k,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,5+ years,Full-time,Google Cloud/
27,Product Data Analyst,"%50,000","['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Startup,Entry-level,C2C,and AWS and Google Cloud
28,Marketing Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,1-10,0-5 yrs,PT,R | Azure | Tableau
29,BI Analyst,"$60,000 - $80,000","['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Unknown,MI,C2C,NaN
30,Junior Data Analyst,$50/hr,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,1-10,EN,Contract,"Azure,SQL,AWS,R"
31,Senior Data Analyst,$50/hr,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Medium,Sr.,PT,SQL;Power BI;;R
32,Data Analytics Specialist,NaN,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Medium,SE,Full-time,"['Google Cloud', 'SQL', 'Azure', 'R']"
33,Data Analyst - Remote,85k - 105k,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Startup,SE,FT,"['R', '', 'Power BI']"
34,Data Analyst II,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,501-1000,Principal,PT,"['', 'AWS', 'Tableau', 'Python', 'Excel']"
35,Data Analyst!!!,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Medium,Junior,Full-time,"Azure,Power BI,AWS"
36,Data Analyst,DOE,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,500,Jr,Freelance,"['R', 'AWS']"
37,Data Analyst!!!,"140,000.00","['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Startup,5+ years,Full-time,"['Excel', 'Azure', 'R', 'Google Cloud']"
38,Data Analyst!!!,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Medium,0-5 yrs,Contract,"['Excel', '', 'AWS', 'Power BI', 'Python']"
39,Sr. Data Analyst,80-90k,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,501-1000,Principal,W2,"['Python', 'Tableau', '', 'Power BI']"
40,Marketing Data Analyst,80-90k,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,10000+,Junior,Part-time,"['Azure', 'Power BI', 'AWS', 'Google Cloud', '']"
41,Junior Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,1-10,Jr,Part-time,Power BI;;Tableau;SQL;Python
42,Jr. Data Analyst,85k - 105k,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,1-10,0-5 yrs,Contract,"['Python', 'Google Cloud']"
43,Data Analyst II,Negotiable,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Startup,Principal,Contract,NaN
44,Sr. Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,1-10,5+ years,Part-time,"['', 'Tableau', 'Power BI', 'AWS']"
45,Senior Data Analyst,NaN,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Unknown,Junior,Freelance,"['Power BI', 'Python', 'R', 'Excel', 'Tableau']"
46,Data Analyst!!!,NaN,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,500,0-2 years,Contract,Tableau;Excel
47,Jr. Data Analyst,$50/hr,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,500,Senior,Temporary,Google Cloud | Azure | Python | | Tableau
48,DATA ANALYST,85k - 105k,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,501-1000,Entry-level,Part-time,NaN
49,DATA ANALYST,70000 USD,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,501-1000,Principal,PT,"['Excel', 'Python', 'Power BI', 'AWS']"

#### Clean the Salary Column

In [ ]:
# Current view of the salary column
mdata['salary'].head(225)

0      ['New York, NY', 'San Francisco, CA', 'Dallas,...
1                                       65000Competitive
2                                       65000Competitive
3                                                    NaN
4                                                €65,000
5                                                    DOE
6                                                  95000
7                                                €65,000
8                                                   120k
9                                             85k - 105k
10                                                110000
11                                                   NaN
12                                             70000 USD
13                                                   NaN
14                                                110000
15                                            Negotiable
16                                                $50/hr
17                                                110000
18                                                   DOE
19                                                   DOE
20                                             70000 USD
21                                             70000 USD
22                                                $50/hr
23                                               %50,000
24                                                  120k
25                                               €65,000
26                                            85k - 105k
27                                               %50,000
28                                                 95000
29                                     $60,000 - $80,000
30                                                $50/hr
31                                                $50/hr
32                                                   NaN
33                                            85k - 105k
34                                                110000
35                                                110000
36                                                   DOE
37                                            140,000.00
38                                                 95000
39                                                80-90k
40                                                80-90k
41                                                110000
42                                            85k - 105k
43                                            Negotiable
44                                                110000
45                                                   NaN
46                                                   NaN
47                                                $50/hr
48                                            85k - 105k
49                                             70000 USD
50                                            85k - 105k
51                                                80-90k
52                                               $90,000
53                                                  120k
54                                            85k - 105k
55                                                   DOE
56                                             70000 USD
57                                             70000 USD
58                                            Negotiable
59                                               %50,000
60                                                $50/hr
61                                                   DOE
62                                                110000
63                                      65000Competitive
64                                               €65,000
65                                      65000Competitive
66                                            85k - 105k
67                                                   DOE
68                                                110000
69                                             70000 USD
70                                            85k - 105k
71                                             70000 USD
72                                            Negotiable
73                                               $90,000
74                                     $60,000 - $80,000
75                                                110000
76                                               $90,000
77                                      65000Competitive
78                                               €65,000
79                                                80-90k
80                                     $60,000 - $80,000
81                                                 95000
82                                                   DOE
83                                                   DOE
84                                                 95000
85                                               %50,000
86                                            140,000.00
87                                                   DOE
88                                                   NaN
89                                                110000
90                                               $90,000
91                                             70000 USD
92                                                   NaN
93                                                80-90k
94                                                 95000
95                                                   NaN
96                                               €65,000
97                                            Negotiable
98                                            85k - 105k
99                                            Negotiable
100                                           Negotiable
101                                               $50/hr
102                                           140,000.00
103                                           85k - 105k
104                                               $50/hr
105                                                 120k
106                                           Negotiable
107                                              %50,000
108                                                  NaN
109                                                 120k
110                                     65000Competitive
111                                                  NaN
112                                              %50,000
113                                           85k - 105k
114                                                 120k
115                                              $90,000
116                                                  DOE
117                                           140,000.00
118                                               80-90k
119                                              %50,000
120                                            70000 USD
121                                           Negotiable
122                                           Negotiable
123                                              €65,000
124                                            70000 USD
125                                                95000
126                                                  NaN
127                                                95000
128                                                  DOE
129                                                95000
130                                    $60,000 - $80,000
131                                               110000
132                                           140,000.00
133                                                  NaN
134                                              %50,000
135                                              €65,000
136                                               $50/hr
137                                              $90,000
138                                              $90,000
139                                                  DOE
140                                                95000
141                                                95000
142                                                  DOE
143                                    $60,000 - $80,000
144                                                 120k
145                                               80-90k
146                                           85k - 105k
147                                     65000Competitive
148                                               $50/hr
149                                           140,000.00
150                                               $50/hr
151                                              $90,000
152                                           140,000.00
153                                              $90,000
154                                              €65,000
155                                               $50/hr
156                                                  DOE
157                                               110000
158                                           140,000.00
159                                                  NaN
160                                     65000Competitive
161                                                 120k
162                                           85k - 105k
163                                                 120k
164                                           140,000.00
165                                               $50/hr
166                                           Negotiable
167                                               $50/hr
168                                           85k - 105k
169                                              €65,000
170                                           140,000.00
171                                              $90,000
172                                              $90,000
173                                              $90,000
174                                           85k - 105k
175                                           Negotiable
176                                                95000
177                                                  NaN
178                                           85k - 105k
179                                           85k - 105k
180                                           Negotiable
181                                           Negotiable
182                                            70000 USD
183                                           140,000.00
184                                                  DOE
185                                           Negotiable
186                                                95000
187                                                  DOE
188                                                95000
189                                    $60,000 - $80,000
190                                               $50/hr
191                                           Negotiable
192                                                 120k
193                                               80-90k
194                                                  DOE
195                                    $60,000 - $80,000
196                                                95000
197                                     65000Competitive
198                                              %50,000
199                                              $90,000
200                                                95000
201                                            70000 USD
202                                           140,000.00
203                                           85k - 105k
204                                              %50,000
205                                              $90,000
206                                                 120k
207                                              €65,000
208                                                   SE
209                                                  NaN
210                                           Negotiable
211                                               80-90k
212                                           85k - 105k
213                                               80-90k
214                                              €65,000
215                                               80-90k
216                                                95000
217                                              $90,000
218                                           85k - 105k
219                                              €65,000
220                                           Negotiable
221                                                95000
222                                           140,000.00
223                                           Negotiable
224                                            70000 USD
Name: salary, dtype: object

In [ ]:
bdata['salary'].head(225)

0      ['New York, NY', 'San Francisco, CA', 'Dallas,...
1                                       65000Competitive
2                                       65000Competitive
3                                                    NaN
4                                                €65,000
5                                                    DOE
6                                                  95000
7                                                €65,000
8                                                   120k
9                                             85k - 105k
10                                                110000
11                                                   NaN
12                                             70000 USD
13                                                   NaN
14                                                110000
15                                            Negotiable
16                                                $50/hr
17                                                110000
18                                                   DOE
19                                                   DOE
20                                             70000 USD
21                                             70000 USD
22                                                $50/hr
23                                               %50,000
24                                                  120k
25                                               €65,000
26                                            85k - 105k
27                                               %50,000
28                                                 95000
29                                     $60,000 - $80,000
30                                                $50/hr
31                                                $50/hr
32                                                   NaN
33                                            85k - 105k
34                                                110000
35                                                110000
36                                                   DOE
37                                            140,000.00
38                                                 95000
39                                                80-90k
40                                                80-90k
41                                                110000
42                                            85k - 105k
43                                            Negotiable
44                                                110000
45                                                   NaN
46                                                   NaN
47                                                $50/hr
48                                            85k - 105k
49                                             70000 USD
50                                            85k - 105k
51                                                80-90k
52                                               $90,000
53                                                  120k
54                                            85k - 105k
55                                                   DOE
56                                             70000 USD
57                                             70000 USD
58                                            Negotiable
59                                               %50,000
60                                                $50/hr
61                                                   DOE
62                                                110000
63                                      65000Competitive
64                                               €65,000
65                                      65000Competitive
66                                            85k - 105k
67                                                   DOE
68                                                110000
69                                             70000 USD
70                                            85k - 105k
71                                             70000 USD
72                                            Negotiable
73                                               $90,000
74                                     $60,000 - $80,000
75                                                110000
76                                               $90,000
77                                      65000Competitive
78                                               €65,000
79                                                80-90k
80                                     $60,000 - $80,000
81                                                 95000
82                                                   DOE
83                                                   DOE
84                                                 95000
85                                               %50,000
86                                            140,000.00
87                                                   DOE
88                                                   NaN
89                                                110000
90                                               $90,000
91                                             70000 USD
92                                                   NaN
93                                                80-90k
94                                                 95000
95                                                   NaN
96                                               €65,000
97                                            Negotiable
98                                            85k - 105k
99                                            Negotiable
100                                           Negotiable
101                                               $50/hr
102                                           140,000.00
103                                           85k - 105k
104                                               $50/hr
105                                                 120k
106                                           Negotiable
107                                              %50,000
108                                                  NaN
109                                                 120k
110                                     65000Competitive
111                                                  NaN
112                                              %50,000
113                                           85k - 105k
114                                                 120k
115                                              $90,000
116                                                  DOE
117                                           140,000.00
118                                               80-90k
119                                              %50,000
120                                            70000 USD
121                                           Negotiable
122                                           Negotiable
123                                              €65,000
124                                            70000 USD
125                                                95000
126                                                  NaN
127                                                95000
128                                                  DOE
129                                                95000
130                                    $60,000 - $80,000
131                                               110000
132                                           140,000.00
133                                                  NaN
134                                              %50,000
135                                              €65,000
136                                               $50/hr
137                                              $90,000
138                                              $90,000
139                                                  DOE
140                                                95000
141                                                95000
142                                                  DOE
143                                    $60,000 - $80,000
144                                                 120k
145                                               80-90k
146                                           85k - 105k
147                                     65000Competitive
148                                               $50/hr
149                                           140,000.00
150                                               $50/hr
151                                              $90,000
152                                           140,000.00
153                                              $90,000
154                                              €65,000
155                                               $50/hr
156                                                  DOE
157                                               110000
158                                           140,000.00
159                                                  NaN
160                                     65000Competitive
161                                                 120k
162                                           85k - 105k
163                                                 120k
164                                           140,000.00
165                                               $50/hr
166                                           Negotiable
167                                               $50/hr
168                                           85k - 105k
169                                              €65,000
170                                           140,000.00
171                                              $90,000
172                                              $90,000
173                                              $90,000
174                                           85k - 105k
175                                           Negotiable
176                                                95000
177                                                  NaN
178                                           85k - 105k
179                                           85k - 105k
180                                           Negotiable
181                                           Negotiable
182                                            70000 USD
183                                           140,000.00
184                                                  DOE
185                                           Negotiable
186                                                95000
187                                                  DOE
188                                                95000
189                                    $60,000 - $80,000
190                                               $50/hr
191                                           Negotiable
192                                                 120k
193                                               80-90k
194                                                  DOE
195                                    $60,000 - $80,000
196                                                95000
197                                     65000Competitive
198                                              %50,000
199                                              $90,000
200                                                95000
201                                            70000 USD
202                                           140,000.00
203                                           85k - 105k
204                                              %50,000
205                                              $90,000
206                                                 120k
207                                              €65,000
208                                                   SE
209                                                  NaN
210                                           Negotiable
211                                               80-90k
212                                           85k - 105k
213                                               80-90k
214                                              €65,000
215                                               80-90k
216                                                95000
217                                              $90,000
218                                           85k - 105k
219                                              €65,000
220                                           Negotiable
221                                                95000
222                                           140,000.00
223                                           Negotiable
224                                            70000 USD
Name: salary, dtype: object

In [ ]:
"""
Cleans the Salary column by remove an special characte

"""
def clean_salary(text):
    if pd.isna(text):
        return 0

    text = str(text).strip()

    # Special cases for Words
    if any(x in text.upper() for x in ['DOE', 'Negotiable', 'Competitive']):
        return 0

    # Remove special characters from the salary column
    replacements = [
        ('NaN', '0'),
        ('65000Competitive', '65000'),  # Remove '65000Competitive' and replace with '65000'
        ('€', ''),
        ('$', ''),  # Removes the '$' from the column and delete extra space
        ('%', ''),    # and so...
        ('120K', '120000'),
        ('120k', '120000'),
        ('70000 USD', '70000'),
        ('$50/hr', '104000'),     # 50 * 2080
        (',', ''),
        ('K', '000'),
        ('k', '000'),
    ]
    for old, new in replacements:
        text = text.replace(old, new)

    # Keep only digits
    text = ''.join(filter(str.isdigit, text))

    try:
        return int(text) if text else 0
    except:
        return 0

# Apply the function to the column
bdata['salary'] = mdata['salary'].apply(clean_salary)

In [ ]:
# Special Case : for two number stuck together
double_values = ['85000105000', '6000080000']

# Create a function that targets column
def concatenated_salary(salary):
    salary_str = str(salary).strip()

    if salary_str == '85000105000':
        num1 = 85000
        num2 = 105000
        val = statistics.median([num1, num2])
        return val

    elif salary_str == '6000080000':
        num1 = 60000
        num2 = 80000
        val = statistics.median([num1, num2])
        return val
    else:
        return salary_str

# Apply the fix
bdata['salary'] = bdata['salary'].apply(concatenated_salary)

In [ ]:
bdata.head(10)

,job_title,salary,location,remote_location,compnay_size,expereince_level,employment_type,skills
0,Sr.,0,120k,C2C,Large,Excel;R,Product Data Analyst,False
1,DATA ANALYST,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,10000+,Sr.,Freelance,"AWS, Python, Google Cloud, Power BI"
2,Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Large,Principal,Contract,"Python, , Excel"
3,Marketing Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,EN,W2,"Tableau , Azure , R , Python ,"
4,Data Analyst II,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Entry-level,PT,"Python , Tableau , Azure , Google Cloud , SQL"
5,Senior Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,1-10,MI,Part-time,"Excel, R"
6,Senior Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Startup,Principal,FT,"Python, AWS"
7,Sr. Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Medium,Junior,W2,"Tableau, Power BI, Python, , AWS"
8,Marketing Data Analyst,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,MI,FT,"Google Cloud, Azure, Excel, Python, SQL"
9,DATA ANALYST,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Unknown,MI,Temporary,", Azure, Excel, SQL, R"

In [ ]:
bdata.tail(15)

,job_title,salary,location,remote_location,compnay_size,expereince_level,employment_type,skills
2485,BI Analyst,90000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,500,0-2 years,W2,"Google Cloud, Python"
2486,Jr. Data Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,500,Principal,C2C,"Python, SQL, AWS, Excel"
2487,Junior Data Analyst,14000000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Medium,Junior,Full-time,"Azure,Power BI,Google Cloud"
2488,Jr. Data Analyst,70000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,500,0-2 years,Contract,"SQL,Tableau,Power BI"
2489,Product Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,1-10,Entry-level,Part-time,"AWS , R , Power BI"
2490,Data Analyst II,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,1-10,Entry-level,FT,", Excel, Google Cloud, Python"
2491,Senior Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,EN,Full-time,None
2492,DATA ANALYST,8090000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Medium,EN,C2C,"Azure , , Tableau , AWS , R"
2493,Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,10000+,Sr.,Freelance,"AWS , Google Cloud"
2494,Marketing Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Startup,Senior,Freelance,"Power BI,SQL,Azure"
2495,Sr. Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,500,5+ years,FT,"SQL, Tableau, Excel"
2496,Data Analytics Specialist,50000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,1-10,Jr,Part-time,"AWS , SQL , R , Python"
2497,BI Analyst,50,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,501-1000,Junior,Temporary,"R,Excel"
2498,Junior Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Jr,Temporary,", AWS, Azure"
2499,BI Analyst,90000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,EN,Temporary,"Tableau, R, AWS"

In [ ]:
bdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_title         2499 non-null   object
 1   salary            2500 non-null   object
 2   location          2500 non-null   object
 3   remote_location   2500 non-null   object
 4   compnay_size      2499 non-null   object
 5   expereince_level  2500 non-null   object
 6   employment_type   2500 non-null   object
 7   skills            2387 non-null   object
dtypes: object(8)
memory usage: 156.4+ KB

### Cleaning the Experience Level

Cleaning the expereince level we will

Assigning each level a number of experience
1. Pr = 4  (Highest)
2. Sr = 3
3. Mi = 2
4. Jr = 1  (Lowest)

Things to be done in the `expereince_level` column
1.   Remove any special character from the column
2.   Create a new column and assign numbers to new column called `experience_level_values`, this new column will be use for training our model
3.   Convert `5+ years` to `Mid`
4.   Convert `Principal` to `Pr`
5.   Convert `0-5 years` to `Jr`
6.   Convert `0-2 years` to Jr
8.   Convert `SE` to `Sr`
9.   Convert `MI` to `Mi`

In [ ]:
# Rename the 'compnay_size' to 'company_size' & 'expereince_level' to 'experience_level'
bdata.rename(columns={'compnay_size': 'company_size', 'expereince_level': 'experience_level'}, inplace=True)  # Set inplace= True to save the changes

In [ ]:
# 1. Reload bdata to fix the 'Series' overwrite issue
# bdata = pd.read_csv('/content/backup_mdata.csv')

# 2. We assign the result back to the specific column, not the whole dataframe variable
bdata['experience_level'] = bdata['experience_level'].replace({
    '0-5 yrs': 'Jr',
    '5+ years': 'Mi',
    '0-2 years': 'Jr',
    'Principal': 'Pr',
    'Sr.': 'Sr',
    'SE': 'Sr',
    'MI': 'Mi',
    'EN': 'None',
    'Junior': 'Jr',
    'Senior': 'Sr',
    'Nan': 'None',
    'Entry-level': 'Jr'
})

# 3. View the results
bdata['experience_level'].head(35)

0     Excel;R
1          Sr
2          Pr
3        None
4          Jr
5          Mi
6          Pr
7          Jr
8          Mi
9          Mi
10         Sr
11         Sr
12         Mi
13         Mi
14         Jr
15         Sr
16         Jr
17         Mi
18         Mi
19         Pr
20         Jr
21         Mi
22       None
23         Jr
24       None
25         Sr
26         Mi
27         Jr
28         Jr
29         Mi
30       None
31         Sr
32         Sr
33         Sr
34         Pr
Name: experience_level, dtype: object

In [ ]:
bdata.head(15)

,job_title,salary,location,remote_location,company_size,experience_level,employment_type,skills
0,Sr.,0,120k,C2C,Large,Excel;R,Product Data Analyst,False
1,DATA ANALYST,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,10000+,Sr,Freelance,"AWS, Python, Google Cloud, Power BI"
2,Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Large,Pr,Contract,"Python, , Excel"
3,Marketing Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,None,W2,"Tableau , Azure , R , Python ,"
4,Data Analyst II,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Jr,PT,"Python , Tableau , Azure , Google Cloud , SQL"
5,Senior Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,1-10,Mi,Part-time,"Excel, R"
6,Senior Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Startup,Pr,FT,"Python, AWS"
7,Sr. Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Medium,Jr,W2,"Tableau, Power BI, Python, , AWS"
8,Marketing Data Analyst,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,Mi,FT,"Google Cloud, Azure, Excel, Python, SQL"
9,DATA ANALYST,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Unknown,Mi,Temporary,", Azure, Excel, SQL, R"
10,Product Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,501-1000,Sr,W2,"Excel , Azure , R , Google Cloud , Tableau"
11,Marketing Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,500,Sr,FT,"Tableau,Azure,SQL,Power BI"
12,BI Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,1-10,Mi,Contract,"SQL, R, Tableau, Power BI, Google Cloud"
13,DATA ANALYST,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,501-1000,Mi,Contract,"AWS, Python, Google Cloud, Tableau, R"
14,Data Analyst - Remote,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,Jr,PT,"AWS, Azure, Excel"

In [ ]:
# Map new values
mapping = {'Pr': 4, 'Sr': 3, 'Mi': 2, 'Jr': 1}

# # Create a new column in bdata and map values to 'expereince_level_values`
bdata['experience_level_value'] = bdata['experience_level'].map(mapping).fillna(0).astype(int)

In [ ]:
# Shows the new column
# bdata['expereince_level_value'].tail(25)

In [ ]:
# Show the current view of the table so far
bdata.head(10)

,job_title,salary,location,remote_location,company_size,experience_level,employment_type,skills,experience_level_value
0,Sr.,0,120k,C2C,Large,Excel;R,Product Data Analyst,False,0
1,DATA ANALYST,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,10000+,Sr,Freelance,"AWS, Python, Google Cloud, Power BI",3
2,Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Large,Pr,Contract,"Python, , Excel",4
3,Marketing Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,None,W2,"Tableau , Azure , R , Python ,",0
4,Data Analyst II,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Jr,PT,"Python , Tableau , Azure , Google Cloud , SQL",1
5,Senior Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,1-10,Mi,Part-time,"Excel, R",2
6,Senior Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Startup,Pr,FT,"Python, AWS",4
7,Sr. Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Medium,Jr,W2,"Tableau, Power BI, Python, , AWS",1
8,Marketing Data Analyst,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,Mi,FT,"Google Cloud, Azure, Excel, Python, SQL",2
9,DATA ANALYST,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Unknown,Mi,Temporary,", Azure, Excel, SQL, R",2

### Cleaning the Company Size

To clean the company size column, we


1.  Rename `compnay_size` to `company_size`
2.  Come up with a way to distinguish the length of the company size
3.  Remove any special character from column such as `-`,`+`,`
4.  Remove any words such as `Startup`,`Unknown`,`Medium` and `Large`

In [ ]:
bdata['company_size'].head(100)

0        Large
1       10000+
2        Large
3      Unknown
4      Unknown
5         1-10
6      Startup
7       Medium
8        Large
9      Unknown
10    501-1000
11         500
12        1-10
13    501-1000
14       Large
15    501-1000
16      Medium
17     Startup
18    501-1000
19     Startup
20    501-1000
21     Startup
22    501-1000
23      10000+
24        1-10
25        1-10
26     Unknown
27     Startup
28        1-10
29     Unknown
30        1-10
31      Medium
32      Medium
33     Startup
34    501-1000
35      Medium
36         500
37     Startup
38      Medium
39    501-1000
40      10000+
41        1-10
42        1-10
43     Startup
44        1-10
45     Unknown
46         500
47         500
48    501-1000
49    501-1000
50     Unknown
51      Medium
52        1-10
53    501-1000
54     Startup
55        1-10
56        1-10
57     Unknown
58     Startup
59     Startup
60         500
61     Unknown
62         500
63     Unknown
64     Startup
65        1-10
66       Large
67     Unknown
68     Unknown
69         500
70         500
71       Large
72     Unknown
73    501-1000
74     Unknown
75       Large
76    501-1000
77       Large
78     Startup
79      10000+
80       Large
81      10000+
82     Startup
83         500
84        1-10
85    501-1000
86      10000+
87     Startup
88     Startup
89        1-10
90      Medium
91         500
92        1-10
93     Unknown
94       Large
95       Large
96       Large
97      10000+
98        1-10
99    501-1000
Name: company_size, dtype: object

In [ ]:
# Create a function to clean the Company Column
def clean_company_size(company_size):

    # Map any words such as 'Startup', 'Unknown','Medium' and 'Large'
    mapping = {
        '501-1000': 'Large',
        '500': 'Small',
        '1-10': 'Startup',
        '10000+': 'Huge'
    }
    # Return the mapped value or the original if not in mapping
    return mapping.get(str(company_size), company_size)

# Apply the function to bdata dataframe
bdata['company_size'] = bdata['company_size'].apply(clean_company_size)

In [ ]:
# Create a new column called 'company_size_value' based on `company_size'
# Map new values
mapping = {'Unknown': 0, 'Startup': 1, 'Medium': 2, 'Large': 3, 'Huge': 4}

# # Create a new column in bdata and map values to 'expereince_level_values`
bdata['company_size_value'] = bdata['company_size'].map(mapping).fillna(0).astype(int)

In [ ]:
bdata.head(15)

,job_title,salary,location,remote_location,company_size,experience_level,employment_type,skills,experience_level_value,company_size_value
0,Sr.,0,120k,C2C,Large,Excel;R,Product Data Analyst,False,0,3
1,DATA ANALYST,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Huge,Sr,Freelance,"AWS, Python, Google Cloud, Power BI",3,4
2,Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Large,Pr,Contract,"Python, , Excel",4,3
3,Marketing Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,None,W2,"Tableau , Azure , R , Python ,",0,0
4,Data Analyst II,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Jr,PT,"Python , Tableau , Azure , Google Cloud , SQL",1,0
5,Senior Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Startup,Mi,Part-time,"Excel, R",2,1
6,Senior Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Startup,Pr,FT,"Python, AWS",4,1
7,Sr. Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Medium,Jr,W2,"Tableau, Power BI, Python, , AWS",1,2
8,Marketing Data Analyst,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,Mi,FT,"Google Cloud, Azure, Excel, Python, SQL",2,3
9,DATA ANALYST,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Unknown,Mi,Temporary,", Azure, Excel, SQL, R",2,0
10,Product Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Large,Sr,W2,"Excel , Azure , R , Google Cloud , Tableau",3,3
11,Marketing Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Small,Sr,FT,"Tableau,Azure,SQL,Power BI",3,0
12,BI Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Startup,Mi,Contract,"SQL, R, Tableau, Power BI, Google Cloud",2,1
13,DATA ANALYST,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Large,Mi,Contract,"AWS, Python, Google Cloud, Tableau, R",2,3
14,Data Analyst - Remote,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,Jr,PT,"AWS, Azure, Excel",1,3

### Cleaning Employment Type

To clean the `employment_type` column

1. Generate a list of `employment_type` to convert to number values
2. Convert `FT` to `Full Time`
3. Convert `C2C` to
4. Convert `PT` to `Part-time`
5. Convert `W2` to `Reguler`

In [ ]:
bdata.head(25)

,job_title,salary,location,remote_location,company_size,experience_level,employment_type,skills,experience_level_value,company_size_value
0,Sr.,0,120k,C2C,Large,Excel;R,Product Data Analyst,False,0,3
1,DATA ANALYST,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Huge,Sr,Freelance,"AWS, Python, Google Cloud, Power BI",3,4
2,Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Large,Pr,Contract,"Python, , Excel",4,3
3,Marketing Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,None,W2,"Tableau , Azure , R , Python ,",0,0
4,Data Analyst II,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Jr,PT,"Python , Tableau , Azure , Google Cloud , SQL",1,0
5,Senior Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Startup,Mi,Part-time,"Excel, R",2,1
6,Senior Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Startup,Pr,FT,"Python, AWS",4,1
7,Sr. Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Medium,Jr,W2,"Tableau, Power BI, Python, , AWS",1,2
8,Marketing Data Analyst,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,Mi,FT,"Google Cloud, Azure, Excel, Python, SQL",2,3
9,DATA ANALYST,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Unknown,Mi,Temporary,", Azure, Excel, SQL, R",2,0
10,Product Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Large,Sr,W2,"Excel , Azure , R , Google Cloud , Tableau",3,3
11,Marketing Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Small,Sr,FT,"Tableau,Azure,SQL,Power BI",3,0
12,BI Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Startup,Mi,Contract,"SQL, R, Tableau, Power BI, Google Cloud",2,1
13,DATA ANALYST,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Large,Mi,Contract,"AWS, Python, Google Cloud, Tableau, R",2,3
14,Data Analyst - Remote,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,Jr,PT,"AWS, Azure, Excel",1,3
15,Junior Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Large,Sr,Full-time,None,3,3
16,Data Analyst,50,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Medium,Jr,Part-time,"Excel,",1,2
17,Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Startup,Mi,Full-time,"Python, AWS, R",2,1
18,DATA ANALYST,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Large,Mi,PT,"Python, Power BI, AWS, Azure,",2,3
19,Senior Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Startup,Pr,Freelance,"Python, Excel, R",4,1
20,Senior Data Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Large,Jr,W2,"Azure,",1,3
21,BI Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Startup,Mi,PT,"Azure, SQL, Excel, Python",2,1
22,Data Analyst - Remote,50,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Large,None,Contract,"Azure,AWS,Power BI",0,3
23,Data Analyst,50000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Huge,Jr,PT,", R, Python, Azure",1,4
24,BI Analyst,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Startup,None,C2C,"SQL,Google Cloud,Python,Excel,Azure",0,1

In [ ]:
bdata['employment_type'].head(45)

0     Product Data Analyst
1                Freelance
2                 Contract
3                       W2
4                       PT
5                Part-time
6                       FT
7                       W2
8                       FT
9                Temporary
10                      W2
11                      FT
12                Contract
13                Contract
14                      PT
15               Full-time
16               Part-time
17               Full-time
18                      PT
19               Freelance
20                      W2
21                      PT
22                Contract
23                      PT
24                     C2C
25               Freelance
26               Full-time
27                     C2C
28                      PT
29                     C2C
30                Contract
31                      PT
32               Full-time
33                      FT
34                      PT
35               Full-time
36               Freelance
37               Full-time
38                Contract
39                      W2
40               Part-time
41               Part-time
42                Contract
43                Contract
44               Part-time
Name: employment_type, dtype: object

In [ ]:
bdata['employment_type'].tail(50)

2450    Part-time
2451           PT
2452    Full-time
2453           W2
2454          C2C
2455     Contract
2456    Freelance
2457    Temporary
2458           W2
2459          C2C
2460     Contract
2461    Full-time
2462           PT
2463    Temporary
2464           FT
2465           FT
2466    Full-time
2467           W2
2468           W2
2469           W2
2470           FT
2471          C2C
2472     Contract
2473    Full-time
2474           W2
2475     Contract
2476          C2C
2477          C2C
2478     Contract
2479     Contract
2480           PT
2481    Full-time
2482    Freelance
2483    Part-time
2484           W2
2485           W2
2486          C2C
2487    Full-time
2488     Contract
2489    Part-time
2490           FT
2491    Full-time
2492          C2C
2493    Freelance
2494    Freelance
2495           FT
2496    Part-time
2497    Temporary
2498    Temporary
2499    Temporary
Name: employment_type, dtype: object

In [ ]:
# Create a function for employment_type
def clean_employment_type(employment_type):
    # Mapping from abbreviations to full names
    mapping = {
        'FT': 'Full-time',
        'PT': 'Part-time',
        'W2': 'Regular',
        'C2C': 'Contract'
    }

    # First apply mapping (if it exists)
    cleaned = mapping.get(employment_type, employment_type)

    # Allowed values after cleaning
    allowed_types = ['Full-time', 'Part-time', 'Regular', 'Contract', 'Freelance', 'Temporary']


    # If value (after mapping) is allowed, keep it. Otherwise return None.
    if cleaned in allowed_types:
        return cleaned
    else:
        return None

# Apply the function
bdata['employment_type'] = bdata['employment_type'].apply(clean_employment_type)

### Quick Check on the Dataframe

Everything seems to be in order, we are almost done.

In [ ]:
bdata.head(25)

,job_title,salary,location,remote_location,company_size,experience_level,employment_type,skills,experience_level_value,company_size_value
0,Sr.,0,120k,C2C,Large,Excel;R,None,False,0,3
1,DATA ANALYST,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Huge,Sr,Freelance,"AWS, Python, Google Cloud, Power BI",3,4
2,Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Large,Pr,Contract,"Python, , Excel",4,3
3,Marketing Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,None,Regular,"Tableau , Azure , R , Python ,",0,0
4,Data Analyst II,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Jr,Part-time,"Python , Tableau , Azure , Google Cloud , SQL",1,0
5,Senior Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Startup,Mi,Part-time,"Excel, R",2,1
6,Senior Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Startup,Pr,Full-time,"Python, AWS",4,1
7,Sr. Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Medium,Jr,Regular,"Tableau, Power BI, Python, , AWS",1,2
8,Marketing Data Analyst,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,Mi,Full-time,"Google Cloud, Azure, Excel, Python, SQL",2,3
9,DATA ANALYST,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Unknown,Mi,Temporary,", Azure, Excel, SQL, R",2,0
10,Product Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Large,Sr,Regular,"Excel , Azure , R , Google Cloud , Tableau",3,3
11,Marketing Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Small,Sr,Full-time,"Tableau,Azure,SQL,Power BI",3,0
12,BI Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Startup,Mi,Contract,"SQL, R, Tableau, Power BI, Google Cloud",2,1
13,DATA ANALYST,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Large,Mi,Contract,"AWS, Python, Google Cloud, Tableau, R",2,3
14,Data Analyst - Remote,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,Jr,Part-time,"AWS, Azure, Excel",1,3
15,Junior Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Large,Sr,Full-time,None,3,3
16,Data Analyst,50,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Medium,Jr,Part-time,"Excel,",1,2
17,Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Startup,Mi,Full-time,"Python, AWS, R",2,1
18,DATA ANALYST,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Large,Mi,Part-time,"Python, Power BI, AWS, Azure,",2,3
19,Senior Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Startup,Pr,Freelance,"Python, Excel, R",4,1
20,Senior Data Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Large,Jr,Regular,"Azure,",1,3
21,BI Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Startup,Mi,Part-time,"Azure, SQL, Excel, Python",2,1
22,Data Analyst - Remote,50,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Large,None,Contract,"Azure,AWS,Power BI",0,3
23,Data Analyst,50000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Huge,Jr,Part-time,", R, Python, Azure",1,4
24,BI Analyst,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Startup,None,Contract,"SQL,Google Cloud,Python,Excel,Azure",0,1

### Creating A New Employment Type Column

Create a new int column and mapping employment types to numbers


1.  Full-time = 1
2.  Part-time = 2
3.  Regular = 3
4.  Contract = 4
5.  Temporary = 5
6.  Freelance = 6

In [ ]:
bdata['employment_type'].head(25)

0          None
1     Freelance
2      Contract
3       Regular
4     Part-time
5     Part-time
6     Full-time
7       Regular
8     Full-time
9     Temporary
10      Regular
11    Full-time
12     Contract
13     Contract
14    Part-time
15    Full-time
16    Part-time
17    Full-time
18    Part-time
19    Freelance
20      Regular
21    Part-time
22     Contract
23    Part-time
24     Contract
Name: employment_type, dtype: object

In [ ]:
# Create a new column called 'employment_type_value' based on `employment_type'

# Map new values
mapping = {'Full-time': 1, 'Part-time': 2, 'Regular': 3, 'Contract': 4, 'Temporary': 5, 'Freelance': 6}


# Create a new column in bdata and map values to 'expereince_level_values`
bdata['employment_type_value'] = bdata['employment_type'].map(mapping).fillna(0).astype(int)

In [ ]:
# After creating the new column 'expereince_level_values`
bdata.head(10)

,job_title,salary,location,remote_location,company_size,experience_level,employment_type,skills,experience_level_value,company_size_value,employment_type_value
0,Sr.,0,120k,C2C,Large,Excel;R,None,False,0,3,0
1,DATA ANALYST,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Huge,Sr,Freelance,"AWS, Python, Google Cloud, Power BI",3,4,6
2,Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Large,Pr,Contract,"Python, , Excel",4,3,4
3,Marketing Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,None,Regular,"Tableau , Azure , R , Python ,",0,0,3
4,Data Analyst II,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Jr,Part-time,"Python , Tableau , Azure , Google Cloud , SQL",1,0,2
5,Senior Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Startup,Mi,Part-time,"Excel, R",2,1,2
6,Senior Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Startup,Pr,Full-time,"Python, AWS",4,1,1
7,Sr. Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Medium,Jr,Regular,"Tableau, Power BI, Python, , AWS",1,2,3
8,Marketing Data Analyst,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,Mi,Full-time,"Google Cloud, Azure, Excel, Python, SQL",2,3,1
9,DATA ANALYST,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Unknown,Mi,Temporary,", Azure, Excel, SQL, R",2,0,5

### Create function that convert Euro to USD

In [ ]:
# Create function
def search_amount(filtered_search):

   # query bdata dataframe to search the salary column that find a match to `$50/hr`
   # filtered_search = bdata[bdata['salary'] == '$50/hr']
   filtered_search = bdata['salary'].query('$50/hr')


   # once a cell is found, multiple matching cells to yearly amoun

   return search_amount

In [ ]:
print(search_amount)

<function search_amount at 0x7b221753a2a0>

In [ ]:
bdata.head(25)

,job_title,salary,location,remote_location,company_size,experience_level,employment_type,skills,experience_level_value,company_size_value,employment_type_value
0,Sr.,0,120k,C2C,Large,Excel;R,None,False,0,3,0
1,DATA ANALYST,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Huge,Sr,Freelance,"AWS, Python, Google Cloud, Power BI",3,4,6
2,Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Large,Pr,Contract,"Python, , Excel",4,3,4
3,Marketing Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,None,Regular,"Tableau , Azure , R , Python ,",0,0,3
4,Data Analyst II,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Jr,Part-time,"Python , Tableau , Azure , Google Cloud , SQL",1,0,2
5,Senior Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Startup,Mi,Part-time,"Excel, R",2,1,2
6,Senior Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Startup,Pr,Full-time,"Python, AWS",4,1,1
7,Sr. Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Medium,Jr,Regular,"Tableau, Power BI, Python, , AWS",1,2,3
8,Marketing Data Analyst,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,Mi,Full-time,"Google Cloud, Azure, Excel, Python, SQL",2,3,1
9,DATA ANALYST,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Unknown,Mi,Temporary,", Azure, Excel, SQL, R",2,0,5
10,Product Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Large,Sr,Regular,"Excel , Azure , R , Google Cloud , Tableau",3,3,3
11,Marketing Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Small,Sr,Full-time,"Tableau,Azure,SQL,Power BI",3,0,1
12,BI Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Startup,Mi,Contract,"SQL, R, Tableau, Power BI, Google Cloud",2,1,4
13,DATA ANALYST,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Large,Mi,Contract,"AWS, Python, Google Cloud, Tableau, R",2,3,4
14,Data Analyst - Remote,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,Jr,Part-time,"AWS, Azure, Excel",1,3,2
15,Junior Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Large,Sr,Full-time,None,3,3,1
16,Data Analyst,50,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Medium,Jr,Part-time,"Excel,",1,2,2
17,Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Startup,Mi,Full-time,"Python, AWS, R",2,1,1
18,DATA ANALYST,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Large,Mi,Part-time,"Python, Power BI, AWS, Azure,",2,3,2
19,Senior Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Startup,Pr,Freelance,"Python, Excel, R",4,1,6
20,Senior Data Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Large,Jr,Regular,"Azure,",1,3,3
21,BI Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Startup,Mi,Part-time,"Azure, SQL, Excel, Python",2,1,2
22,Data Analyst - Remote,50,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Large,None,Contract,"Azure,AWS,Power BI",0,3,4
23,Data Analyst,50000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Huge,Jr,Part-time,", R, Python, Azure",1,4,2
24,BI Analyst,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Startup,None,Contract,"SQL,Google Cloud,Python,Excel,Azure",0,1,4

In [ ]:
bdata.tail(150)

,job_title,salary,location,remote_location,company_size,experience_level,employment_type,skills,experience_level_value,company_size_value,employment_type_value
2350,Sr. Data Analyst,14000000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Huge,None,Full-time,"Excel, Azure, R",0,4,1
2351,Data Analyst,50000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Jr,Freelance,", AWS",1,0,6
2352,Jr. Data Analyst,14000000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Large,Mi,Regular,"Excel,Python,Tableau",2,3,3
2353,BI Analyst,50,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Startup,Sr,Contract,"SQL, Power BI,",3,1,4
2354,Jr. Data Analyst,50,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,Sr,Contract,"Google Cloud, Python,",3,3,4
2355,Product Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Large,Mi,Part-time,"Excel, Google Cloud, Power BI, Azure, SQL",2,3,2
2356,Sr. Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Startup,Jr,Regular,"AWS, Excel, SQL",1,1,3
2357,Data Analyst!!!,70000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Startup,Jr,Contract,", R , Python , Tableau , Excel",1,1,4
2358,Product Data Analyst,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Small,Mi,Full-time,"Azure, AWS",2,0,1
2359,Data Analytics Specialist,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Unknown,Jr,Regular,"Python , Excel",1,0,3
2360,Marketing Data Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Medium,Jr,Contract,"Tableau, SQL, Excel",1,2,4
2361,Data Analytics Specialist,50000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Startup,Pr,Temporary,", Excel, SQL, Tableau, Python",4,1,5
2362,Product Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Small,Sr,Full-time,", AWS, Python, Azure",3,0,1
2363,Sr. Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Large,Jr,Freelance,", AWS",1,3,6
2364,Data Analyst!!!,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Small,Pr,Temporary,"R, Excel",4,0,5
2365,Sr. Data Analyst,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Huge,Sr,Freelance,"AWS , SQL , Python",3,4,6
2366,DATA ANALYST,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Large,Jr,Temporary,"Power BI ,",1,3,5
2367,Marketing Data Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Startup,Jr,Part-time,"Azure , Python",1,1,2
2368,Data Analyst!!!,50,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Startup,Jr,Part-time,"SQL , Azure , Tableau , Excel",1,1,2
2369,Data Analytics Specialist,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Huge,None,Temporary,"SQL , AWS , , Power BI",0,4,5
2370,Data Analyst,50000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Startup,Jr,Freelance,"AWS , Excel",1,1,6
2371,Data Analyst II,8090000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Large,Mi,Contract,"AWS , Azure , Tableau , R , Power BI",2,3,4
2372,Senior Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Unknown,None,Freelance,"Google Cloud,Power BI",0,0,6
2373,"['Excel', 'SQL', 'Power BI', 'Google Cloud']",0,120k,0-2 years,Large,Full-time,None,False,0,3,0
2374,Data Analyst!!!,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Startup,None,Full-time,"AWS , Excel , R , , Python",0,1,1
2375,Senior Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Medium,Mi,Full-time,"AWS, , Python, Power BI, Excel",2,2,1
2376,Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Sr,Part-time,"Google Cloud , Excel , AWS , SQL",3,0,2
2377,Jr. Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Unknown,Mi,Contract,"Azure, R, SQL, Python,",2,0,4
2378,Data Analyst II,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Huge,Sr,Part-time,"Python , , AWS , Tableau , Azure",3,4,2
2379,BI Analyst,8090000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Startup,Mi,Contract,"Power BI,Azure,Excel",2,1,4
2380,Junior Data Analyst,70000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Medium,Jr,Contract,"Google Cloud, SQL, Python, Tableau, Excel",1,2,4
2381,BI Analyst,50000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Large,Sr,Part-time,"Power BI , SQL , Excel , Azure , Google Cloud",3,3,2
2382,Data Analytics Specialist,90000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,Jr,Full-time,"R,Excel,Power BI",1,0,1
2383,Data Analyst II,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Large,Mi,Freelance,"AWS,SQL,Azure,Power BI",2,3,6
2384,Data Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Large,Jr,Contract,", AWS, Python, Tableau",1,3,4
2385,Data Analyst!!!,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Medium,Mi,Contract,"R, Excel",2,2,4
2386,Product Data Analyst,90000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Medium,Jr,Part-time,"R,Tableau,Python",1,2,2
2387,Senior Data Analyst,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Large,Jr,Freelance,"AWS, SQL, R, Power BI",1,3,6
2388,Data Analyst II,90000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Huge,Mi,Contract,"Excel, , Python",2,4,4
2389,Jr. Data Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Startup,Mi,Contract,"Power BI,Tableau,Python,AWS",2,1,4
2390,Data Analyst!!!,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Small,Jr,Full-time,"Power BI,SQL",1,0,1
2391,Data Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Large,Sr,Part-time,"Power BI , Tableau , Google Cloud",3,3,2
2392,Product Data Analyst,14000000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,Jr,Freelance,"SQL , Excel , Python ,",1,0,6
2393,Jr. Data Analyst,70000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Medium,Jr,Contract,"Tableau,Google Cloud",1,2,4
2394,Data Analyst II,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Startup,Mi,Contract,"Azure, Python",2,1,4
2395,DATA ANALYST,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Medium,Sr,Part-time,None,3,2,2
2396,Data Analyst!!!,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Huge,Pr,Contract,"Excel , Power BI , , Tableau , Google Cloud",4,4,4
2397,Jr. Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Unknown,Pr,Part-time,"Tableau , R , Azure , Power BI ,",4,0,2
2398,Junior Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Startup,Mi,Temporary,"Excel, AWS, Tableau, Azure",2,1,5
2399,Junior Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Medium,Jr,Full-time,"Tableau, Google Cloud, Excel",1,2,1
2400,Marketing Data Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Medium,Pr,Freelance,"R, Tableau,",4,2,6
2401,Data Analytics Specialist,50000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Huge,Mi,Regular,"Azure, SQL, R",2,4,3
2402,Junior Data Analyst,8090000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Unknown,None,Contract,"Tableau, Azure, Excel, Power BI",0,0,4
2403,Jr. Data Analyst,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Large,Jr,Part-time,"AWS, Google Cloud, , Tableau, Azure",1,3,2
2404,Sr. Data Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Huge,Jr,Contract,"Power BI, R, Google Cloud, SQL, Azure",1,4,4
2405,Data Analytics Specialist,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Unknown,Sr,Temporary,"Tableau , Python , , R",3,0,5
2406,Marketing Data Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Startup,Mi,Freelance,"R, Excel",2,1,6
2407,Data Analytics Specialist,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Medium,Mi,Part-time,"Google Cloud , Power BI",2,2,2
2408,Jr. Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Medium,Mi,Part-time,"Tableau, SQL, Python, Azure",2,2,2
2409,Data Analyst!!!,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Small,Jr,Part-time,"Excel, AWS, Power BI,",1,0,2
2410,BI Analyst,50000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Startup,Pr,Full-time,"Tableau, Python, Google Cloud",4,1,1
2411,Data Analyst II,14000000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Large,Jr,Temporary,"Tableau,Azure,Excel",1,3,5
2412,Data Analyst!!!,14000000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Large,Mi,Full-time,", Google Cloud, SQL, Azure, AWS",2,3,1
2413,DATA ANALYST,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Large,None,Contract,"Tableau, Power BI, Azure, Google Cloud",0,3,4
2414,Marketing Data Analyst,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Huge,Mi,Freelance,"Azure,AWS,Python,R",2,4,6
2415,Junior Data Analyst,70000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Startup,Pr,Contract,"Azure, AWS, SQL, R, Python",4,1,4
2416,DATA ANALYST,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Large,Jr,Temporary,",Power BI,Tableau,Google Cloud,AWS",1,3,5
2417,Junior Data Analyst,8090000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Large,Mi,Full-time,", SQL, Tableau, Python",2,3,1
2418,Data Analyst - Remote,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Medium,Mi,Freelance,"Power BI, Azure, SQL, Tableau",2,2,6
2419,Sr. Data Analyst,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Small,Pr,Full-time,"Power BI,Azure",4,0,1
2420,BI Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Unknown,Pr,Full-time,"Google Cloud, , Azure, Excel",4,0,1
2421,Data Analyst II,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Startup,Jr,Full-time,"AWS , R , , SQL , Google Cloud",1,1,1
2422,Jr. Data Analyst,90000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Unknown,Mi,Contract,"Excel, Azure,",2,0,4
2423,DATA ANALYST,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Small,Jr,Regular,"Python, Tableau, AWS",1,0,3
2424,DATA ANALYST,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Huge,Jr,Temporary,"Google Cloud , Excel , AWS , Azure",1,4,5
2425,Jr. Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Startup,Mi,Full-time,"SQL , Power BI , R",2,1,1
2426,Product Data Analyst,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Startup,Sr,Full-time,"SQL , AWS , Azure",3,1,1
2427,Data Analyst II,70000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Startup,Sr,Freelance,None,3,1,6
2428,Data Analyst II,8090000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Startup,Sr,Contract,"Tableau,Python,Excel,Azure",3,1,4
2429,Data Analytics Specialist,8090000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Small,Jr,Contract,"Azure,Power BI,Python,SQL",1,0,4
2430,Data Analyst - Remote,50,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Startup,Mi,Contract,"R, Python, Excel, Google Cloud, Azure",2,1,4
2431,Marketing Data Analyst,90000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Small,Mi,Part-time,"Google Cloud , Azure , Python",2,0,2
2432,Junior Data Analyst,8090000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Small,Sr,Full-time,None,3,0,1
2433,Sr. Data Analyst,50000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Large,Sr,Part-time,"AWS, Power BI, Python",3,3,2
2434,Marketing Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Startup,Jr,Contract,"R, Azure, , Power BI",1,1,4
2435,Data Analytics Specialist,14000000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Jr,Freelance,",Tableau,Python,Google Cloud,Azure",1,0,6
2436,Jr. Data Analyst,50,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Medium,Mi,Temporary,"Excel, Google Cloud, AWS, Tableau, Azure",2,2,5
2437,Data Analytics Specialist,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Unknown,Jr,Part-time,"R, Azure, AWS",1,0,2
2438,Data Analyst,8090000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Huge,Jr,Part-time,"Google Cloud, Power BI",1,4,2
2439,Marketing Data Analyst,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Large,Sr,Temporary,"Azure,",3,3,5
2440,Jr. Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Small,Jr,Part-time,"Tableau , , SQL",1,0,2
2441,Data Analyst - Remote,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Startup,Sr,Full-time,"R, SQL",3,1,1
2442,Junior Data Analyst,50000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Large,Pr,Full-time,"R,Power BI",4,3,1
2443,Data Analyst II,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Large,Jr,Part-time,"Tableau , AWS , Power BI",1,3,2
2444,Product Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Startup,Jr,Contract,", SQL , Python , Azure",1,1,4
2445,Data Analyst!!!,8090000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Medium,Jr,Freelance,"Power BI , Google Cloud , SQL , Excel , R",1,2,6
2446,Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Medium,Mi,Full-time,"Google Cloud , Tableau , SQL , Azure",2,2,1
2447,DATA ANALYST,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Startup,Jr,Full-time,"Tableau,AWS,Google Cloud,Python,SQL",1,1,1
2448,Product Data Analyst,70000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Small,Jr,Part-time,"Tableau, Google Cloud, Excel",1,0,2
2449,Product Data Analyst,70000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Small,Pr,Full-time,"R , Azure",4,0,1
2450,Junior Data Analyst,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Huge,Pr,Part-time,"Power BI, R, Google Cloud",4,4,2
2451,Jr. Data Analyst,70000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Startup,None,Part-time,"R, Google Cloud, Tableau, Python",0,1,2
2452,BI Analyst,14000000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Startup,Jr,Full-time,"Power BI, Python, Google Cloud, R",1,1,1
2453,Data Analyst!!!,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Startup,Mi,Regular,"SQL,AWS,R,Tableau,Power BI",2,1,3
2454,Marketing Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Unknown,Mi,Contract,"Python, SQL, R, Google Cloud, Power BI",2,0,4
2455,Product Data Analyst,8090000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Mi,Contract,"Google Cloud, Power BI, Tableau, R, Python",2,0,4
2456,Sr. Data Analyst,50,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Huge,Jr,Freelance,"Excel, AWS",1,4,6
2457,Data Analyst,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Medium,Sr,Temporary,"AWS, R, , Google Cloud, Excel",3,2,5
2458,Sr. Data Analyst,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",0,Small,Jr,Regular,"AWS, Power BI, Azure, Tableau, R",1,0,3
2459,0-2 years,0,Power BI;Google Cloud;,0,80-90k,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Contract,Large,0,0,4
2460,Product Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,Mi,Contract,"Power BI, SQL, R",2,0,4
2461,Data Analyst!!!,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Startup,Jr,Full-time,"Azure , Power BI",1,1,1
2462,Data Analytics Specialist,8090000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,Mi,Part-time,"R, Tableau, Power BI, Excel, SQL",2,0,2
2463,Data Analyst,50,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Large,Mi,Temporary,"Azure, SQL, Google Cloud, Power BI",2,3,5
2464,Sr. Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Large,Sr,Full-time,"Azure, R, AWS",3,3,1
2465,DATA ANALYST,14000000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Unknown,Pr,Full-time,"Tableau, AWS",4,0,1
2466,Senior Data Analyst,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Large,None,Full-time,"Power BI, SQL",0,3,1
2467,Data Analyst!!!,8090000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Large,Pr,Regular,"Python, R, SQL, Azure",4,3,3
2468,Product Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Large,Mi,Regular,"SQL , R , Python ,",2,3,3
2469,Jr. Data Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Medium,Mi,Regular,"Azure, Google Cloud, AWS",2,2,3
2470,Jr. Data Analyst,50,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Startup,Sr,Full-time,"Google Cloud , Power BI , AWS , Excel , R",3,1,1
2471,Junior Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Startup,Jr,Contract,"Tableau,Excel,Google Cloud",1,1,4
2472,Data Analyst - Remote,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Unknown,Jr,Contract,"Power BI, Python, R, , Azure",1,0,4
2473,Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Unknown,Jr,Full-time,"Python,SQL,Azure",1,0,1
2474,Data Analyst - Remote,50,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Startup,Jr,Regular,"Azure,Python,R,SQL,Tableau",1,1,3
2475,Sr. Data Analyst,14000000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Large,Pr,Contract,"Google Cloud,Tableau,Power BI,Python",4,3,4
2476,Product Data Analyst,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Unknown,Sr,Contract,None,3,0,4
2477,Data Analytics Specialist,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Medium,Sr,Contract,"Tableau, R, Google Cloud, AWS",3,2,4
2478,Jr. Data Analyst,50000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Startup,Jr,Contract,"Azure , Tableau , R , SQL , Excel",1,1,4
2479,Jr. Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Startup,Pr,Contract,"AWS, SQL, Excel",4,1,4
2480,Data Analytics Specialist,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Large,Sr,Part-time,"R, AWS, Google Cloud, SQL, Tableau",3,3,2
2481,Data Analyst!!!,120000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",1,Startup,Sr,Full-time,"Excel,",3,1,1
2482,DATA ANALYST,65000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Partial,Unknown,Jr,Freelance,"Tableau, Python",1,0,6
2483,Data Analyst - Remote,14000000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Hybrid,Large,Jr,Part-time,", Azure, Power BI, R",1,3,2
2484,Sr. Data Analyst,0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",True,Unknown,Jr,Regular,"Google Cloud, AWS,",1,0,3
2485,BI Analyst,90000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Small,Jr,Regular,"Google Cloud, Python",1,0,3
2486,Jr. Data Analyst,70000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Small,Pr,Contract,"Python, SQL, AWS, Excel",4,0,4
2487,Junior Data Analyst,14000000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",False,Medium,Jr,Full-time,"Azure,Power BI,Google Cloud",1,2,1
2488,Jr. Data Analyst,70000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Temporarily Remote,Small,Jr,Contract,"SQL,Tableau,Power BI",1,0,4
2489,Product Data Analyst,110000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Startup,Jr,Part-time,"AWS , R , Power BI",1,1,2
2490,Data Analyst II,95000.0,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Startup,Jr,Full-time,", Excel, Google Cloud, Python",1,1,1
2491,Senior Data Analyst,95000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",Yes,Unknown,None,Full-time,None,0,0,1
2492,DATA ANALYST,8090000,"['New York, NY', 'San Francisco, CA', 'Dallas,...",No,Medium,None,Contract,"Azure , , Tableau , AWS , R",0,2,4

### Removing `[` & `]` from job title

In [ ]:
# Before Cleaning the
bdata['salary'].head(15)

0           0
1       65000
2       65000
3           0
4       65000
5           0
6       95000
7       65000
8      120000
9     95000.0
10     110000
11          0
12      70000
13          0
14     110000
Name: salary, dtype: object

In [ ]:
# Current view of `job title`
mdata['salary'].head(15)

0     ['New York, NY', 'San Francisco, CA', 'Dallas,...
1                                      65000Competitive
2                                      65000Competitive
3                                                   NaN
4                                               €65,000
5                                                   DOE
6                                                 95000
7                                               €65,000
8                                                  120k
9                                            85k - 105k
10                                               110000
11                                                  NaN
12                                            70000 USD
13                                                  NaN
14                                               110000
Name: salary, dtype: object

In [ ]:
# Removing the `[` & `]` from Location column
bdata['location'] = bdata['location'].str.replace(r'[\[\]]', '', regex=True)

In [ ]:
# After Cleaning the Location column
bdata.head(25)

,job_title,salary,location,remote_location,company_size,experience_level,employment_type,skills,experience_level_value,company_size_value,employment_type_value
0,Sr.,0,120k,C2C,Large,Excel;R,None,False,0,3,0
1,DATA ANALYST,65000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",No,Huge,Sr,Freelance,"AWS, Python, Google Cloud, Power BI",3,4,6
2,Data Analyst,65000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",1,Large,Pr,Contract,"Python, , Excel",4,3,4
3,Marketing Data Analyst,0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Yes,Unknown,None,Regular,"Tableau , Azure , R , Python ,",0,0,3
4,Data Analyst II,65000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Hybrid,Unknown,Jr,Part-time,"Python , Tableau , Azure , Google Cloud , SQL",1,0,2
5,Senior Data Analyst,0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Partial,Startup,Mi,Part-time,"Excel, R",2,1,2
6,Senior Data Analyst,95000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",False,Startup,Pr,Full-time,"Python, AWS",4,1,1
7,Sr. Data Analyst,65000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",1,Medium,Jr,Regular,"Tableau, Power BI, Python, , AWS",1,2,3
8,Marketing Data Analyst,120000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",0,Large,Mi,Full-time,"Google Cloud, Azure, Excel, Python, SQL",2,3,1
9,DATA ANALYST,95000.0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",False,Unknown,Mi,Temporary,", Azure, Excel, SQL, R",2,0,5
10,Product Data Analyst,110000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",False,Large,Sr,Regular,"Excel , Azure , R , Google Cloud , Tableau",3,3,3
11,Marketing Data Analyst,0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",False,Small,Sr,Full-time,"Tableau,Azure,SQL,Power BI",3,0,1
12,BI Analyst,70000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Temporarily Remote,Startup,Mi,Contract,"SQL, R, Tableau, Power BI, Google Cloud",2,1,4
13,DATA ANALYST,0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",1,Large,Mi,Contract,"AWS, Python, Google Cloud, Tableau, R",2,3,4
14,Data Analyst - Remote,110000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",0,Large,Jr,Part-time,"AWS, Azure, Excel",1,3,2
15,Junior Data Analyst,0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Hybrid,Large,Sr,Full-time,None,3,3,1
16,Data Analyst,50,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",1,Medium,Jr,Part-time,"Excel,",1,2,2
17,Data Analyst,110000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Partial,Startup,Mi,Full-time,"Python, AWS, R",2,1,1
18,DATA ANALYST,0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Hybrid,Large,Mi,Part-time,"Python, Power BI, AWS, Azure,",2,3,2
19,Senior Data Analyst,0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Temporarily Remote,Startup,Pr,Freelance,"Python, Excel, R",4,1,6
20,Senior Data Analyst,70000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Partial,Large,Jr,Regular,"Azure,",1,3,3
21,BI Analyst,70000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Yes,Startup,Mi,Part-time,"Azure, SQL, Excel, Python",2,1,2
22,Data Analyst - Remote,50,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",True,Large,None,Contract,"Azure,AWS,Power BI",0,3,4
23,Data Analyst,50000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Hybrid,Huge,Jr,Part-time,", R, Python, Azure",1,4,2
24,BI Analyst,120000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Yes,Startup,None,Contract,"SQL,Google Cloud,Python,Excel,Azure",0,1,4

### Checking Last Minute Issues:

In [ ]:
# Viewing the salary column
# Problem 1 : There are salaries with $0 and $50 no data analyst job will pay you $0 & $50, we need to fix that.
bdata['salary']

0              0
1          65000
2          65000
3              0
4          65000
5              0
6          95000
7          65000
8         120000
9        95000.0
10        110000
11             0
12         70000
13             0
14        110000
15             0
16            50
17        110000
18             0
19             0
20         70000
21         70000
22            50
23         50000
24        120000
25         65000
26       95000.0
27         50000
28         95000
29       70000.0
30            50
31            50
32             0
33       95000.0
34        110000
35        110000
36             0
37      14000000
38         95000
39       8090000
40       8090000
41        110000
42       95000.0
43             0
44        110000
45             0
46             0
47            50
48       95000.0
49         70000
50       95000.0
51       8090000
52         90000
53        120000
54       95000.0
55             0
56         70000
57         70000
58             0
59         50000
60            50
61             0
62        110000
63         65000
64         65000
65         65000
66       95000.0
67             0
68        110000
69         70000
70       95000.0
71         70000
72             0
73         90000
74       70000.0
75        110000
76         90000
77         65000
78         65000
79       8090000
80       70000.0
81         95000
82             0
83             0
84         95000
85         50000
86      14000000
87             0
88             0
89        110000
90         90000
91         70000
92             0
93       8090000
94         95000
95             0
96         65000
97             0
98       95000.0
99             0
100            0
101           50
102     14000000
103      95000.0
104           50
105       120000
106            0
107        50000
108            0
109       120000
110        65000
111            0
112        50000
113      95000.0
114       120000
115        90000
116            0
117     14000000
118      8090000
119        50000
120        70000
121            0
122            0
123        65000
124        70000
125        95000
126            0
127        95000
128            0
129        95000
130      70000.0
131       110000
132     14000000
133            0
134        50000
135        65000
136           50
137        90000
138        90000
139            0
140        95000
141        95000
142            0
143      70000.0
144       120000
145      8090000
146      95000.0
147        65000
148           50
149     14000000
150           50
151        90000
152     14000000
153        90000
154        65000
155           50
156            0
157       110000
158     14000000
159            0
160        65000
161       120000
162      95000.0
163       120000
164     14000000
165           50
166            0
167           50
168      95000.0
169        65000
170     14000000
171        90000
172        90000
173        90000
174      95000.0
175            0
176        95000
177            0
178      95000.0
179      95000.0
180            0
181            0
182        70000
183     14000000
184            0
185            0
186        95000
187            0
188        95000
189      70000.0
190           50
191            0
192       120000
193      8090000
194            0
195      70000.0
196        95000
197        65000
198        50000
199        90000
200        95000
201        70000
202     14000000
203      95000.0
204        50000
205        90000
206       120000
207        65000
208            0
209            0
210            0
211      8090000
212      95000.0
213      8090000
214        65000
215      8090000
216        95000
217        90000
218      95000.0
219        65000
220            0
221        95000
222     14000000
223            0
224        70000
225            0
226            0
227           50
228        65000
229        95000
230        65000
231        50000
232        65000
233            0
234        50000
235            0
236            0
237        65000
238        95000
239            0
240        95000
241           50
242        65000
243            0
244       120000
245     14000000
246     14000000
247           50
248      95000.0
249            0
250        90000
251            0
252       110000
253           50
254            0
255        65000
256        95000
257        65000
258        65000
259        65000
260        65000
261      95000.0
262       120000
263        50000
264        50000
265        90000
266        50000
267        50000
268        90000
269       120000
270      8090000
271            0
272        95000
273       120000
274      95000.0
275      70000.0
276        70000
277      8090000
278        95000
279        95000
280        65000
281            0
282            0
283            0
284        90000
285       110000
286        50000
287        90000
288        70000
289      8090000
290        70000
291        90000
292     14000000
293        95000
294        70000
295            0
296        90000
297      70000.0
298            0
299       120000
300            0
301            0
302            0
303        95000
304      95000.0
305            0
306        65000
307        65000
308       120000
309            0
310        70000
311            0
312        65000
313        70000
314      70000.0
315            0
316            0
317        65000
318        70000
319     14000000
320      8090000
321            0
322       110000
323     14000000
324       120000
325        70000
326      95000.0
327        95000
328            0
329        50000
330      70000.0
331        65000
332     14000000
333        50000
334            0
335        65000
336            0
337            0
338      70000.0
339        65000
340           50
341        50000
342        90000
343       120000
344            0
345            0
346        70000
347     14000000
348            0
349       120000
350            0
351           50
352        50000
353        50000
354      95000.0
355        95000
356      95000.0
357            0
358           50
359      8090000
360        95000
361        65000
362        50000
363       110000
364            0
365           50
366       110000
367       120000
368        90000
369        65000
370      95000.0
371        70000
372            0
373            0
374       120000
375        65000
376        95000
377       110000
378            0
379        90000
380            0
381      95000.0
382      8090000
383            0
384        90000
385            0
386            0
387      70000.0
388     14000000
389        65000
390      70000.0
391        65000
392       110000
393        90000
394      8090000
395           50
396       110000
397        90000
398       110000
399        95000
400        90000
401            0
402      8090000
403        70000
404      95000.0
405      8090000
406           50
407     14000000
408            0
409     14000000
410     14000000
411       110000
412      95000.0
413           50
414       120000
415        70000
416     14000000
417      95000.0
418        50000
419      70000.0
420      70000.0
421            0
422            0
423      8090000
424     14000000
425        50000
426        50000
427            0
428           50
429      95000.0
430        65000
431        65000
432       120000
433        90000
434      8090000
435      70000.0
436        50000
437        65000
438       110000
439       120000
440        90000
441            0
442        90000
443        50000
444        90000
445     14000000
446            0
447        50000
448        65000
449        90000
450      95000.0
451            0
452        50000
453            0
454            0
455        50000
456            0
457      95000.0
458        50000
459      8090000
460            0
461        65000
462        90000
463        70000
464      8090000
465        95000
466        90000
467           50
468     14000000
469            0
470      8090000
471      8090000
472      95000.0
473            0
474     14000000
475        70000
476        95000
477        50000
478        50000
479            0
480            0
481            0
482        90000
483      8090000
484      8090000
485      95000.0
486     14000000
487        50000
488        65000
489        65000
490            0
491       110000
492            0
493           50
494       110000
495        65000
496        90000
497        65000
498     14000000
499        90000
500       110000
501        65000
502        65000
503        95000
504        65000
505            0
506            0
507      70000.0
508        65000
509        65000
510       120000
511        95000
512        50000
513        65000
514     14000000
515        50000
516            0
517            0
518     14000000
519            0
520           50
521            0
522        65000
523           50
524        95000
525            0
526       120000
527        95000
528            0
529        65000
530           50
531            0
532      8090000
533        90000
534        50000
535      95000.0
536      70000.0
537        65000
538      8090000
539            0
540      95000.0
541        65000
542            0
543        50000
544     14000000
545        50000
546        95000
547            0
548        65000
549        95000
550        95000
551            0
552        70000
553           50
554        70000
555      95000.0
556        95000
557        70000
558        90000
559        90000
560       110000
561        90000
562      70000.0
563      8090000
564      95000.0
565        50000
566       110000
567      95000.0
568      70000.0
569        65000
570            0
571           50
572        90000
573        95000
574        95000
575      70000.0
576      70000.0
577      8090000
578      70000.0
579      70000.0
580        65000
581            0
582      70000.0
583      8090000
584        70000
585       120000
586       120000
587      95000.0
588            0
589            0
590        65000
591           50
592        65000
593     14000000
594       110000
595           50
596     14000000
597            0
598        50000
599        50000
600            0
601       110000
602        90000
603       110000
604     14000000
605     14000000
606     14000000
607        95000
608        90000
609      70000.0
610        70000
611       110000
612        95000
613      8090000
614            0
615       120000
616        90000
617        50000
618        65000
619        95000
620        65000
621        90000
622       110000
623        65000
624        90000
625        70000
626            0
627      70000.0
628        65000
629      95000.0
630     14000000
631       110000
632            0
633        70000
634        50000
635     14000000
636            0
637     14000000
638      95000.0
639       110000
640           50
641        90000
642       120000
643      8090000
644        50000
645       110000
646            0
647     14000000
648            0
649      70000.0
650        65000
651            0
652        95000
653        50000
654           50
655     14000000
656      8090000
657        70000
658     14000000
659       110000
660            0
661        50000
662       110000
663       110000
664        65000
665      95000.0
666     14000000
667      95000.0
668     14000000
669            0
670           50
671       120000
672       110000
673      70000.0
674            0
675            0
676           50
677        65000
678       120000
679      95000.0
680       110000
681        70000
682      8090000
683            0
684      8090000
685       120000
686      70000.0
687       110000
688            0
689       110000
690            0
691     14000000
692      70000.0
693            0
694      8090000
695     14000000
696       110000
697        50000
698        70000
699     14000000
700        70000
701      95000.0
702        65000
703            0
704        65000
705        95000
706      95000.0
707       110000
708        70000
709      8090000
710        65000
711      8090000
712            0
713        95000
714       110000
715           50
716        65000
717        50000
718        95000
719        65000
720            0
721       120000
722      95000.0
723            0
724      70000.0
725     14000000
726            0
727     14000000
728            0
729            0
730            0
731      8090000
732      95000.0
733            0
734            0
735        65000
736        95000
737            0
738        70000
739     14000000
740            0
741            0
742        95000
743        50000
744            0
745     14000000
746        65000
747     14000000
748           50
749       120000
750        65000
751        70000
752      70000.0
753            0
754        65000
755            0
756            0
757       110000
758      8090000
759        95000
760      95000.0
761            0
762        50000
763        65000
764      95000.0
765      8090000
766     14000000
767       110000
768            0
769        95000
770     14000000
771      8090000
772        90000
773           50
774       110000
775       120000
776        50000
777           50
778        70000
779        90000
780     14000000
781            0
782      8090000
783       120000
784      70000.0
785       120000
786        65000
787        50000
788        50000
789            0
790           50
791     14000000
792            0
793      95000.0
794           50
795      70000.0
796        95000
797       120000
798            0
799      8090000
800       110000
801       120000
802      95000.0
803           50
804            0
805            0
806            0
807        65000
808        95000
809           50
810        95000
811       120000
812            0
813            0
814            0
815       110000
816            0
817        90000
818       120000
819      70000.0
820            0
821       120000
822        70000
823        50000
824        70000
825        70000
826            0
827      8090000
828            0
829        50000
830            0
831        70000
832        70000
833      8090000
834     14000000
835      70000.0
836        65000
837            0
838      8090000
839     14000000
840      70000.0
841        65000
842        65000
843        65000
844       110000
845       120000
846        70000
847           50
848            0
849        65000
850            0
851       120000
852        65000
853        95000
854            0
855     14000000
856     14000000
857       120000
858           50
859           50
860            0
861        70000
862            0
863       110000
864      95000.0
865            0
866       120000
867        50000
868            0
869       120000
870        70000
871           50
872      95000.0
873     14000000
874      8090000
875      95000.0
876     14000000
877      8090000
878        70000
879        95000
880        70000
881        70000
882        95000
883            0
884      95000.0
885        70000
886            0
887            0
888        90000
889           50
890      70000.0
891        95000
892      95000.0
893            0
894     14000000
895        95000
896      8090000
897        95000
898      8090000
899            0
900        95000
901        70000
902       110000
903      70000.0
904        50000
905            0
906        90000
907        65000
908        50000
909            0
910        70000
911            0
912        95000
913       120000
914       120000
915        65000
916           50
917        90000
918            0
919        65000
920      8090000
921       120000
922        50000
923            0
924        90000
925            0
926        65000
927           50
928       110000
929            0
930       120000
931        50000
932        65000
933           50
934            0
935        70000
936      95000.0
937        65000
938        65000
939        90000
940           50
941        65000
942        70000
943            0
944            0
945            0
946        65000
947       120000
948      95000.0
949      8090000
950        90000
951        65000
952      95000.0
953      95000.0
954        50000
955      95000.0
956            0
957        50000
958     14000000
959        95000
960      95000.0
961        65000
962      8090000
963     14000000
964            0
965       110000
966       110000
967     14000000
968        65000
969           50
970            0
971        95000
972            0
973      70000.0
974       110000
975            0
976           50
977       110000
978     14000000
979        65000
980      8090000
981        65000
982        95000
983        65000
984            0
985            0
986            0
987      95000.0
988        95000
989            0
990        90000
991        90000
992       120000
993            0
994      70000.0
995       120000
996        70000
997            0
998            0
999      70000.0
1000     8090000
1001       65000
1002     95000.0
1003           0
1004       70000
1005       65000
1006      110000
1007          50
1008       65000
1009           0
1010          50
1011       70000
1012       90000
1013    14000000
1014           0
1015       50000
1016     8090000
1017      110000
1018      120000
1019     70000.0
1020       65000
1021       95000
1022      110000
1023     95000.0
1024       50000
1025           0
1026     70000.0
1027     70000.0
1028           0
1029      120000
1030     8090000
1031     95000.0
1032       95000
1033      110000
1034       50000
1035    14000000
1036      110000
1037      120000
1038      120000
1039           0
1040          50
1041           0
1042     95000.0
1043    14000000
1044     95000.0
1045     95000.0
1046      110000
1047     70000.0
1048       70000
1049           0
1050          50
1051       65000
1052     95000.0
1053     8090000
1054           0
1055       65000
1056      110000
1057      120000
1058     95000.0
1059      120000
1060    14000000
1061          50
1062     8090000
1063           0
1064     95000.0
1065       50000
1066       65000
1067      110000
1068       50000
1069           0
1070     70000.0
1071           0
1072       65000
1073       65000
1074    14000000
1075           0
1076       90000
1077       50000
1078       95000
1079    14000000
1080      120000
1081       50000
1082       95000
1083      110000
1084     70000.0
1085          50
1086           0
1087     95000.0
1088    14000000
1089     8090000
1090          50
1091       70000
1092       95000
1093      110000
1094     70000.0
1095      110000
1096     70000.0
1097       65000
1098       65000
1099       90000
1100       90000
1101    14000000
1102           0
1103     8090000
1104     8090000
1105    14000000
1106      110000
1107     95000.0
1108       65000
1109      110000
1110           0
1111      110000
1112       65000
1113     95000.0
1114           0
1115    14000000
1116      110000
1117           0
1118     8090000
1119       50000
1120       90000
1121       50000
1122      110000
1123     8090000
1124      120000
1125           0
1126       90000
1127           0
1128       70000
1129      120000
1130     70000.0
1131     95000.0
1132     70000.0
1133       70000
1134       95000
1135          50
1136       65000
1137       70000
1138          50
1139     95000.0
1140       65000
1141      120000
1142     70000.0
1143           0
1144     8090000
1145       65000
1146      110000
1147       65000
1148      110000
1149       95000
1150           0
1151          50
1152       90000
1153       95000
1154       70000
1155          50
1156       70000
1157       65000
1158      120000
1159      120000
1160       50000
1161     70000.0
1162       90000
1163     70000.0
1164       50000
1165       90000
1166       95000
1167          50
1168    14000000
1169     95000.0
1170       70000
1171       90000
1172     8090000
1173       50000
1174           0
1175       50000

In [ ]:
# Viewing the job title column
# Problem 2: There are special characters 'Data Analyst!!!' in the job title column that need to be removed.
bdata['job_title']

0                                                     Sr.
1                                            DATA ANALYST
2                                            Data Analyst
3                                  Marketing Data Analyst
4                                         Data Analyst II
5                                     Senior Data Analyst
6                                     Senior Data Analyst
7                                        Sr. Data Analyst
8                                  Marketing Data Analyst
9                                            DATA ANALYST
10                                   Product Data Analyst
11                                 Marketing Data Analyst
12                                             BI Analyst
13                                           DATA ANALYST
14                                  Data Analyst - Remote
15                                    Junior Data Analyst
16                                           Data Analyst
17                                           Data Analyst
18                                           DATA ANALYST
19                                    Senior Data Analyst
20                                    Senior Data Analyst
21                                             BI Analyst
22                                  Data Analyst - Remote
23                                           Data Analyst
24                                             BI Analyst
25                                    Senior Data Analyst
26                                 Marketing Data Analyst
27                                   Product Data Analyst
28                                 Marketing Data Analyst
29                                             BI Analyst
30                                    Junior Data Analyst
31                                    Senior Data Analyst
32                              Data Analytics Specialist
33                                  Data Analyst - Remote
34                                        Data Analyst II
35                                        Data Analyst!!!
36                                           Data Analyst
37                                        Data Analyst!!!
38                                        Data Analyst!!!
39                                       Sr. Data Analyst
40                                 Marketing Data Analyst
41                                    Junior Data Analyst
42                                       Jr. Data Analyst
43                                        Data Analyst II
44                                       Sr. Data Analyst
45                                    Senior Data Analyst
46                                        Data Analyst!!!
47                                       Jr. Data Analyst
48                                           DATA ANALYST
49                                           DATA ANALYST
50                                    Junior Data Analyst
51                                           DATA ANALYST
52                                       Jr. Data Analyst
53                                       Jr. Data Analyst
54                                  Data Analyst - Remote
55                                        Data Analyst II
56                                        Data Analyst!!!
57                                           Data Analyst
58                                 Marketing Data Analyst
59                              Data Analytics Specialist
60                                             BI Analyst
61                                           DATA ANALYST
62                                    Junior Data Analyst
63                                           DATA ANALYST
64                                             BI Analyst
65                                        Data Analyst II
66                                   Product Data Analyst
67                                  Data Analyst - Remote
68                                       Jr. Data Analyst
69                                  Data Analyst - Remote
70                                    Senior Data Analyst
71                                 Marketing Data Analyst
72                                           DATA ANALYST
73                                           Data Analyst
74                                   Product Data Analyst
75                                    Senior Data Analyst
76                                        Data Analyst!!!
77                                        Data Analyst II
78                                           DATA ANALYST
79                                    Senior Data Analyst
80                                           DATA ANALYST
81                                    Junior Data Analyst
82                                        Data Analyst II
83                              Data Analytics Specialist
84                                   Product Data Analyst
85                                       Jr. Data Analyst
86                                       Sr. Data Analyst
87                                       Jr. Data Analyst
88                                       Jr. Data Analyst
89                                    Senior Data Analyst
90                                   Product Data Analyst
91                                        Data Analyst II
92                                 Marketing Data Analyst
93                                   Product Data Analyst
94                                   Product Data Analyst
95                                           DATA ANALYST
96                                  Data Analyst - Remote
97                                   Product Data Analyst
98                                       Sr. Data Analyst
99                                             BI Analyst
100                                Marketing Data Analyst
101                                   Senior Data Analyst
102                                      Sr. Data Analyst
103                             Data Analytics Specialist
104                                   Junior Data Analyst
105                                       Data Analyst II
106                                  Product Data Analyst
107                                Marketing Data Analyst
108                                            BI Analyst
109                                   Senior Data Analyst
110                                  Product Data Analyst
111                                      Jr. Data Analyst
112                                       Data Analyst!!!
113                                       Data Analyst!!!
114                                          Data Analyst
115                                   Senior Data Analyst
116                                          Data Analyst
117                                       Data Analyst!!!
118                                      Jr. Data Analyst
119                                   Junior Data Analyst
120                                       Data Analyst II
121                                          DATA ANALYST
122                                   Senior Data Analyst
123                                 Data Analyst - Remote
124                                Marketing Data Analyst
125                                      Jr. Data Analyst
126                                   Senior Data Analyst
127                                  Product Data Analyst
128                             Data Analytics Specialist
129                                   Junior Data Analyst
130                                  Product Data Analyst
131                             Data Analytics Specialist
132                                      Sr. Data Analyst
133                                       Data Analyst II
134                                      Sr. Data Analyst
135                                   Senior Data Analyst
136                                Marketing Data Analyst
137                                            BI Analyst
138                                            BI Analyst
139                                       Data Analyst II
140                                Marketing Data Analyst
141                                 Data Analyst - Remote
142                                   Junior Data Analyst
143                                 Data Analyst - Remote
144                                   Junior Data Analyst
145                                      Jr. Data Analyst
146                                   Senior Data Analyst
147                                      Sr. Data Analyst
148                                            BI Analyst
149                             Data Analytics Specialist
150                                          DATA ANALYST
151                                       Data Analyst!!!
152                                          Data Analyst
153                                          DATA ANALYST
154                                      Sr. Data Analyst
155                                  Product Data Analyst
156                                      Sr. Data Analyst
157                                       Data Analyst!!!
158                                  Product Data Analyst
159                                   Junior Data Analyst
160                                 Data Analyst - Remote
161                                          DATA ANALYST
162                                   Junior Data Analyst
163                                   Junior Data Analyst
164                                 Data Analyst - Remote
165                             Data Analytics Specialist
166                                            BI Analyst
167                                       Data Analyst II
168                                            BI Analyst
169                                          Data Analyst
170                                  Product Data Analyst
171                                Marketing Data Analyst
172                                          DATA ANALYST
173                                  Product Data Analyst
174                                            BI Analyst
175                                       Data Analyst!!!
176                                       Data Analyst II
177                                       Data Analyst!!!
178                                  Product Data Analyst
179                                      Jr. Data Analyst
180                                          DATA ANALYST
181                                       Data Analyst II
182                                   Junior Data Analyst
183                                      Sr. Data Analyst
184                             Data Analytics Specialist
185                                          Data Analyst
186                                Marketing Data Analyst
187                                Marketing Data Analyst
188                                       Data Analyst II
189                                            BI Analyst
190                                       Data Analyst!!!
191                                      Sr. Data Analyst
192                                            BI Analyst
193                                          DATA ANALYST
194                                  Product Data Analyst
195                                       Data Analyst II
196                                  Product Data Analyst
197                                            BI Analyst
198                                 Data Analyst - Remote
199                                   Senior Data Analyst
200                                      Sr. Data Analyst
201                                      Jr. Data Analyst
202                                       Data Analyst!!!
203                                      Sr. Data Analyst
204                                            BI Analyst
205                                       Data Analyst!!!
206                                            BI Analyst
207                                          Data Analyst
208     ['New York, NY', 'San Francisco, CA', 'Dallas,...
209                                      Jr. Data Analyst
210                             Data Analytics Specialist
211                                          Data Analyst
212                                          DATA ANALYST
213                                      Jr. Data Analyst
214                                       Data Analyst!!!
215                                       Data Analyst II
216                                   Senior Data Analyst
217                                          Data Analyst
218                                   Senior Data Analyst
219                                 Data Analyst - Remote
220                                          DATA ANALYST
221                                          DATA ANALYST
222                                Marketing Data Analyst
223                             Data Analytics Specialist
224                                          DATA ANALYST
225                                       Data Analyst!!!
226                                            BI Analyst
227                                       Data Analyst!!!
228                                      Sr. Data Analyst
229                                      Sr. Data Analyst
230                                  Product Data Analyst
231                             Data Analytics Specialist
232                                            BI Analyst
233                                      Sr. Data Analyst
234                                       Data Analyst II
235                                            BI Analyst
236                                 Data Analyst - Remote
237                                   Junior Data Analyst
238                                   Senior Data Analyst
239                                            BI Analyst
240                                       Data Analyst!!!
241                                Marketing Data Analyst
242                                Marketing Data Analyst
243                                   Senior Data Analyst
244                                Marketing Data Analyst
245                                       Data Analyst II
246                                   Junior Data Analyst
247                                  Product Data Analyst
248                                  Product Data Analyst
249                                      Jr. Data Analyst
250                             Data Analytics Specialist
251                                            BI Analyst
252                             Data Analytics Specialist
253                                          DATA ANALYST
254                                   Senior Data Analyst
255                                   Senior Data Analyst
256                                          DATA ANALYST
257                                      Jr. Data Analyst
258                                          Data Analyst
259                                 Data Analyst - Remote
260                                            BI Analyst
261                                   Senior Data Analyst
262                                 Data Analyst - Remote
263                                   Senior Data Analyst
264                                          Data Analyst
265                                          DATA ANALYST
266                                Marketing Data Analyst
267                                  Product Data Analyst
268                                          Data Analyst
269                                   Senior Data Analyst
270                                          DATA ANALYST
271                                          Data Analyst
272                                      Jr. Data Analyst
273                                          DATA ANALYST
274                                            BI Analyst
275                                   Senior Data Analyst
276                                       Data Analyst II
277                                  Product Data Analyst
278                             Data Analytics Specialist
279                                   Senior Data Analyst
280                                            BI Analyst
281                                      Sr. Data Analyst
282                                Marketing Data Analyst
283                                 Data Analyst - Remote
284                                 Data Analyst - Remote
285                             Data Analytics Specialist
286                                   Senior Data Analyst
287                                       Data Analyst!!!
288                             Data Analytics Specialist
289                                       Data Analyst!!!
290                                   Junior Data Analyst
291                                   Senior Data Analyst
292                                          DATA ANALYST
293                                          DATA ANALYST
294                                  Product Data Analyst
295                                   Junior Data Analyst
296                                      Jr. Data Analyst
297                                   Junior Data Analyst
298                                   Junior Data Analyst
299                             Data Analytics Specialist
300                                Marketing Data Analyst
301                                          Data Analyst
302                                  Product Data Analyst
303                                  Product Data Analyst
304                                  Product Data Analyst
305                                          DATA ANALYST
306                                          Data Analyst
307                                   Junior Data Analyst
308                                Marketing Data Analyst
309                                      Jr. Data Analyst
310                                       Data Analyst!!!
311                                          DATA ANALYST
312                                   Senior Data Analyst
313                                   Senior Data Analyst
314                                   Senior Data Analyst
315                                            BI Analyst
316                             Data Analytics Specialist
317                                      Sr. Data Analyst
318                                   Junior Data Analyst
319                                      Sr. Data Analyst
320                                       Data Analyst II
321                             Data Analytics Specialist
322                                   Senior Data Analyst
323                                          DATA ANALYST
324                             Data Analytics Specialist
325                                       Data Analyst!!!
326                                            BI Analyst
327                                          DATA ANALYST
328                                          Data Analyst
329                                  Product Data Analyst
330                                            BI Analyst
331                                          Data Analyst
332                                          DATA ANALYST
333                                       Data Analyst!!!
334                                   Senior Data Analyst
335                                      Sr. Data Analyst
336                                   Junior Data Analyst
337                             Data Analytics Specialist
338                             Data Analytics Specialist
339                                   Senior Data Analyst
340                                   Junior Data Analyst
341                                          Data Analyst
342                                      Sr. Data Analyst
343                                   Junior Data Analyst

# Data Imputation

### Problem 1: Fixing Salary Column

1. Handling Industry Benchmarks - In order to find fix the Salary column we need to determine what to replace it with, so we need a range to determine the lowest to the highest.
For this we will be doing this for U.S location, so from the west coast to the east coast and everywhere in between.

    According to ▶ [Source](https://www.payscale.com/research/US/Job=Junior_Data_Analyst/Salary/c4d249b7/Entry-Level)
    

    For a Junior Data Analyst

    Low End `$42,000` to High End `$90,000`

    Using ```(a + b) / 2```
    Taking the Low End salary and the High End and using formula, we will get the Mean, which gives us `$66,000`


**Analytical Note:** While a nationwide mean of **\$66,000** serves as a reliable baseline for general U.S. distribution, this approach assumes a uniform geographic distribution. It does not account for localized variance (such as higher market premiums on the West Coast versus regional adjustments in the Midwest).

I have a dataset in this dataset (for right now) is 4 column, in order viewing the dataset is : job_title, salary, location, company_size. In the job_title column is a different position of data analyst,  in the salary column is the salary for the data analyst, in location column is U.S based location in the U.S formated like  Denver, CO, New York, NY and so on, in the last column is company_size with a value between 0 and 4, Unknown = 0, Startup = 1, Medium = 2, Large = 3, Huge = 4.

 I am trying to get the most accurey salary for the data analyst, Brainstorm ideas on what formula (excel formula work too, if you happen to find one) .
Salary = US location + Data Analyst position + Company Size

In [ ]:
# Review the salary column
bdata['salary']

0              0
1          65000
2          65000
3              0
4          65000
5              0
6          95000
7          65000
8         120000
9        95000.0
10        110000
11             0
12         70000
13             0
14        110000
15             0
16            50
17        110000
18             0
19             0
20         70000
21         70000
22            50
23         50000
24        120000
25         65000
26       95000.0
27         50000
28         95000
29       70000.0
30            50
31            50
32             0
33       95000.0
34        110000
35        110000
36             0
37      14000000
38         95000
39       8090000
40       8090000
41        110000
42       95000.0
43             0
44        110000
45             0
46             0
47            50
48       95000.0
49         70000
50       95000.0
51       8090000
52         90000
53        120000
54       95000.0
55             0
56         70000
57         70000
58             0
59         50000
60            50
61             0
62        110000
63         65000
64         65000
65         65000
66       95000.0
67             0
68        110000
69         70000
70       95000.0
71         70000
72             0
73         90000
74       70000.0
75        110000
76         90000
77         65000
78         65000
79       8090000
80       70000.0
81         95000
82             0
83             0
84         95000
85         50000
86      14000000
87             0
88             0
89        110000
90         90000
91         70000
92             0
93       8090000
94         95000
95             0
96         65000
97             0
98       95000.0
99             0
100            0
101           50
102     14000000
103      95000.0
104           50
105       120000
106            0
107        50000
108            0
109       120000
110        65000
111            0
112        50000
113      95000.0
114       120000
115        90000
116            0
117     14000000
118      8090000
119        50000
120        70000
121            0
122            0
123        65000
124        70000
125        95000
126            0
127        95000
128            0
129        95000
130      70000.0
131       110000
132     14000000
133            0
134        50000
135        65000
136           50
137        90000
138        90000
139            0
140        95000
141        95000
142            0
143      70000.0
144       120000
145      8090000
146      95000.0
147        65000
148           50
149     14000000
150           50
151        90000
152     14000000
153        90000
154        65000
155           50
156            0
157       110000
158     14000000
159            0
160        65000
161       120000
162      95000.0
163       120000
164     14000000
165           50
166            0
167           50
168      95000.0
169        65000
170     14000000
171        90000
172        90000
173        90000
174      95000.0
175            0
176        95000
177            0
178      95000.0
179      95000.0
180            0
181            0
182        70000
183     14000000
184            0
185            0
186        95000
187            0
188        95000
189      70000.0
190           50
191            0
192       120000
193      8090000
194            0
195      70000.0
196        95000
197        65000
198        50000
199        90000
200        95000
201        70000
202     14000000
203      95000.0
204        50000
205        90000
206       120000
207        65000
208            0
209            0
210            0
211      8090000
212      95000.0
213      8090000
214        65000
215      8090000
216        95000
217        90000
218      95000.0
219        65000
220            0
221        95000
222     14000000
223            0
224        70000
225            0
226            0
227           50
228        65000
229        95000
230        65000
231        50000
232        65000
233            0
234        50000
235            0
236            0
237        65000
238        95000
239            0
240        95000
241           50
242        65000
243            0
244       120000
245     14000000
246     14000000
247           50
248      95000.0
249            0
250        90000
251            0
252       110000
253           50
254            0
255        65000
256        95000
257        65000
258        65000
259        65000
260        65000
261      95000.0
262       120000
263        50000
264        50000
265        90000
266        50000
267        50000
268        90000
269       120000
270      8090000
271            0
272        95000
273       120000
274      95000.0
275      70000.0
276        70000
277      8090000
278        95000
279        95000
280        65000
281            0
282            0
283            0
284        90000
285       110000
286        50000
287        90000
288        70000
289      8090000
290        70000
291        90000
292     14000000
293        95000
294        70000
295            0
296        90000
297      70000.0
298            0
299       120000
300            0
301            0
302            0
303        95000
304      95000.0
305            0
306        65000
307        65000
308       120000
309            0
310        70000
311            0
312        65000
313        70000
314      70000.0
315            0
316            0
317        65000
318        70000
319     14000000
320      8090000
321            0
322       110000
323     14000000
324       120000
325        70000
326      95000.0
327        95000
328            0
329        50000
330      70000.0
331        65000
332     14000000
333        50000
334            0
335        65000
336            0
337            0
338      70000.0
339        65000
340           50
341        50000
342        90000
343       120000
344            0
345            0
346        70000
347     14000000
348            0
349       120000
350            0
351           50
352        50000
353        50000
354      95000.0
355        95000
356      95000.0
357            0
358           50
359      8090000
360        95000
361        65000
362        50000
363       110000
364            0
365           50
366       110000
367       120000
368        90000
369        65000
370      95000.0
371        70000
372            0
373            0
374       120000
375        65000
376        95000
377       110000
378            0
379        90000
380            0
381      95000.0
382      8090000
383            0
384        90000
385            0
386            0
387      70000.0
388     14000000
389        65000
390      70000.0
391        65000
392       110000
393        90000
394      8090000
395           50
396       110000
397        90000
398       110000
399        95000
400        90000
401            0
402      8090000
403        70000
404      95000.0
405      8090000
406           50
407     14000000
408            0
409     14000000
410     14000000
411       110000
412      95000.0
413           50
414       120000
415        70000
416     14000000
417      95000.0
418        50000
419      70000.0
420      70000.0
421            0
422            0
423      8090000
424     14000000
425        50000
426        50000
427            0
428           50
429      95000.0
430        65000
431        65000
432       120000
433        90000
434      8090000
435      70000.0
436        50000
437        65000
438       110000
439       120000
440        90000
441            0
442        90000
443        50000
444        90000
445     14000000
446            0
447        50000
448        65000
449        90000
450      95000.0
451            0
452        50000
453            0
454            0
455        50000
456            0
457      95000.0
458        50000
459      8090000
460            0
461        65000
462        90000
463        70000
464      8090000
465        95000
466        90000
467           50
468     14000000
469            0
470      8090000
471      8090000
472      95000.0
473            0
474     14000000
475        70000
476        95000
477        50000
478        50000
479            0
480            0
481            0
482        90000
483      8090000
484      8090000
485      95000.0
486     14000000
487        50000
488        65000
489        65000
490            0
491       110000
492            0
493           50
494       110000
495        65000
496        90000
497        65000
498     14000000
499        90000
500       110000
501        65000
502        65000
503        95000
504        65000
505            0
506            0
507      70000.0
508        65000
509        65000
510       120000
511        95000
512        50000
513        65000
514     14000000
515        50000
516            0
517            0
518     14000000
519            0
520           50
521            0
522        65000
523           50
524        95000
525            0
526       120000
527        95000
528            0
529        65000
530           50
531            0
532      8090000
533        90000
534        50000
535      95000.0
536      70000.0
537        65000
538      8090000
539            0
540      95000.0
541        65000
542            0
543        50000
544     14000000
545        50000
546        95000
547            0
548        65000
549        95000
550        95000
551            0
552        70000
553           50
554        70000
555      95000.0
556        95000
557        70000
558        90000
559        90000
560       110000
561        90000
562      70000.0
563      8090000
564      95000.0
565        50000
566       110000
567      95000.0
568      70000.0
569        65000
570            0
571           50
572        90000
573        95000
574        95000
575      70000.0
576      70000.0
577      8090000
578      70000.0
579      70000.0
580        65000
581            0
582      70000.0
583      8090000
584        70000
585       120000
586       120000
587      95000.0
588            0
589            0
590        65000
591           50
592        65000
593     14000000
594       110000
595           50
596     14000000
597            0
598        50000
599        50000
600            0
601       110000
602        90000
603       110000
604     14000000
605     14000000
606     14000000
607        95000
608        90000
609      70000.0
610        70000
611       110000
612        95000
613      8090000
614            0
615       120000
616        90000
617        50000
618        65000
619        95000
620        65000
621        90000
622       110000
623        65000
624        90000
625        70000
626            0
627      70000.0
628        65000
629      95000.0
630     14000000
631       110000
632            0
633        70000
634        50000
635     14000000
636            0
637     14000000
638      95000.0
639       110000
640           50
641        90000
642       120000
643      8090000
644        50000
645       110000
646            0
647     14000000
648            0
649      70000.0
650        65000
651            0
652        95000
653        50000
654           50
655     14000000
656      8090000
657        70000
658     14000000
659       110000
660            0
661        50000
662       110000
663       110000
664        65000
665      95000.0
666     14000000
667      95000.0
668     14000000
669            0
670           50
671       120000
672       110000
673      70000.0
674            0
675            0
676           50
677        65000
678       120000
679      95000.0
680       110000
681        70000
682      8090000
683            0
684      8090000
685       120000
686      70000.0
687       110000
688            0
689       110000
690            0
691     14000000
692      70000.0
693            0
694      8090000
695     14000000
696       110000
697        50000
698        70000
699     14000000
700        70000
701      95000.0
702        65000
703            0
704        65000
705        95000
706      95000.0
707       110000
708        70000
709      8090000
710        65000
711      8090000
712            0
713        95000
714       110000
715           50
716        65000
717        50000
718        95000
719        65000
720            0
721       120000
722      95000.0
723            0
724      70000.0
725     14000000
726            0
727     14000000
728            0
729            0
730            0
731      8090000
732      95000.0
733            0
734            0
735        65000
736        95000
737            0
738        70000
739     14000000
740            0
741            0
742        95000
743        50000
744            0
745     14000000
746        65000
747     14000000
748           50
749       120000
750        65000
751        70000
752      70000.0
753            0
754        65000
755            0
756            0
757       110000
758      8090000
759        95000
760      95000.0
761            0
762        50000
763        65000
764      95000.0
765      8090000
766     14000000
767       110000
768            0
769        95000
770     14000000
771      8090000
772        90000
773           50
774       110000
775       120000
776        50000
777           50
778        70000
779        90000
780     14000000
781            0
782      8090000
783       120000
784      70000.0
785       120000
786        65000
787        50000
788        50000
789            0
790           50
791     14000000
792            0
793      95000.0
794           50
795      70000.0
796        95000
797       120000
798            0
799      8090000
800       110000
801       120000
802      95000.0
803           50
804            0
805            0
806            0
807        65000
808        95000
809           50
810        95000
811       120000
812            0
813            0
814            0
815       110000
816            0
817        90000
818       120000
819      70000.0
820            0
821       120000
822        70000
823        50000
824        70000
825        70000
826            0
827      8090000
828            0
829        50000
830            0
831        70000
832        70000
833      8090000
834     14000000
835      70000.0
836        65000
837            0
838      8090000
839     14000000
840      70000.0
841        65000
842        65000
843        65000
844       110000
845       120000
846        70000
847           50
848            0
849        65000
850            0
851       120000
852        65000
853        95000
854            0
855     14000000
856     14000000
857       120000
858           50
859           50
860            0
861        70000
862            0
863       110000
864      95000.0
865            0
866       120000
867        50000
868            0
869       120000
870        70000
871           50
872      95000.0
873     14000000
874      8090000
875      95000.0
876     14000000
877      8090000
878        70000
879        95000
880        70000
881        70000
882        95000
883            0
884      95000.0
885        70000
886            0
887            0
888        90000
889           50
890      70000.0
891        95000
892      95000.0
893            0
894     14000000
895        95000
896      8090000
897        95000
898      8090000
899            0
900        95000
901        70000
902       110000
903      70000.0
904        50000
905            0
906        90000
907        65000
908        50000
909            0
910        70000
911            0
912        95000
913       120000
914       120000
915        65000
916           50
917        90000
918            0
919        65000
920      8090000
921       120000
922        50000
923            0
924        90000
925            0
926        65000
927           50
928       110000
929            0
930       120000
931        50000
932        65000
933           50
934            0
935        70000
936      95000.0
937        65000
938        65000
939        90000
940           50
941        65000
942        70000
943            0
944            0
945            0
946        65000
947       120000
948      95000.0
949      8090000
950        90000
951        65000
952      95000.0
953      95000.0
954        50000
955      95000.0
956            0
957        50000
958     14000000
959        95000
960      95000.0
961        65000
962      8090000
963     14000000
964            0
965       110000
966       110000
967     14000000
968        65000
969           50
970            0
971        95000
972            0
973      70000.0
974       110000
975            0
976           50
977       110000
978     14000000
979        65000
980      8090000
981        65000
982        95000
983        65000
984            0
985            0
986            0
987      95000.0
988        95000
989            0
990        90000
991        90000
992       120000
993            0
994      70000.0
995       120000
996        70000
997            0
998            0
999      70000.0
1000     8090000
1001       65000
1002     95000.0
1003           0
1004       70000
1005       65000
1006      110000
1007          50
1008       65000
1009           0
1010          50
1011       70000
1012       90000
1013    14000000
1014           0
1015       50000
1016     8090000
1017      110000
1018      120000
1019     70000.0
1020       65000
1021       95000
1022      110000
1023     95000.0
1024       50000
1025           0
1026     70000.0
1027     70000.0
1028           0
1029      120000
1030     8090000
1031     95000.0
1032       95000
1033      110000
1034       50000
1035    14000000
1036      110000
1037      120000
1038      120000
1039           0
1040          50
1041           0
1042     95000.0
1043    14000000
1044     95000.0
1045     95000.0
1046      110000
1047     70000.0
1048       70000
1049           0
1050          50
1051       65000
1052     95000.0
1053     8090000
1054           0
1055       65000
1056      110000
1057      120000
1058     95000.0
1059      120000
1060    14000000
1061          50
1062     8090000
1063           0
1064     95000.0
1065       50000
1066       65000
1067      110000
1068       50000
1069           0
1070     70000.0
1071           0
1072       65000
1073       65000
1074    14000000
1075           0
1076       90000
1077       50000
1078       95000
1079    14000000
1080      120000
1081       50000
1082       95000
1083      110000
1084     70000.0
1085          50
1086           0
1087     95000.0
1088    14000000
1089     8090000
1090          50
1091       70000
1092       95000
1093      110000
1094     70000.0
1095      110000
1096     70000.0
1097       65000
1098       65000
1099       90000
1100       90000
1101    14000000
1102           0
1103     8090000
1104     8090000
1105    14000000
1106      110000
1107     95000.0
1108       65000
1109      110000
1110           0
1111      110000
1112       65000
1113     95000.0
1114           0
1115    14000000
1116      110000
1117           0
1118     8090000
1119       50000
1120       90000
1121       50000
1122      110000
1123     8090000
1124      120000
1125           0
1126       90000
1127           0
1128       70000
1129      120000
1130     70000.0
1131     95000.0
1132     70000.0
1133       70000
1134       95000
1135          50
1136       65000
1137       70000
1138          50
1139     95000.0
1140       65000
1141      120000
1142     70000.0
1143           0
1144     8090000
1145       65000
1146      110000
1147       65000
1148      110000
1149       95000
1150           0
1151          50
1152       90000
1153       95000
1154       70000
1155          50
1156       70000
1157       65000
1158      120000
1159      120000
1160       50000
1161     70000.0
1162       90000
1163     70000.0
1164       50000
1165       90000
1166       95000
1167          50
1168    14000000
1169     95000.0
1170       70000
1171       90000
1172     8090000
1173       50000
1174           0
1175       50000

In [ ]:
"""
Fix the Salary Column by removing the rows that have $0 and $50
"""
def zero_salary():
  # check value from the salary column if the space has 0 or 50 in


  # if it does, replace the 0 with something else either $65,000 or $72,000 as the default pay
 pass

In [ ]:
bdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   job_title               2499 non-null   object
 1   salary                  2500 non-null   object
 2   location                2500 non-null   object
 3   remote_location         2500 non-null   object
 4   company_size            2499 non-null   object
 5   experience_level        2500 non-null   object
 6   employment_type         2479 non-null   object
 7   skills                  2387 non-null   object
 8   experience_level_value  2500 non-null   int64
 9   company_size_value      2500 non-null   int64
 10  employment_type_value   2500 non-null   int64
dtypes: int64(3), object(8)
memory usage: 215.0+ KB

In [ ]:
bdata.head(25)

,job_title,salary,location,remote_location,company_size,experience_level,employment_type,skills,experience_level_value,company_size_value,employment_type_value
0,Sr.Data Analyst,0,"Las Vegas, NV",C2C,Large,None,None,False,0,3,0
1,Data Analyst,65000,"Atlanta, GA",No,Huge,Sr,Freelance,"AWS, Python, Google Cloud, Power BI",3,4,6
2,Data Analyst,65000,"Santa Fe, NW",1,Large,Pr,Contract,"Python, , Excel",4,3,4
3,Marketing Data Analyst,0,"Orlando, FL",Yes,Unknown,None,Regular,"Tableau , Azure , R , Python ,",0,0,3
4,None,65000,"Columbus, OH",Hybrid,Unknown,Jr,Part-time,"Python , Tableau , Azure , Google Cloud , SQL",1,0,2
5,Senior Data Analyst,0,"Oklahoma, OK",Partial,Startup,Mi,Part-time,"Excel, R",2,1,2
6,Senior Data Analyst,95000,"Phoenix, AZ",False,Startup,Pr,Full-time,"Python, AWS",4,1,1
7,Sr. Data Analyst,65000,"Atlanta, GA",1,Medium,Jr,Regular,"Tableau, Power BI, Python, , AWS",1,2,3
8,Marketing Data Analyst,120000,"Las Vegas, NV",0,Large,Mi,Full-time,"Google Cloud, Azure, Excel, Python, SQL",2,3,1
9,Data Analyst,95000.0,"Fort Collins, CO",False,Unknown,Mi,Temporary,", Azure, Excel, SQL, R",2,0,5

In [ ]:
# We nee to find all the values in the location column
bdata['location']

0                                                    120k
1       'New York, NY', 'San Francisco, CA', 'Dallas, ...
2       'New York, NY', 'San Francisco, CA', 'Dallas, ...
3       'New York, NY', 'San Francisco, CA', 'Dallas, ...
4       'New York, NY', 'San Francisco, CA', 'Dallas, ...
5       'New York, NY', 'San Francisco, CA', 'Dallas, ...
6       'New York, NY', 'San Francisco, CA', 'Dallas, ...
7       'New York, NY', 'San Francisco, CA', 'Dallas, ...
8       'New York, NY', 'San Francisco, CA', 'Dallas, ...
9       'New York, NY', 'San Francisco, CA', 'Dallas, ...
10      'New York, NY', 'San Francisco, CA', 'Dallas, ...
11      'New York, NY', 'San Francisco, CA', 'Dallas, ...
12      'New York, NY', 'San Francisco, CA', 'Dallas, ...
13      'New York, NY', 'San Francisco, CA', 'Dallas, ...
14      'New York, NY', 'San Francisco, CA', 'Dallas, ...
15      'New York, NY', 'San Francisco, CA', 'Dallas, ...
16      'New York, NY', 'San Francisco, CA', 'Dallas, ...
17      'New York, NY', 'San Francisco, CA', 'Dallas, ...
18      'New York, NY', 'San Francisco, CA', 'Dallas, ...
19      'New York, NY', 'San Francisco, CA', 'Dallas, ...
20      'New York, NY', 'San Francisco, CA', 'Dallas, ...
21      'New York, NY', 'San Francisco, CA', 'Dallas, ...
22      'New York, NY', 'San Francisco, CA', 'Dallas, ...
23      'New York, NY', 'San Francisco, CA', 'Dallas, ...
24      'New York, NY', 'San Francisco, CA', 'Dallas, ...
25      'New York, NY', 'San Francisco, CA', 'Dallas, ...
26      'New York, NY', 'San Francisco, CA', 'Dallas, ...
27      'New York, NY', 'San Francisco, CA', 'Dallas, ...
28      'New York, NY', 'San Francisco, CA', 'Dallas, ...
29      'New York, NY', 'San Francisco, CA', 'Dallas, ...
30      'New York, NY', 'San Francisco, CA', 'Dallas, ...
31      'New York, NY', 'San Francisco, CA', 'Dallas, ...
32      'New York, NY', 'San Francisco, CA', 'Dallas, ...
33      'New York, NY', 'San Francisco, CA', 'Dallas, ...
34      'New York, NY', 'San Francisco, CA', 'Dallas, ...
35      'New York, NY', 'San Francisco, CA', 'Dallas, ...
36      'New York, NY', 'San Francisco, CA', 'Dallas, ...
37      'New York, NY', 'San Francisco, CA', 'Dallas, ...
38      'New York, NY', 'San Francisco, CA', 'Dallas, ...
39      'New York, NY', 'San Francisco, CA', 'Dallas, ...
40      'New York, NY', 'San Francisco, CA', 'Dallas, ...
41      'New York, NY', 'San Francisco, CA', 'Dallas, ...
42      'New York, NY', 'San Francisco, CA', 'Dallas, ...
43      'New York, NY', 'San Francisco, CA', 'Dallas, ...
44      'New York, NY', 'San Francisco, CA', 'Dallas, ...
45      'New York, NY', 'San Francisco, CA', 'Dallas, ...
46      'New York, NY', 'San Francisco, CA', 'Dallas, ...
47      'New York, NY', 'San Francisco, CA', 'Dallas, ...
48      'New York, NY', 'San Francisco, CA', 'Dallas, ...
49      'New York, NY', 'San Francisco, CA', 'Dallas, ...
50      'New York, NY', 'San Francisco, CA', 'Dallas, ...
51      'New York, NY', 'San Francisco, CA', 'Dallas, ...
52      'New York, NY', 'San Francisco, CA', 'Dallas, ...
53      'New York, NY', 'San Francisco, CA', 'Dallas, ...
54      'New York, NY', 'San Francisco, CA', 'Dallas, ...
55      'New York, NY', 'San Francisco, CA', 'Dallas, ...
56      'New York, NY', 'San Francisco, CA', 'Dallas, ...
57      'New York, NY', 'San Francisco, CA', 'Dallas, ...
58      'New York, NY', 'San Francisco, CA', 'Dallas, ...
59      'New York, NY', 'San Francisco, CA', 'Dallas, ...
60      'New York, NY', 'San Francisco, CA', 'Dallas, ...
61      'New York, NY', 'San Francisco, CA', 'Dallas, ...
62      'New York, NY', 'San Francisco, CA', 'Dallas, ...
63      'New York, NY', 'San Francisco, CA', 'Dallas, ...
64      'New York, NY', 'San Francisco, CA', 'Dallas, ...
65      'New York, NY', 'San Francisco, CA', 'Dallas, ...
66      'New York, NY', 'San Francisco, CA', 'Dallas, ...
67      'New York, NY', 'San Francisco, CA', 'Dallas, ...
68      'New York, NY', 'San Francisco, CA', 'Dallas, ...
69      'New York, NY', 'San Francisco, CA', 'Dallas, ...
70      'New York, NY', 'San Francisco, CA', 'Dallas, ...
71      'New York, NY', 'San Francisco, CA', 'Dallas, ...
72      'New York, NY', 'San Francisco, CA', 'Dallas, ...
73      'New York, NY', 'San Francisco, CA', 'Dallas, ...
74      'New York, NY', 'San Francisco, CA', 'Dallas, ...
75      'New York, NY', 'San Francisco, CA', 'Dallas, ...
76      'New York, NY', 'San Francisco, CA', 'Dallas, ...
77      'New York, NY', 'San Francisco, CA', 'Dallas, ...
78      'New York, NY', 'San Francisco, CA', 'Dallas, ...
79      'New York, NY', 'San Francisco, CA', 'Dallas, ...
80      'New York, NY', 'San Francisco, CA', 'Dallas, ...
81      'New York, NY', 'San Francisco, CA', 'Dallas, ...
82      'New York, NY', 'San Francisco, CA', 'Dallas, ...
83      'New York, NY', 'San Francisco, CA', 'Dallas, ...
84      'New York, NY', 'San Francisco, CA', 'Dallas, ...
85      'New York, NY', 'San Francisco, CA', 'Dallas, ...
86      'New York, NY', 'San Francisco, CA', 'Dallas, ...
87      'New York, NY', 'San Francisco, CA', 'Dallas, ...
88      'New York, NY', 'San Francisco, CA', 'Dallas, ...
89      'New York, NY', 'San Francisco, CA', 'Dallas, ...
90      'New York, NY', 'San Francisco, CA', 'Dallas, ...
91      'New York, NY', 'San Francisco, CA', 'Dallas, ...
92      'New York, NY', 'San Francisco, CA', 'Dallas, ...
93      'New York, NY', 'San Francisco, CA', 'Dallas, ...
94      'New York, NY', 'San Francisco, CA', 'Dallas, ...
95      'New York, NY', 'San Francisco, CA', 'Dallas, ...
96      'New York, NY', 'San Francisco, CA', 'Dallas, ...
97      'New York, NY', 'San Francisco, CA', 'Dallas, ...
98      'New York, NY', 'San Francisco, CA', 'Dallas, ...
99      'New York, NY', 'San Francisco, CA', 'Dallas, ...
100     'New York, NY', 'San Francisco, CA', 'Dallas, ...
101     'New York, NY', 'San Francisco, CA', 'Dallas, ...
102     'New York, NY', 'San Francisco, CA', 'Dallas, ...
103     'New York, NY', 'San Francisco, CA', 'Dallas, ...
104     'New York, NY', 'San Francisco, CA', 'Dallas, ...
105     'New York, NY', 'San Francisco, CA', 'Dallas, ...
106     'New York, NY', 'San Francisco, CA', 'Dallas, ...
107     'New York, NY', 'San Francisco, CA', 'Dallas, ...
108     'New York, NY', 'San Francisco, CA', 'Dallas, ...
109     'New York, NY', 'San Francisco, CA', 'Dallas, ...
110     'New York, NY', 'San Francisco, CA', 'Dallas, ...
111     'New York, NY', 'San Francisco, CA', 'Dallas, ...
112     'New York, NY', 'San Francisco, CA', 'Dallas, ...
113     'New York, NY', 'San Francisco, CA', 'Dallas, ...
114     'New York, NY', 'San Francisco, CA', 'Dallas, ...
115     'New York, NY', 'San Francisco, CA', 'Dallas, ...
116     'New York, NY', 'San Francisco, CA', 'Dallas, ...
117     'New York, NY', 'San Francisco, CA', 'Dallas, ...
118     'New York, NY', 'San Francisco, CA', 'Dallas, ...
119     'New York, NY', 'San Francisco, CA', 'Dallas, ...
120     'New York, NY', 'San Francisco, CA', 'Dallas, ...
121     'New York, NY', 'San Francisco, CA', 'Dallas, ...
122     'New York, NY', 'San Francisco, CA', 'Dallas, ...
123     'New York, NY', 'San Francisco, CA', 'Dallas, ...
124     'New York, NY', 'San Francisco, CA', 'Dallas, ...
125     'New York, NY', 'San Francisco, CA', 'Dallas, ...
126     'New York, NY', 'San Francisco, CA', 'Dallas, ...
127     'New York, NY', 'San Francisco, CA', 'Dallas, ...
128     'New York, NY', 'San Francisco, CA', 'Dallas, ...
129     'New York, NY', 'San Francisco, CA', 'Dallas, ...
130     'New York, NY', 'San Francisco, CA', 'Dallas, ...
131     'New York, NY', 'San Francisco, CA', 'Dallas, ...
132     'New York, NY', 'San Francisco, CA', 'Dallas, ...
133     'New York, NY', 'San Francisco, CA', 'Dallas, ...
134     'New York, NY', 'San Francisco, CA', 'Dallas, ...
135     'New York, NY', 'San Francisco, CA', 'Dallas, ...
136     'New York, NY', 'San Francisco, CA', 'Dallas, ...
137     'New York, NY', 'San Francisco, CA', 'Dallas, ...
138     'New York, NY', 'San Francisco, CA', 'Dallas, ...
139     'New York, NY', 'San Francisco, CA', 'Dallas, ...
140     'New York, NY', 'San Francisco, CA', 'Dallas, ...
141     'New York, NY', 'San Francisco, CA', 'Dallas, ...
142     'New York, NY', 'San Francisco, CA', 'Dallas, ...
143     'New York, NY', 'San Francisco, CA', 'Dallas, ...
144     'New York, NY', 'San Francisco, CA', 'Dallas, ...
145     'New York, NY', 'San Francisco, CA', 'Dallas, ...
146     'New York, NY', 'San Francisco, CA', 'Dallas, ...
147     'New York, NY', 'San Francisco, CA', 'Dallas, ...
148     'New York, NY', 'San Francisco, CA', 'Dallas, ...
149     'New York, NY', 'San Francisco, CA', 'Dallas, ...
150     'New York, NY', 'San Francisco, CA', 'Dallas, ...
151     'New York, NY', 'San Francisco, CA', 'Dallas, ...
152     'New York, NY', 'San Francisco, CA', 'Dallas, ...
153     'New York, NY', 'San Francisco, CA', 'Dallas, ...
154     'New York, NY', 'San Francisco, CA', 'Dallas, ...
155     'New York, NY', 'San Francisco, CA', 'Dallas, ...
156     'New York, NY', 'San Francisco, CA', 'Dallas, ...
157     'New York, NY', 'San Francisco, CA', 'Dallas, ...
158     'New York, NY', 'San Francisco, CA', 'Dallas, ...
159     'New York, NY', 'San Francisco, CA', 'Dallas, ...
160     'New York, NY', 'San Francisco, CA', 'Dallas, ...
161     'New York, NY', 'San Francisco, CA', 'Dallas, ...
162     'New York, NY', 'San Francisco, CA', 'Dallas, ...
163     'New York, NY', 'San Francisco, CA', 'Dallas, ...
164     'New York, NY', 'San Francisco, CA', 'Dallas, ...
165     'New York, NY', 'San Francisco, CA', 'Dallas, ...
166     'New York, NY', 'San Francisco, CA', 'Dallas, ...
167     'New York, NY', 'San Francisco, CA', 'Dallas, ...
168     'New York, NY', 'San Francisco, CA', 'Dallas, ...
169     'New York, NY', 'San Francisco, CA', 'Dallas, ...
170     'New York, NY', 'San Francisco, CA', 'Dallas, ...
171     'New York, NY', 'San Francisco, CA', 'Dallas, ...
172     'New York, NY', 'San Francisco, CA', 'Dallas, ...
173     'New York, NY', 'San Francisco, CA', 'Dallas, ...
174     'New York, NY', 'San Francisco, CA', 'Dallas, ...
175     'New York, NY', 'San Francisco, CA', 'Dallas, ...
176     'New York, NY', 'San Francisco, CA', 'Dallas, ...
177     'New York, NY', 'San Francisco, CA', 'Dallas, ...
178     'New York, NY', 'San Francisco, CA', 'Dallas, ...
179     'New York, NY', 'San Francisco, CA', 'Dallas, ...
180     'New York, NY', 'San Francisco, CA', 'Dallas, ...
181     'New York, NY', 'San Francisco, CA', 'Dallas, ...
182     'New York, NY', 'San Francisco, CA', 'Dallas, ...
183     'New York, NY', 'San Francisco, CA', 'Dallas, ...
184     'New York, NY', 'San Francisco, CA', 'Dallas, ...
185     'New York, NY', 'San Francisco, CA', 'Dallas, ...
186     'New York, NY', 'San Francisco, CA', 'Dallas, ...
187     'New York, NY', 'San Francisco, CA', 'Dallas, ...
188     'New York, NY', 'San Francisco, CA', 'Dallas, ...
189     'New York, NY', 'San Francisco, CA', 'Dallas, ...
190     'New York, NY', 'San Francisco, CA', 'Dallas, ...
191     'New York, NY', 'San Francisco, CA', 'Dallas, ...
192     'New York, NY', 'San Francisco, CA', 'Dallas, ...
193     'New York, NY', 'San Francisco, CA', 'Dallas, ...
194     'New York, NY', 'San Francisco, CA', 'Dallas, ...
195     'New York, NY', 'San Francisco, CA', 'Dallas, ...
196     'New York, NY', 'San Francisco, CA', 'Dallas, ...
197     'New York, NY', 'San Francisco, CA', 'Dallas, ...
198     'New York, NY', 'San Francisco, CA', 'Dallas, ...
199     'New York, NY', 'San Francisco, CA', 'Dallas, ...
200     'New York, NY', 'San Francisco, CA', 'Dallas, ...
201     'New York, NY', 'San Francisco, CA', 'Dallas, ...
202     'New York, NY', 'San Francisco, CA', 'Dallas, ...
203     'New York, NY', 'San Francisco, CA', 'Dallas, ...
204     'New York, NY', 'San Francisco, CA', 'Dallas, ...
205     'New York, NY', 'San Francisco, CA', 'Dallas, ...
206     'New York, NY', 'San Francisco, CA', 'Dallas, ...
207     'New York, NY', 'San Francisco, CA', 'Dallas, ...
208             AWS and Tableau and Azure and R and Excel
209     'New York, NY', 'San Francisco, CA', 'Dallas, ...
210     'New York, NY', 'San Francisco, CA', 'Dallas, ...
211     'New York, NY', 'San Francisco, CA', 'Dallas, ...
212     'New York, NY', 'San Francisco, CA', 'Dallas, ...
213     'New York, NY', 'San Francisco, CA', 'Dallas, ...
214     'New York, NY', 'San Francisco, CA', 'Dallas, ...
215     'New York, NY', 'San Francisco, CA', 'Dallas, ...
216     'New York, NY', 'San Francisco, CA', 'Dallas, ...
217     'New York, NY', 'San Francisco, CA', 'Dallas, ...
218     'New York, NY', 'San Francisco, CA', 'Dallas, ...
219     'New York, NY', 'San Francisco, CA', 'Dallas, ...
220     'New York, NY', 'San Francisco, CA', 'Dallas, ...
221     'New York, NY', 'San Francisco, CA', 'Dallas, ...
222     'New York, NY', 'San Francisco, CA', 'Dallas, ...
223     'New York, NY', 'San Francisco, CA', 'Dallas, ...
224     'New York, NY', 'San Francisco, CA', 'Dallas, ...
225     'New York, NY', 'San Francisco, CA', 'Dallas, ...
226     'New York, NY', 'San Francisco, CA', 'Dallas, ...
227     'New York, NY', 'San Francisco, CA', 'Dallas, ...
228     'New York, NY', 'San Francisco, CA', 'Dallas, ...
229     'New York, NY', 'San Francisco, CA', 'Dallas, ...
230     'New York, NY', 'San Francisco, CA', 'Dallas, ...
231     'New York, NY', 'San Francisco, CA', 'Dallas, ...
232     'New York, NY', 'San Francisco, CA', 'Dallas, ...
233     'New York, NY', 'San Francisco, CA', 'Dallas, ...
234     'New York, NY', 'San Francisco, CA', 'Dallas, ...
235     'New York, NY', 'San Francisco, CA', 'Dallas, ...
236     'New York, NY', 'San Francisco, CA', 'Dallas, ...
237     'New York, NY', 'San Francisco, CA', 'Dallas, ...
238     'New York, NY', 'San Francisco, CA', 'Dallas, ...
239     'New York, NY', 'San Francisco, CA', 'Dallas, ...
240     'New York, NY', 'San Francisco, CA', 'Dallas, ...
241     'New York, NY', 'San Francisco, CA', 'Dallas, ...
242     'New York, NY', 'San Francisco, CA', 'Dallas, ...
243     'New York, NY', 'San Francisco, CA', 'Dallas, ...
244     'New York, NY', 'San Francisco, CA', 'Dallas, ...
245     'New York, NY', 'San Francisco, CA', 'Dallas, ...
246     'New York, NY', 'San Francisco, CA', 'Dallas, ...
247     'New York, NY', 'San Francisco, CA', 'Dallas, ...
248     'New York, NY', 'San Francisco, CA', 'Dallas, ...
249     'New York, NY', 'San Francisco, CA', 'Dallas, ...
250     'New York, NY', 'San Francisco, CA', 'Dallas, ...
251     'New York, NY', 'San Francisco, CA', 'Dallas, ...
252     'New York, NY', 'San Francisco, CA', 'Dallas, ...
253     'New York, NY', 'San Francisco, CA', 'Dallas, ...
254     'New York, NY', 'San Francisco, CA', 'Dallas, ...
255     'New York, NY', 'San Francisco, CA', 'Dallas, ...
256     'New York, NY', 'San Francisco, CA', 'Dallas, ...
257     'New York, NY', 'San Francisco, CA', 'Dallas, ...
258     'New York, NY', 'San Francisco, CA', 'Dallas, ...
259     'New York, NY', 'San Francisco, CA', 'Dallas, ...
260     'New York, NY', 'San Francisco, CA', 'Dallas, ...
261     'New York, NY', 'San Francisco, CA', 'Dallas, ...
262     'New York, NY', 'San Francisco, CA', 'Dallas, ...
263     'New York, NY', 'San Francisco, CA', 'Dallas, ...
264     'New York, NY', 'San Francisco, CA', 'Dallas, ...
265     'New York, NY', 'San Francisco, CA', 'Dallas, ...
266     'New York, NY', 'San Francisco, CA', 'Dallas, ...
267     'New York, NY', 'San Francisco, CA', 'Dallas, ...
268     'New York, NY', 'San Francisco, CA', 'Dallas, ...
269     'New York, NY', 'San Francisco, CA', 'Dallas, ...
270     'New York, NY', 'San Francisco, CA', 'Dallas, ...
271     'New York, NY', 'San Francisco, CA', 'Dallas, ...
272     'New York, NY', 'San Francisco, CA', 'Dallas, ...
273     'New York, NY', 'San Francisco, CA', 'Dallas, ...
274     'New York, NY', 'San Francisco, CA', 'Dallas, ...
275     'New York, NY', 'San Francisco, CA', 'Dallas, ...
276     'New York, NY', 'San Francisco, CA', 'Dallas, ...
277     'New York, NY', 'San Francisco, CA', 'Dallas, ...
278     'New York, NY', 'San Francisco, CA', 'Dallas, ...
279     'New York, NY', 'San Francisco, CA', 'Dallas, ...
280     'New York, NY', 'San Francisco, CA', 'Dallas, ...
281     'New York, NY', 'San Francisco, CA', 'Dallas, ...
282     'New York, NY', 'San Francisco, CA', 'Dallas, ...
283     'New York, NY', 'San Francisco, CA', 'Dallas, ...
284     'New York, NY', 'San Francisco, CA', 'Dallas, ...
285     'New York, NY', 'San Francisco, CA', 'Dallas, ...
286     'New York, NY', 'San Francisco, CA', 'Dallas, ...
287     'New York, NY', 'San Francisco, CA', 'Dallas, ...
288     'New York, NY', 'San Francisco, CA', 'Dallas, ...
289     'New York, NY', 'San Francisco, CA', 'Dallas, ...
290     'New York, NY', 'San Francisco, CA', 'Dallas, ...
291     'New York, NY', 'San Francisco, CA', 'Dallas, ...
292     'New York, NY', 'San Francisco, CA', 'Dallas, ...
293     'New York, NY', 'San Francisco, CA', 'Dallas, ...
294     'New York, NY', 'San Francisco, CA', 'Dallas, ...
295     'New York, NY', 'San Francisco, CA', 'Dallas, ...
296     'New York, NY', 'San Francisco, CA', 'Dallas, ...
297     'New York, NY', 'San Francisco, CA', 'Dallas, ...
298     'New York, NY', 'San Francisco, CA', 'Dallas, ...
299     'New York, NY', 'San Francisco, CA', 'Dallas, ...
300     'New York, NY', 'San Francisco, CA', 'Dallas, ...
301     'New York, NY', 'San Francisco, CA', 'Dallas, ...
302     'New York, NY', 'San Francisco, CA', 'Dallas, ...
303     'New York, NY', 'San Francisco, CA', 'Dallas, ...
304     'New York, NY', 'San Francisco, CA', 'Dallas, ...
305     'New York, NY', 'San Francisco, CA', 'Dallas, ...
306     'New York, NY', 'San Francisco, CA', 'Dallas, ...
307     'New York, NY', 'San Francisco, CA', 'Dallas, ...
308     'New York, NY', 'San Francisco, CA', 'Dallas, ...
309     'New York, NY', 'San Francisco, CA', 'Dallas, ...
310     'New York, NY', 'San Francisco, CA', 'Dallas, ...
311     'New York, NY', 'San Francisco, CA', 'Dallas, ...
312     'New York, NY', 'San Francisco, CA', 'Dallas, ...
313     'New York, NY', 'San Francisco, CA', 'Dallas, ...
314     'New York, NY', 'San Francisco, CA', 'Dallas, ...
315     'New York, NY', 'San Francisco, CA', 'Dallas, ...
316     'New York, NY', 'San Francisco, CA', 'Dallas, ...
317     'New York, NY', 'San Francisco, CA', 'Dallas, ...
318     'New York, NY', 'San Francisco, CA', 'Dallas, ...
319     'New York, NY', 'San Francisco, CA', 'Dallas, ...
320     'New York, NY', 'San Francisco, CA', 'Dallas, ...
321     'New York, NY', 'San Francisco, CA', 'Dallas, ...
322     'New York, NY', 'San Francisco, CA', 'Dallas, ...
323     'New York, NY', 'San Francisco, CA', 'Dallas, ...
324     'New York, NY', 'San Francisco, CA', 'Dallas, ...
325     'New York, NY', 'San Francisco, CA', 'Dallas, ...
326     'New York, NY', 'San Francisco, CA', 'Dallas, ...
327     'New York, NY', 'San Francisco, CA', 'Dallas, ...
328     'New York, NY', 'San Francisco, CA', 'Dallas, ...
329     'New York, NY', 'San Francisco, CA', 'Dallas, ...
330     'New York, NY', 'San Francisco, CA', 'Dallas, ...
331     'New York, NY', 'San Francisco, CA', 'Dallas, ...
332     'New York, NY', 'San Francisco, CA', 'Dallas, ...
333     'New York, NY', 'San Francisco, CA', 'Dallas, ...
334     'New York, NY', 'San Francisco, CA', 'Dallas, ...
335     'New York, NY', 'San Francisco, CA', 'Dallas, ...
336     'New York, NY', 'San Francisco, CA', 'Dallas, ...
337     'New York, NY', 'San Francisco, CA', 'Dallas, ...
338     'New York, NY', 'San Francisco, CA', 'Dallas, ...
339     'New York, NY', 'San Francisco, CA', 'Dallas, ...
340     'New York, NY', 'San Francisco, CA', 'Dallas, ...
341     'New York, NY', 'San Francisco, CA', 'Dallas, ...
342     'New York, NY', 'San Francisco, CA', 'Dallas, ...
343     'New York, NY', 'San Francisco, CA', 'Dallas, ...

## Problem 1.5 : Fixing Location values

In [ ]:
# Show all columns in the dataframe
bdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   job_title               2499 non-null   object
 1   salary                  2500 non-null   object
 2   location                2500 non-null   object
 3   remote_location         2500 non-null   object
 4   company_size            2499 non-null   object
 5   experience_level        2500 non-null   object
 6   employment_type         2479 non-null   object
 7   skills                  2387 non-null   object
 8   experience_level_value  2500 non-null   int64
 9   company_size_value      2500 non-null   int64
 10  employment_type_value   2500 non-null   int64
dtypes: int64(3), object(8)
memory usage: 215.0+ KB

In [ ]:
# Print all the unique locations, as you can see we have 9 values to work with
unique_location = bdata['location'].unique()
unique_location

array(['120k',
       "'New York, NY', 'San Francisco, CA', 'Dallas, TX', 'Remote', 'US', 'London, UK', 'Austin, TX', 'Anywhere', nan, 'Houston,TX', 'Huntsville,AL'",
       'AWS and Tableau and Azure and R and Excel', 'Contract',
       'Marketing Data Analyst', 'Temporarily Remote', 'EN', 'MI',
       '140,000.00', 'Data Analytics Specialist', 'Sr.', '1', '500',
       'C2C', 'Medium', 'Full-time',
       "'SQL', 'Python', 'Google Cloud', 'Tableau', 'Azure'", 'Startup',
       '65000Competitive', '$50/hr', 'Unknown', 'Power BI;Google Cloud;'],
      dtype=object)

In [ ]:
print(bdata['location'].value_counts().head(30))

location
'New York, NY', 'San Francisco, CA', 'Dallas, TX', 'Remote', 'US', 'London, UK', 'Austin, TX', 'Anywhere', nan, 'Houston,TX', 'Huntsville,AL'    2476
120k                                                                                                                                                2
Contract                                                                                                                                            2
MI                                                                                                                                                  2
Marketing Data Analyst                                                                                                                              1
AWS and Tableau and Azure and R and Excel                                                                                                           1
Temporarily Remote                                                                                                                                  1
EN                                                                                                                                                  1
140,000.00                                                                                                                                          1
Data Analytics Specialist                                                                                                                           1
Sr.                                                                                                                                                 1
1                                                                                                                                                   1
500                                                                                                                                                 1
C2C                                                                                                                                                 1
Medium                                                                                                                                              1
Full-time                                                                                                                                           1
'SQL', 'Python', 'Google Cloud', 'Tableau', 'Azure'                                                                                                 1
Startup                                                                                                                                             1
65000Competitive                                                                                                                                    1
$50/hr                                                                                                                                              1
Unknown                                                                                                                                             1
Power BI;Google Cloud;                                                                                                                              1
Name: count, dtype: int64

In [ ]:
bdata.head(35)

,job_title,salary,location,remote_location,company_size,experience_level,employment_type,skills,experience_level_value,company_size_value,employment_type_value
0,Sr.,0,120k,C2C,Large,Excel;R,None,False,0,3,0
1,DATA ANALYST,65000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",No,Huge,Sr,Freelance,"AWS, Python, Google Cloud, Power BI",3,4,6
2,Data Analyst,65000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",1,Large,Pr,Contract,"Python, , Excel",4,3,4
3,Marketing Data Analyst,0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Yes,Unknown,None,Regular,"Tableau , Azure , R , Python ,",0,0,3
4,Data Analyst II,65000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Hybrid,Unknown,Jr,Part-time,"Python , Tableau , Azure , Google Cloud , SQL",1,0,2
5,Senior Data Analyst,0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Partial,Startup,Mi,Part-time,"Excel, R",2,1,2
6,Senior Data Analyst,95000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",False,Startup,Pr,Full-time,"Python, AWS",4,1,1
7,Sr. Data Analyst,65000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",1,Medium,Jr,Regular,"Tableau, Power BI, Python, , AWS",1,2,3
8,Marketing Data Analyst,120000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",0,Large,Mi,Full-time,"Google Cloud, Azure, Excel, Python, SQL",2,3,1
9,DATA ANALYST,95000.0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",False,Unknown,Mi,Temporary,", Azure, Excel, SQL, R",2,0,5
10,Product Data Analyst,110000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",False,Large,Sr,Regular,"Excel , Azure , R , Google Cloud , Tableau",3,3,3
11,Marketing Data Analyst,0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",False,Small,Sr,Full-time,"Tableau,Azure,SQL,Power BI",3,0,1
12,BI Analyst,70000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Temporarily Remote,Startup,Mi,Contract,"SQL, R, Tableau, Power BI, Google Cloud",2,1,4
13,DATA ANALYST,0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",1,Large,Mi,Contract,"AWS, Python, Google Cloud, Tableau, R",2,3,4
14,Data Analyst - Remote,110000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",0,Large,Jr,Part-time,"AWS, Azure, Excel",1,3,2
15,Junior Data Analyst,0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Hybrid,Large,Sr,Full-time,None,3,3,1
16,Data Analyst,50,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",1,Medium,Jr,Part-time,"Excel,",1,2,2
17,Data Analyst,110000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Partial,Startup,Mi,Full-time,"Python, AWS, R",2,1,1
18,DATA ANALYST,0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Hybrid,Large,Mi,Part-time,"Python, Power BI, AWS, Azure,",2,3,2
19,Senior Data Analyst,0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Temporarily Remote,Startup,Pr,Freelance,"Python, Excel, R",4,1,6
20,Senior Data Analyst,70000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Partial,Large,Jr,Regular,"Azure,",1,3,3
21,BI Analyst,70000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Yes,Startup,Mi,Part-time,"Azure, SQL, Excel, Python",2,1,2
22,Data Analyst - Remote,50,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",True,Large,None,Contract,"Azure,AWS,Power BI",0,3,4
23,Data Analyst,50000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Hybrid,Huge,Jr,Part-time,", R, Python, Azure",1,4,2
24,BI Analyst,120000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Yes,Startup,None,Contract,"SQL,Google Cloud,Python,Excel,Azure",0,1,4
25,Senior Data Analyst,65000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",True,Startup,Sr,Freelance,"Google Cloud, Tableau, Excel, SQL, Power BI",3,1,6
26,Marketing Data Analyst,95000.0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Hybrid,Unknown,Mi,Full-time,"Google Cloud,",2,0,1
27,Product Data Analyst,50000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Yes,Startup,Jr,Contract,", AWS , Google Cloud",1,1,4
28,Marketing Data Analyst,95000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Partial,Startup,Jr,Part-time,"R , Azure , Tableau",1,1,2
29,BI Analyst,70000.0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",False,Unknown,Mi,Contract,None,2,0,4
30,Junior Data Analyst,50,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Hybrid,Startup,None,Contract,"Azure,SQL,AWS,R",0,1,4
31,Senior Data Analyst,50,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Partial,Medium,Sr,Part-time,"SQL,Power BI,R",3,2,2
32,Data Analytics Specialist,0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",0,Medium,Sr,Full-time,"Google Cloud, SQL, Azure, R",3,2,1
33,Data Analyst - Remote,95000.0,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",No,Startup,Sr,Full-time,"R, , Power BI",3,1,1
34,Data Analyst II,110000,"'New York, NY', 'San Francisco, CA', 'Dallas, ...",Partial,Large,Pr,Part-time,", AWS, Tableau, Python, Excel",4,3,2

In [ ]:
# Remove '[' and ']' from the Location column
bdata['location'] = bdata['location'].str.replace(r"[\[\]]", "", regex=True)

In [ ]:
# Check to see if '[' and ']' were removed
bdata['location'].head(25)

0                                                  120k
1     'New York, NY', 'San Francisco, CA', 'Dallas, ...
2     'New York, NY', 'San Francisco, CA', 'Dallas, ...
3     'New York, NY', 'San Francisco, CA', 'Dallas, ...
4     'New York, NY', 'San Francisco, CA', 'Dallas, ...
5     'New York, NY', 'San Francisco, CA', 'Dallas, ...
6     'New York, NY', 'San Francisco, CA', 'Dallas, ...
7     'New York, NY', 'San Francisco, CA', 'Dallas, ...
8     'New York, NY', 'San Francisco, CA', 'Dallas, ...
9     'New York, NY', 'San Francisco, CA', 'Dallas, ...
10    'New York, NY', 'San Francisco, CA', 'Dallas, ...
11    'New York, NY', 'San Francisco, CA', 'Dallas, ...
12    'New York, NY', 'San Francisco, CA', 'Dallas, ...
13    'New York, NY', 'San Francisco, CA', 'Dallas, ...
14    'New York, NY', 'San Francisco, CA', 'Dallas, ...
15    'New York, NY', 'San Francisco, CA', 'Dallas, ...
16    'New York, NY', 'San Francisco, CA', 'Dallas, ...
17    'New York, NY', 'San Francisco, CA', 'Dallas, ...
18    'New York, NY', 'San Francisco, CA', 'Dallas, ...
19    'New York, NY', 'San Francisco, CA', 'Dallas, ...
20    'New York, NY', 'San Francisco, CA', 'Dallas, ...
21    'New York, NY', 'San Francisco, CA', 'Dallas, ...
22    'New York, NY', 'San Francisco, CA', 'Dallas, ...
23    'New York, NY', 'San Francisco, CA', 'Dallas, ...
24    'New York, NY', 'San Francisco, CA', 'Dallas, ...
Name: location, dtype: object

In [ ]:
# 1. Removes all unwanted values in the location column

# Define the set of non-location values provided by the user
non_location_set = {
    'AWS and Tableau and Azure and R and Excel', 'Contract',
    'Marketing Data Analyst', 'Temporarily Remote', 'EN', 'MI',
    '140,000.00', 'Data Analytics Specialist', 'Sr.', '1', '500',
    'C2C', 'Medium', 'Full-time', '120k',
    "'SQL', 'Python', 'Google Cloud', 'Tableau', 'Azure'", 'Startup',
    '65000Competitive', '$50/hr', 'Unknown', 'Power BI;Google Cloud;'
}

# Replace these values with NaN in the location column
bdata['location'] = bdata['location'].replace(list(non_location_set), np.nan)

# Also handle the '120k' value found in the previous search
# bdata['location'] = bdata['location'].replace('120k', np.nan)

# Check the results
print(f"Remaining unique values in location: {bdata['location'].nunique()}")
display(bdata['location'].value_counts().head())

Remaining unique values in location: 1

location
'New York, NY', 'San Francisco, CA', 'Dallas, TX', 'Remote', 'US', 'London, UK', 'Austin, TX', 'Anywhere', nan, 'Houston,TX', 'Huntsville,AL'    2476
Name: count, dtype: int64

In [ ]:
# 1.5 Check to see if all unwanted values have been removed and turned into Nan values
bdata['location'].head(210)

0                                                    NaN
1      'New York, NY', 'San Francisco, CA', 'Dallas, ...
2      'New York, NY', 'San Francisco, CA', 'Dallas, ...
3      'New York, NY', 'San Francisco, CA', 'Dallas, ...
4      'New York, NY', 'San Francisco, CA', 'Dallas, ...
5      'New York, NY', 'San Francisco, CA', 'Dallas, ...
6      'New York, NY', 'San Francisco, CA', 'Dallas, ...
7      'New York, NY', 'San Francisco, CA', 'Dallas, ...
8      'New York, NY', 'San Francisco, CA', 'Dallas, ...
9      'New York, NY', 'San Francisco, CA', 'Dallas, ...
10     'New York, NY', 'San Francisco, CA', 'Dallas, ...
11     'New York, NY', 'San Francisco, CA', 'Dallas, ...
12     'New York, NY', 'San Francisco, CA', 'Dallas, ...
13     'New York, NY', 'San Francisco, CA', 'Dallas, ...
14     'New York, NY', 'San Francisco, CA', 'Dallas, ...
15     'New York, NY', 'San Francisco, CA', 'Dallas, ...
16     'New York, NY', 'San Francisco, CA', 'Dallas, ...
17     'New York, NY', 'San Francisco, CA', 'Dallas, ...
18     'New York, NY', 'San Francisco, CA', 'Dallas, ...
19     'New York, NY', 'San Francisco, CA', 'Dallas, ...
20     'New York, NY', 'San Francisco, CA', 'Dallas, ...
21     'New York, NY', 'San Francisco, CA', 'Dallas, ...
22     'New York, NY', 'San Francisco, CA', 'Dallas, ...
23     'New York, NY', 'San Francisco, CA', 'Dallas, ...
24     'New York, NY', 'San Francisco, CA', 'Dallas, ...
25     'New York, NY', 'San Francisco, CA', 'Dallas, ...
26     'New York, NY', 'San Francisco, CA', 'Dallas, ...
27     'New York, NY', 'San Francisco, CA', 'Dallas, ...
28     'New York, NY', 'San Francisco, CA', 'Dallas, ...
29     'New York, NY', 'San Francisco, CA', 'Dallas, ...
30     'New York, NY', 'San Francisco, CA', 'Dallas, ...
31     'New York, NY', 'San Francisco, CA', 'Dallas, ...
32     'New York, NY', 'San Francisco, CA', 'Dallas, ...
33     'New York, NY', 'San Francisco, CA', 'Dallas, ...
34     'New York, NY', 'San Francisco, CA', 'Dallas, ...
35     'New York, NY', 'San Francisco, CA', 'Dallas, ...
36     'New York, NY', 'San Francisco, CA', 'Dallas, ...
37     'New York, NY', 'San Francisco, CA', 'Dallas, ...
38     'New York, NY', 'San Francisco, CA', 'Dallas, ...
39     'New York, NY', 'San Francisco, CA', 'Dallas, ...
40     'New York, NY', 'San Francisco, CA', 'Dallas, ...
41     'New York, NY', 'San Francisco, CA', 'Dallas, ...
42     'New York, NY', 'San Francisco, CA', 'Dallas, ...
43     'New York, NY', 'San Francisco, CA', 'Dallas, ...
44     'New York, NY', 'San Francisco, CA', 'Dallas, ...
45     'New York, NY', 'San Francisco, CA', 'Dallas, ...
46     'New York, NY', 'San Francisco, CA', 'Dallas, ...
47     'New York, NY', 'San Francisco, CA', 'Dallas, ...
48     'New York, NY', 'San Francisco, CA', 'Dallas, ...
49     'New York, NY', 'San Francisco, CA', 'Dallas, ...
50     'New York, NY', 'San Francisco, CA', 'Dallas, ...
51     'New York, NY', 'San Francisco, CA', 'Dallas, ...
52     'New York, NY', 'San Francisco, CA', 'Dallas, ...
53     'New York, NY', 'San Francisco, CA', 'Dallas, ...
54     'New York, NY', 'San Francisco, CA', 'Dallas, ...
55     'New York, NY', 'San Francisco, CA', 'Dallas, ...
56     'New York, NY', 'San Francisco, CA', 'Dallas, ...
57     'New York, NY', 'San Francisco, CA', 'Dallas, ...
58     'New York, NY', 'San Francisco, CA', 'Dallas, ...
59     'New York, NY', 'San Francisco, CA', 'Dallas, ...
60     'New York, NY', 'San Francisco, CA', 'Dallas, ...
61     'New York, NY', 'San Francisco, CA', 'Dallas, ...
62     'New York, NY', 'San Francisco, CA', 'Dallas, ...
63     'New York, NY', 'San Francisco, CA', 'Dallas, ...
64     'New York, NY', 'San Francisco, CA', 'Dallas, ...
65     'New York, NY', 'San Francisco, CA', 'Dallas, ...
66     'New York, NY', 'San Francisco, CA', 'Dallas, ...
67     'New York, NY', 'San Francisco, CA', 'Dallas, ...
68     'New York, NY', 'San Francisco, CA', 'Dallas, ...
69     'New York, NY', 'San Francisco, CA', 'Dallas, ...
70     'New York, NY', 'San Francisco, CA', 'Dallas, ...
71     'New York, NY', 'San Francisco, CA', 'Dallas, ...
72     'New York, NY', 'San Francisco, CA', 'Dallas, ...
73     'New York, NY', 'San Francisco, CA', 'Dallas, ...
74     'New York, NY', 'San Francisco, CA', 'Dallas, ...
75     'New York, NY', 'San Francisco, CA', 'Dallas, ...
76     'New York, NY', 'San Francisco, CA', 'Dallas, ...
77     'New York, NY', 'San Francisco, CA', 'Dallas, ...
78     'New York, NY', 'San Francisco, CA', 'Dallas, ...
79     'New York, NY', 'San Francisco, CA', 'Dallas, ...
80     'New York, NY', 'San Francisco, CA', 'Dallas, ...
81     'New York, NY', 'San Francisco, CA', 'Dallas, ...
82     'New York, NY', 'San Francisco, CA', 'Dallas, ...
83     'New York, NY', 'San Francisco, CA', 'Dallas, ...
84     'New York, NY', 'San Francisco, CA', 'Dallas, ...
85     'New York, NY', 'San Francisco, CA', 'Dallas, ...
86     'New York, NY', 'San Francisco, CA', 'Dallas, ...
87     'New York, NY', 'San Francisco, CA', 'Dallas, ...
88     'New York, NY', 'San Francisco, CA', 'Dallas, ...
89     'New York, NY', 'San Francisco, CA', 'Dallas, ...
90     'New York, NY', 'San Francisco, CA', 'Dallas, ...
91     'New York, NY', 'San Francisco, CA', 'Dallas, ...
92     'New York, NY', 'San Francisco, CA', 'Dallas, ...
93     'New York, NY', 'San Francisco, CA', 'Dallas, ...
94     'New York, NY', 'San Francisco, CA', 'Dallas, ...
95     'New York, NY', 'San Francisco, CA', 'Dallas, ...
96     'New York, NY', 'San Francisco, CA', 'Dallas, ...
97     'New York, NY', 'San Francisco, CA', 'Dallas, ...
98     'New York, NY', 'San Francisco, CA', 'Dallas, ...
99     'New York, NY', 'San Francisco, CA', 'Dallas, ...
100    'New York, NY', 'San Francisco, CA', 'Dallas, ...
101    'New York, NY', 'San Francisco, CA', 'Dallas, ...
102    'New York, NY', 'San Francisco, CA', 'Dallas, ...
103    'New York, NY', 'San Francisco, CA', 'Dallas, ...
104    'New York, NY', 'San Francisco, CA', 'Dallas, ...
105    'New York, NY', 'San Francisco, CA', 'Dallas, ...
106    'New York, NY', 'San Francisco, CA', 'Dallas, ...
107    'New York, NY', 'San Francisco, CA', 'Dallas, ...
108    'New York, NY', 'San Francisco, CA', 'Dallas, ...
109    'New York, NY', 'San Francisco, CA', 'Dallas, ...
110    'New York, NY', 'San Francisco, CA', 'Dallas, ...
111    'New York, NY', 'San Francisco, CA', 'Dallas, ...
112    'New York, NY', 'San Francisco, CA', 'Dallas, ...
113    'New York, NY', 'San Francisco, CA', 'Dallas, ...
114    'New York, NY', 'San Francisco, CA', 'Dallas, ...
115    'New York, NY', 'San Francisco, CA', 'Dallas, ...
116    'New York, NY', 'San Francisco, CA', 'Dallas, ...
117    'New York, NY', 'San Francisco, CA', 'Dallas, ...
118    'New York, NY', 'San Francisco, CA', 'Dallas, ...
119    'New York, NY', 'San Francisco, CA', 'Dallas, ...
120    'New York, NY', 'San Francisco, CA', 'Dallas, ...
121    'New York, NY', 'San Francisco, CA', 'Dallas, ...
122    'New York, NY', 'San Francisco, CA', 'Dallas, ...
123    'New York, NY', 'San Francisco, CA', 'Dallas, ...
124    'New York, NY', 'San Francisco, CA', 'Dallas, ...
125    'New York, NY', 'San Francisco, CA', 'Dallas, ...
126    'New York, NY', 'San Francisco, CA', 'Dallas, ...
127    'New York, NY', 'San Francisco, CA', 'Dallas, ...
128    'New York, NY', 'San Francisco, CA', 'Dallas, ...
129    'New York, NY', 'San Francisco, CA', 'Dallas, ...
130    'New York, NY', 'San Francisco, CA', 'Dallas, ...
131    'New York, NY', 'San Francisco, CA', 'Dallas, ...
132    'New York, NY', 'San Francisco, CA', 'Dallas, ...
133    'New York, NY', 'San Francisco, CA', 'Dallas, ...
134    'New York, NY', 'San Francisco, CA', 'Dallas, ...
135    'New York, NY', 'San Francisco, CA', 'Dallas, ...
136    'New York, NY', 'San Francisco, CA', 'Dallas, ...
137    'New York, NY', 'San Francisco, CA', 'Dallas, ...
138    'New York, NY', 'San Francisco, CA', 'Dallas, ...
139    'New York, NY', 'San Francisco, CA', 'Dallas, ...
140    'New York, NY', 'San Francisco, CA', 'Dallas, ...
141    'New York, NY', 'San Francisco, CA', 'Dallas, ...
142    'New York, NY', 'San Francisco, CA', 'Dallas, ...
143    'New York, NY', 'San Francisco, CA', 'Dallas, ...
144    'New York, NY', 'San Francisco, CA', 'Dallas, ...
145    'New York, NY', 'San Francisco, CA', 'Dallas, ...
146    'New York, NY', 'San Francisco, CA', 'Dallas, ...
147    'New York, NY', 'San Francisco, CA', 'Dallas, ...
148    'New York, NY', 'San Francisco, CA', 'Dallas, ...
149    'New York, NY', 'San Francisco, CA', 'Dallas, ...
150    'New York, NY', 'San Francisco, CA', 'Dallas, ...
151    'New York, NY', 'San Francisco, CA', 'Dallas, ...
152    'New York, NY', 'San Francisco, CA', 'Dallas, ...
153    'New York, NY', 'San Francisco, CA', 'Dallas, ...
154    'New York, NY', 'San Francisco, CA', 'Dallas, ...
155    'New York, NY', 'San Francisco, CA', 'Dallas, ...
156    'New York, NY', 'San Francisco, CA', 'Dallas, ...
157    'New York, NY', 'San Francisco, CA', 'Dallas, ...
158    'New York, NY', 'San Francisco, CA', 'Dallas, ...
159    'New York, NY', 'San Francisco, CA', 'Dallas, ...
160    'New York, NY', 'San Francisco, CA', 'Dallas, ...
161    'New York, NY', 'San Francisco, CA', 'Dallas, ...
162    'New York, NY', 'San Francisco, CA', 'Dallas, ...
163    'New York, NY', 'San Francisco, CA', 'Dallas, ...
164    'New York, NY', 'San Francisco, CA', 'Dallas, ...
165    'New York, NY', 'San Francisco, CA', 'Dallas, ...
166    'New York, NY', 'San Francisco, CA', 'Dallas, ...
167    'New York, NY', 'San Francisco, CA', 'Dallas, ...
168    'New York, NY', 'San Francisco, CA', 'Dallas, ...
169    'New York, NY', 'San Francisco, CA', 'Dallas, ...
170    'New York, NY', 'San Francisco, CA', 'Dallas, ...
171    'New York, NY', 'San Francisco, CA', 'Dallas, ...
172    'New York, NY', 'San Francisco, CA', 'Dallas, ...
173    'New York, NY', 'San Francisco, CA', 'Dallas, ...
174    'New York, NY', 'San Francisco, CA', 'Dallas, ...
175    'New York, NY', 'San Francisco, CA', 'Dallas, ...
176    'New York, NY', 'San Francisco, CA', 'Dallas, ...
177    'New York, NY', 'San Francisco, CA', 'Dallas, ...
178    'New York, NY', 'San Francisco, CA', 'Dallas, ...
179    'New York, NY', 'San Francisco, CA', 'Dallas, ...
180    'New York, NY', 'San Francisco, CA', 'Dallas, ...
181    'New York, NY', 'San Francisco, CA', 'Dallas, ...
182    'New York, NY', 'San Francisco, CA', 'Dallas, ...
183    'New York, NY', 'San Francisco, CA', 'Dallas, ...
184    'New York, NY', 'San Francisco, CA', 'Dallas, ...
185    'New York, NY', 'San Francisco, CA', 'Dallas, ...
186    'New York, NY', 'San Francisco, CA', 'Dallas, ...
187    'New York, NY', 'San Francisco, CA', 'Dallas, ...
188    'New York, NY', 'San Francisco, CA', 'Dallas, ...
189    'New York, NY', 'San Francisco, CA', 'Dallas, ...
190    'New York, NY', 'San Francisco, CA', 'Dallas, ...
191    'New York, NY', 'San Francisco, CA', 'Dallas, ...
192    'New York, NY', 'San Francisco, CA', 'Dallas, ...
193    'New York, NY', 'San Francisco, CA', 'Dallas, ...
194    'New York, NY', 'San Francisco, CA', 'Dallas, ...
195    'New York, NY', 'San Francisco, CA', 'Dallas, ...
196    'New York, NY', 'San Francisco, CA', 'Dallas, ...
197    'New York, NY', 'San Francisco, CA', 'Dallas, ...
198    'New York, NY', 'San Francisco, CA', 'Dallas, ...
199    'New York, NY', 'San Francisco, CA', 'Dallas, ...
200    'New York, NY', 'San Francisco, CA', 'Dallas, ...
201    'New York, NY', 'San Francisco, CA', 'Dallas, ...
202    'New York, NY', 'San Francisco, CA', 'Dallas, ...
203    'New York, NY', 'San Francisco, CA', 'Dallas, ...
204    'New York, NY', 'San Francisco, CA', 'Dallas, ...
205    'New York, NY', 'San Francisco, CA', 'Dallas, ...
206    'New York, NY', 'San Francisco, CA', 'Dallas, ...
207    'New York, NY', 'San Francisco, CA', 'Dallas, ...
208                                                  NaN
209    'New York, NY', 'San Francisco, CA', 'Dallas, ...
Name: location, dtype: object

In [ ]:
# 2.0, Next remove all values in the location column that are the target string
# Define the specific grouped string to remove
target_string = "'New York, NY', 'San Francisco, CA', 'Dallas, TX', 'Remote', 'US', 'London, UK', 'Austin, TX', 'Anywhere', nan, 'Houston,TX', 'Huntsville,AL'"

# Replace the grouped string and actual NaN values with NaN
bdata['location'] = bdata['location'].replace(target_string, np.nan)
bdata['location'] = bdata['location'].replace(['nan', 'NaN', 'None', 'Anywhere'], np.nan)

# Identify rows where 'location' is null
mask = bdata['location'].isna()

# Verify the cleaning results
print(f"Unique locations after removal: {bdata['location'].nunique()}")
print(f"Number of NaN values to be filled: {bdata['location'].isna().sum()}")
display(bdata['location'].value_counts(dropna=False).head())

Unique locations after removal: 0
Number of NaN values to be filled: 2500

/tmp/ipykernel_21978/2004342734.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bdata['location'] = bdata['location'].replace(target_string, np.nan)

location
NaN    2500
Name: count, dtype: int64

In [ ]:
# 3.0 Check bdata location, should be full of Nan
bdata['location']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
8      NaN
9      NaN
10     NaN
11     NaN
12     NaN
13     NaN
14     NaN
15     NaN
16     NaN
17     NaN
18     NaN
19     NaN
20     NaN
21     NaN
22     NaN
23     NaN
24     NaN
25     NaN
26     NaN
27     NaN
28     NaN
29     NaN
30     NaN
31     NaN
32     NaN
33     NaN
34     NaN
35     NaN
36     NaN
37     NaN
38     NaN
39     NaN
40     NaN
41     NaN
42     NaN
43     NaN
44     NaN
45     NaN
46     NaN
47     NaN
48     NaN
49     NaN
50     NaN
51     NaN
52     NaN
53     NaN
54     NaN
55     NaN
56     NaN
57     NaN
58     NaN
59     NaN
60     NaN
61     NaN
62     NaN
63     NaN
64     NaN
65     NaN
66     NaN
67     NaN
68     NaN
69     NaN
70     NaN
71     NaN
72     NaN
73     NaN
74     NaN
75     NaN
76     NaN
77     NaN
78     NaN
79     NaN
80     NaN
81     NaN
82     NaN
83     NaN
84     NaN
85     NaN
86     NaN
87     NaN
88     NaN
89     NaN
90     NaN
91     NaN
92     NaN
93     NaN
94     NaN
95     NaN
96     NaN
97     NaN
98     NaN
99     NaN
100    NaN
101    NaN
102    NaN
103    NaN
104    NaN
105    NaN
106    NaN
107    NaN
108    NaN
109    NaN
110    NaN
111    NaN
112    NaN
113    NaN
114    NaN
115    NaN
116    NaN
117    NaN
118    NaN
119    NaN
120    NaN
121    NaN
122    NaN
123    NaN
124    NaN
125    NaN
126    NaN
127    NaN
128    NaN
129    NaN
130    NaN
131    NaN
132    NaN
133    NaN
134    NaN
135    NaN
136    NaN
137    NaN
138    NaN
139    NaN
140    NaN
141    NaN
142    NaN
143    NaN
144    NaN
145    NaN
146    NaN
147    NaN
148    NaN
149    NaN
150    NaN
151    NaN
152    NaN
153    NaN
154    NaN
155    NaN
156    NaN
157    NaN
158    NaN
159    NaN
160    NaN
161    NaN
162    NaN
163    NaN
164    NaN
165    NaN
166    NaN
167    NaN
168    NaN
169    NaN
170    NaN
171    NaN
172    NaN
173    NaN
174    NaN
175    NaN
176    NaN
177    NaN
178    NaN
179    NaN
180    NaN
181    NaN
182    NaN
183    NaN
184    NaN
185    NaN
186    NaN
187    NaN
188    NaN
189    NaN
190    NaN
191    NaN
192    NaN
193    NaN
194    NaN
195    NaN
196    NaN
197    NaN
198    NaN
199    NaN
200    NaN
201    NaN
202    NaN
203    NaN
204    NaN
205    NaN
206    NaN
207    NaN
208    NaN
209    NaN
210    NaN
211    NaN
212    NaN
213    NaN
214    NaN
215    NaN
216    NaN
217    NaN
218    NaN
219    NaN
220    NaN
221    NaN
222    NaN
223    NaN
224    NaN
225    NaN
226    NaN
227    NaN
228    NaN
229    NaN
230    NaN
231    NaN
232    NaN
233    NaN
234    NaN
235    NaN
236    NaN
237    NaN
238    NaN
239    NaN
240    NaN
241    NaN
242    NaN
243    NaN
244    NaN
245    NaN
246    NaN
247    NaN
248    NaN
249    NaN
250    NaN
251    NaN
252    NaN
253    NaN
254    NaN
255    NaN
256    NaN
257    NaN
258    NaN
259    NaN
260    NaN
261    NaN
262    NaN
263    NaN
264    NaN
265    NaN
266    NaN
267    NaN
268    NaN
269    NaN
270    NaN
271    NaN
272    NaN
273    NaN
274    NaN
275    NaN
276    NaN
277    NaN
278    NaN
279    NaN
280    NaN
281    NaN
282    NaN
283    NaN
284    NaN
285    NaN
286    NaN
287    NaN
288    NaN
289    NaN
290    NaN
291    NaN
292    NaN
293    NaN
294    NaN
295    NaN
296    NaN
297    NaN
298    NaN
299    NaN
300    NaN
301    NaN
302    NaN
303    NaN
304    NaN
305    NaN
306    NaN
307    NaN
308    NaN
309    NaN
310    NaN
311    NaN
312    NaN
313    NaN
314    NaN
315    NaN
316    NaN
317    NaN
318    NaN
319    NaN
320    NaN
321    NaN
322    NaN
323    NaN
324    NaN
325    NaN
326    NaN
327    NaN
328    NaN
329    NaN
330    NaN
331    NaN
332    NaN
333    NaN
334    NaN
335    NaN
336    NaN
337    NaN
338    NaN
339    NaN
340    NaN
341    NaN
342    NaN
343    NaN
344    NaN
345    NaN
346    NaN
347    NaN
348    NaN
349    NaN
350    NaN
351    NaN
352    NaN
353    NaN
354    NaN
355    NaN
356    NaN
357    NaN
358    NaN
359    NaN
360    NaN
361    NaN
362    NaN
363    NaN
364    NaN
365    NaN
366    NaN
367    NaN
368    NaN
369    NaN
370    NaN
371    NaN
372    NaN
373    NaN
374    NaN
375    NaN
376    NaN
377    NaN
378    NaN
379    NaN
380    NaN
381    NaN
382    NaN
383    NaN
384    NaN
385    NaN
386    NaN
387    NaN
388    NaN
389    NaN
390    NaN
391    NaN
392    NaN
393    NaN
394    NaN
395    NaN
396    NaN
397    NaN
398    NaN
399    NaN
400    NaN
401    NaN
402    NaN
403    NaN
404    NaN
405    NaN
406    NaN
407    NaN
408    NaN
409    NaN
410    NaN
411    NaN
412    NaN
413    NaN
414    NaN
415    NaN
416    NaN
417    NaN
418    NaN
419    NaN
420    NaN
421    NaN
422    NaN
423    NaN
424    NaN
425    NaN
426    NaN
427    NaN
428    NaN
429    NaN
430    NaN
431    NaN
432    NaN
433    NaN
434    NaN
435    NaN
436    NaN
437    NaN
438    NaN
439    NaN
440    NaN
441    NaN
442    NaN
443    NaN
444    NaN
445    NaN
446    NaN
447    NaN
448    NaN
449    NaN
450    NaN
451    NaN
452    NaN
453    NaN
454    NaN
455    NaN
456    NaN
457    NaN
458    NaN
459    NaN
460    NaN
461    NaN
462    NaN
463    NaN
464    NaN
465    NaN
466    NaN
467    NaN
468    NaN
469    NaN
470    NaN
471    NaN
472    NaN
473    NaN
474    NaN
475    NaN
476    NaN
477    NaN
478    NaN
479    NaN
480    NaN
481    NaN
482    NaN
483    NaN
484    NaN
485    NaN
486    NaN
487    NaN
488    NaN
489    NaN
490    NaN
491    NaN
492    NaN
493    NaN
494    NaN
495    NaN
496    NaN
497    NaN
498    NaN
499    NaN
500    NaN
501    NaN
502    NaN
503    NaN
504    NaN
505    NaN
506    NaN
507    NaN
508    NaN
509    NaN
510    NaN
511    NaN
512    NaN
513    NaN
514    NaN
515    NaN
516    NaN
517    NaN
518    NaN
519    NaN
520    NaN
521    NaN
522    NaN
523    NaN
524    NaN
525    NaN
526    NaN
527    NaN
528    NaN
529    NaN
530    NaN
531    NaN
532    NaN
533    NaN
534    NaN
535    NaN
536    NaN
537    NaN
538    NaN
539    NaN
540    NaN
541    NaN
542    NaN
543    NaN
544    NaN
545    NaN
546    NaN
547    NaN
548    NaN
549    NaN
550    NaN
551    NaN
552    NaN
553    NaN
554    NaN
555    NaN
556    NaN
557    NaN
558    NaN
559    NaN
560    NaN
561    NaN
562    NaN
563    NaN
564    NaN
565    NaN
566    NaN
567    NaN
568    NaN
569    NaN
570    NaN
571    NaN
572    NaN
573    NaN
574    NaN
575    NaN
576    NaN
577    NaN
578    NaN
579    NaN
580    NaN
581    NaN
582    NaN
583    NaN
584    NaN
585    NaN
586    NaN
587    NaN
588    NaN
589    NaN
590    NaN
591    NaN
592    NaN
593    NaN
594    NaN
595    NaN
596    NaN
597    NaN
598    NaN
599    NaN
600    NaN
601    NaN
602    NaN
603    NaN
604    NaN
605    NaN
606    NaN
607    NaN
608    NaN
609    NaN
610    NaN
611    NaN
612    NaN
613    NaN
614    NaN
615    NaN
616    NaN
617    NaN
618    NaN
619    NaN
620    NaN
621    NaN
622    NaN
623    NaN
624    NaN
625    NaN
626    NaN
627    NaN
628    NaN
629    NaN
630    NaN
631    NaN
632    NaN
633    NaN
634    NaN
635    NaN
636    NaN
637    NaN
638    NaN
639    NaN
640    NaN
641    NaN
642    NaN
643    NaN
644    NaN
645    NaN
646    NaN
647    NaN
648    NaN
649    NaN
650    NaN
651    NaN
652    NaN
653    NaN
654    NaN
655    NaN
656    NaN
657    NaN
658    NaN
659    NaN
660    NaN
661    NaN
662    NaN
663    NaN
664    NaN
665    NaN
666    NaN
667    NaN
668    NaN
669    NaN
670    NaN
671    NaN
672    NaN
673    NaN
674    NaN
675    NaN
676    NaN
677    NaN
678    NaN
679    NaN
680    NaN
681    NaN
682    NaN
683    NaN
684    NaN
685    NaN
686    NaN
687    NaN
688    NaN
689    NaN
690    NaN
691    NaN
692    NaN
693    NaN
694    NaN
695    NaN
696    NaN
697    NaN
698    NaN
699    NaN
700    NaN
701    NaN
702    NaN
703    NaN
704    NaN
705    NaN
706    NaN
707    NaN
708    NaN
709    NaN
710    NaN
711    NaN
712    NaN
713    NaN
714    NaN
715    NaN
716    NaN
717    NaN
718    NaN
719    NaN
720    NaN
721    NaN
722    NaN
723    NaN
724    NaN
725    NaN
726    NaN
727    NaN
728    NaN
729    NaN
730    NaN
731    NaN
732    NaN
733    NaN
734    NaN
735    NaN
736    NaN
737    NaN
738    NaN
739    NaN
740    NaN
741    NaN
742    NaN
743    NaN
744    NaN
745    NaN
746    NaN
747    NaN
748    NaN
749    NaN
750    NaN
751    NaN
752    NaN
753    NaN
754    NaN
755    NaN
756    NaN
757    NaN
758    NaN
759    NaN
760    NaN
761    NaN
762    NaN
763    NaN
764    NaN
765    NaN
766    NaN
767    NaN
768    NaN
769    NaN
770    NaN
771    NaN
772    NaN
773    NaN
774    NaN
775    NaN
776    NaN
777    NaN
778    NaN
779    NaN
780    NaN
781    NaN
782    NaN
783    NaN
784    NaN
785    NaN
786    NaN
787    NaN
788    NaN
789    NaN
790    NaN
791    NaN
792    NaN
793    NaN
794    NaN
795    NaN
796    NaN
797    NaN
798    NaN
799    NaN
800    NaN
801    NaN
802    NaN
803    NaN
804    NaN
805    NaN
806    NaN
807    NaN
808    NaN
809    NaN
810    NaN
811    NaN
812    NaN
813    NaN
814    NaN
815    NaN
816    NaN
817    NaN
818    NaN
819    NaN
820    NaN
821    NaN
822    NaN
823    NaN
824    NaN
825    NaN
826    NaN
827    NaN
828    NaN
829    NaN
830    NaN
831    NaN
832    NaN
833    NaN
834    NaN
835    NaN
836    NaN
837    NaN
838    NaN
839    NaN
840    NaN
841    NaN
842    NaN
843    NaN
844    NaN
845    NaN
846    NaN
847    NaN
848    NaN
849    NaN
850    NaN
851    NaN
852    NaN
853    NaN
854    NaN
855    NaN
856    NaN
857    NaN
858    NaN
859    NaN
860    NaN
861    NaN
862    NaN
863    NaN
864    NaN
865    NaN
866    NaN
867    NaN
868    NaN
869    NaN
870    NaN
871    NaN
872    NaN
873    NaN
874    NaN
875    NaN
876    NaN
877    NaN
878    NaN
879    NaN
880    NaN
881    NaN
882    NaN
883    NaN
884    NaN
885    NaN
886    NaN
887    NaN
888    NaN
889    NaN
890    NaN
891    NaN
892    NaN
893    NaN
894    NaN
895    NaN
896    NaN
897    NaN
898    NaN
899    NaN
900    NaN
901    NaN
902    NaN
903    NaN
904    NaN
905    NaN
906    NaN
907    NaN
908    NaN
909    NaN
910    NaN
911    NaN
912    NaN
913    NaN
914    NaN
915    NaN
916    NaN
917    NaN
918    NaN
919    NaN
920    NaN
921    NaN
922    NaN
923    NaN
924    NaN
925    NaN
926    NaN
927    NaN
928    NaN
929    NaN
930    NaN
931    NaN
932    NaN
933    NaN
934    NaN
935    NaN
936    NaN
937    NaN
938    NaN
939    NaN
940    NaN
941    NaN
942    NaN
943    NaN
944    NaN
945    NaN
946    NaN
947    NaN
948    NaN
949    NaN
950    NaN
951    NaN
952    NaN
953    NaN
954    NaN
955    NaN
956    NaN
957    NaN
958    NaN
959    NaN
960    NaN
961    NaN
962    NaN
963    NaN
964    NaN
965    NaN
966    NaN
967    NaN
968    NaN
969    NaN
970    NaN
971    NaN
972    NaN
973    NaN
974    NaN
975    NaN
976    NaN
977    NaN
978    NaN
979    NaN
980    NaN
981    NaN
982    NaN
983    NaN
984    NaN
985    NaN
986    NaN
987    NaN
988    NaN
989    NaN
990    NaN
991    NaN
992    NaN
993    NaN
994    NaN
995    NaN
996    NaN
997    NaN
998    NaN
999    NaN
1000   NaN
1001   NaN
1002   NaN
1003   NaN
1004   NaN
1005   NaN
1006   NaN
1007   NaN
1008   NaN
1009   NaN
1010   NaN
1011   NaN
1012   NaN
1013   NaN
1014   NaN
1015   NaN
1016   NaN
1017   NaN
1018   NaN
1019   NaN
1020   NaN
1021   NaN
1022   NaN
1023   NaN
1024   NaN
1025   NaN
1026   NaN
1027   NaN
1028   NaN
1029   NaN
1030   NaN
1031   NaN
1032   NaN
1033   NaN
1034   NaN
1035   NaN
1036   NaN
1037   NaN
1038   NaN
1039   NaN
1040   NaN
1041   NaN
1042   NaN
1043   NaN
1044   NaN
1045   NaN
1046   NaN
1047   NaN
1048   NaN
1049   NaN
1050   NaN
1051   NaN
1052   NaN
1053   NaN
1054   NaN
1055   NaN
1056   NaN
1057   NaN
1058   NaN
1059   NaN
1060   NaN
1061   NaN
1062   NaN
1063   NaN
1064   NaN
1065   NaN
1066   NaN
1067   NaN
1068   NaN
1069   NaN
1070   NaN
1071   NaN
1072   NaN
1073   NaN
1074   NaN
1075   NaN
1076   NaN
1077   NaN
1078   NaN
1079   NaN
1080   NaN
1081   NaN
1082   NaN
1083   NaN
1084   NaN
1085   NaN
1086   NaN
1087   NaN
1088   NaN
1089   NaN
1090   NaN
1091   NaN
1092   NaN
1093   NaN
1094   NaN
1095   NaN
1096   NaN
1097   NaN
1098   NaN
1099   NaN
1100   NaN
1101   NaN
1102   NaN
1103   NaN
1104   NaN
1105   NaN
1106   NaN
1107   NaN
1108   NaN
1109   NaN
1110   NaN
1111   NaN
1112   NaN
1113   NaN
1114   NaN
1115   NaN
1116   NaN
1117   NaN
1118   NaN
1119   NaN
1120   NaN
1121   NaN
1122   NaN
1123   NaN
1124   NaN
1125   NaN
1126   NaN
1127   NaN
1128   NaN
1129   NaN
1130   NaN
1131   NaN
1132   NaN
1133   NaN
1134   NaN
1135   NaN
1136   NaN
1137   NaN
1138   NaN
1139   NaN
1140   NaN
1141   NaN
1142   NaN
1143   NaN
1144   NaN
1145   NaN
1146   NaN
1147   NaN
1148   NaN
1149   NaN
1150   NaN
1151   NaN
1152   NaN
1153   NaN
1154   NaN
1155   NaN
1156   NaN
1157   NaN
1158   NaN
1159   NaN
1160   NaN
1161   NaN
1162   NaN
1163   NaN
1164   NaN
1165   NaN
1166   NaN
1167   NaN
1168   NaN
1169   NaN
1170   NaN
1171   NaN
1172   NaN
1173   NaN
1174   NaN
1175   NaN
1176   NaN
1177   NaN
1178   NaN
1179   NaN
1180   NaN
1181   NaN
1182   NaN
1183   NaN
1184   NaN
1185   NaN
1186   NaN
1187   NaN
1188   NaN
1189   NaN
1190   NaN
1191   NaN
1192   NaN
1193   NaN
1194   NaN
1195   NaN
1196   NaN
1197   NaN
1198   NaN
1199   NaN
1200   NaN
1201   NaN
1202   NaN
1203   NaN
1204   NaN
1205   NaN
1206   NaN
1207   NaN
1208   NaN
1209   NaN
1210   NaN
1211   NaN
1212   NaN
1213   NaN
1214   NaN
1215   NaN
1216   NaN
1217   NaN
1218   NaN
1219   NaN
1220   NaN
1221   NaN
1222   NaN
1223   NaN
1224   NaN
1225   NaN
1226   NaN
1227   NaN
1228   NaN
1229   NaN
1230   NaN
1231   NaN
1232   NaN
1233   NaN
1234   NaN
1235   NaN
1236   NaN
1237   NaN
1238   NaN
1239   NaN
1240   NaN
1241   NaN
1242   NaN
1243   NaN
1244   NaN
1245   NaN
1246   NaN
1247   NaN
1248   NaN
1249   NaN
1250   NaN
1251   NaN
1252   NaN
1253   NaN
1254   NaN
1255   NaN
1256   NaN
1257   NaN
1258   NaN
1259   NaN
1260   NaN
1261   NaN
1262   NaN
1263   NaN
1264   NaN
1265   NaN
1266   NaN
1267   NaN
1268   NaN
1269   NaN
1270   NaN
1271   NaN
1272   NaN
1273   NaN
1274   NaN
1275   NaN
1276   NaN
1277   NaN
1278   NaN
1279   NaN
1280   NaN
1281   NaN
1282   NaN
1283   NaN
1284   NaN
1285   NaN
1286   NaN
1287   NaN
1288   NaN
1289   NaN
1290   NaN
1291   NaN
1292   NaN
1293   NaN
1294   NaN
1295   NaN
1296   NaN
1297   NaN
1298   NaN
1299   NaN
1300   NaN
1301   NaN
1302   NaN
1303   NaN
1304   NaN
1305   NaN
1306   NaN
1307   NaN
1308   NaN
1309   NaN
1310   NaN
1311   NaN
1312   NaN
1313   NaN
1314   NaN
1315   NaN
1316   NaN
1317   NaN
1318   NaN
1319   NaN
1320   NaN
1321   NaN
1322   NaN
1323   NaN
1324   NaN
1325   NaN
1326   NaN
1327   NaN
1328   NaN
1329   NaN
1330   NaN
1331   NaN
1332   NaN
1333   NaN
1334   NaN
1335   NaN
1336   NaN
1337   NaN
1338   NaN
1339   NaN
1340   NaN
1341   NaN
1342   NaN
1343   NaN
1344   NaN
1345   NaN
1346   NaN
1347   NaN
1348   NaN
1349   NaN
1350   NaN
1351   NaN
1352   NaN
1353   NaN
1354   NaN
1355   NaN
1356   NaN
1357   NaN
1358   NaN
1359   NaN
1360   NaN
1361   NaN
1362   NaN
1363   NaN
1364   NaN
1365   NaN
1366   NaN
1367   NaN
1368   NaN
1369   NaN
1370   NaN
1371   NaN
1372   NaN
1373   NaN
1374   NaN
1375   NaN
1376   NaN
1377   NaN
1378   NaN
1379   NaN
1380   NaN
1381   NaN
1382   NaN
1383   NaN
1384   NaN
1385   NaN
1386   NaN
1387   NaN
1388   NaN
1389   NaN
1390   NaN
1391   NaN
1392   NaN
1393   NaN
1394   NaN
1395   NaN
1396   NaN
1397   NaN
1398   NaN
1399   NaN
1400   NaN
1401   NaN
1402   NaN
1403   NaN
1404   NaN
1405   NaN
1406   NaN
1407   NaN
1408   NaN
1409   NaN
1410   NaN
1411   NaN
1412   NaN
1413   NaN
1414   NaN
1415   NaN
1416   NaN
1417   NaN
1418   NaN
1419   NaN
1420   NaN
1421   NaN
1422   NaN
1423   NaN
1424   NaN
1425   NaN
1426   NaN
1427   NaN
1428   NaN
1429   NaN
1430   NaN
1431   NaN
1432   NaN
1433   NaN
1434   NaN
1435   NaN
1436   NaN
1437   NaN
1438   NaN
1439   NaN
1440   NaN
1441   NaN
1442   NaN
1443   NaN
1444   NaN
1445   NaN
1446   NaN
1447   NaN
1448   NaN
1449   NaN
1450   NaN
1451   NaN
1452   NaN
1453   NaN
1454   NaN
1455   NaN
1456   NaN
1457   NaN
1458   NaN
1459   NaN
1460   NaN
1461   NaN
1462   NaN
1463   NaN
1464   NaN
1465   NaN
1466   NaN
1467   NaN
1468   NaN
1469   NaN
1470   NaN
1471   NaN
1472   NaN
1473   NaN
1474   NaN
1475   NaN
1476   NaN
1477   NaN
1478   NaN
1479   NaN
1480   NaN
1481   NaN
1482   NaN
1483   NaN
1484   NaN
1485   NaN
1486   NaN
1487   NaN
1488   NaN
1489   NaN
1490   NaN
1491   NaN
1492   NaN
1493   NaN
1494   NaN
1495   NaN
1496   NaN
1497   NaN
1498   NaN
1499   NaN
1500   NaN
1501   NaN
1502   NaN
1503   NaN
1504   NaN
1505   NaN
1506   NaN
1507   NaN
1508   NaN
1509   NaN
1510   NaN
1511   NaN
1512   NaN
1513   NaN
1514   NaN
1515   NaN
1516   NaN
1517   NaN
1518   NaN
1519   NaN
1520   NaN
1521   NaN
1522   NaN
1523   NaN
1524   NaN
1525   NaN
1526   NaN
1527   NaN
1528   NaN
1529   NaN
1530   NaN
1531   NaN
1532   NaN
1533   NaN
1534   NaN
1535   NaN
1536   NaN
1537   NaN
1538   NaN
1539   NaN
1540   NaN
1541   NaN
1542   NaN
1543   NaN
1544   NaN
1545   NaN
1546   NaN
1547   NaN
1548   NaN
1549   NaN
1550   NaN
1551   NaN
1552   NaN
1553   NaN
1554   NaN
1555   NaN
1556   NaN
1557   NaN
1558   NaN
1559   NaN
1560   NaN
1561   NaN
1562   NaN
1563   NaN
1564   NaN
1565   NaN
1566   NaN
1567   NaN
1568   NaN
1569   NaN
1570   NaN
1571   NaN
1572   NaN
1573   NaN
1574   NaN
1575   NaN
1576   NaN
1577   NaN
1578   NaN
1579   NaN
1580   NaN
1581   NaN
1582   NaN
1583   NaN
1584   NaN
1585   NaN
1586   NaN
1587   NaN
1588   NaN
1589   NaN
1590   NaN
1591   NaN
1592   NaN
1593   NaN
1594   NaN
1595   NaN
1596   NaN
1597   NaN
1598   NaN
1599   NaN
1600   NaN
1601   NaN
1602   NaN
1603   NaN
1604   NaN
1605   NaN
1606   NaN
1607   NaN
1608   NaN
1609   NaN
1610   NaN
1611   NaN
1612   NaN
1613   NaN
1614   NaN
1615   NaN
1616   NaN
1617   NaN
1618   NaN
1619   NaN
1620   NaN
1621   NaN
1622   NaN
1623   NaN
1624   NaN
1625   NaN
1626   NaN
1627   NaN
1628   NaN
1629   NaN
1630   NaN
1631   NaN
1632   NaN
1633   NaN
1634   NaN
1635   NaN
1636   NaN
1637   NaN
1638   NaN
1639   NaN
1640   NaN
1641   NaN
1642   NaN
1643   NaN
1644   NaN
1645   NaN
1646   NaN
1647   NaN
1648   NaN
1649   NaN
1650   NaN
1651   NaN
1652   NaN
1653   NaN
1654   NaN
1655   NaN
1656   NaN
1657   NaN
1658   NaN
1659   NaN
1660   NaN
1661   NaN
1662   NaN
1663   NaN
1664   NaN
1665   NaN
1666   NaN
1667   NaN
1668   NaN
1669   NaN
1670   NaN
1671   NaN
1672   NaN
1673   NaN
1674   NaN
1675   NaN
1676   NaN
1677   NaN
1678   NaN
1679   NaN
1680   NaN
1681   NaN
1682   NaN
1683   NaN
1684   NaN
1685   NaN
1686   NaN
1687   NaN
1688   NaN
1689   NaN
1690   NaN
1691   NaN
1692   NaN
1693   NaN
1694   NaN
1695   NaN
1696   NaN
1697   NaN
1698   NaN
1699   NaN
1700   NaN
1701   NaN
1702   NaN
1703   NaN
1704   NaN
1705   NaN
1706   NaN
1707   NaN
1708   NaN
1709   NaN
1710   NaN
1711   NaN
1712   NaN
1713   NaN
1714   NaN
1715   NaN
1716   NaN
1717   NaN
1718   NaN
1719   NaN
1720   NaN
1721   NaN
1722   NaN
1723   NaN
1724   NaN
1725   NaN
1726   NaN
1727   NaN
1728   NaN
1729   NaN
1730   NaN
1731   NaN
1732   NaN
1733   NaN
1734   NaN
1735   NaN
1736   NaN
1737   NaN
1738   NaN
1739   NaN
1740   NaN
1741   NaN
1742   NaN
1743   NaN
1744   NaN
1745   NaN
1746   NaN
1747   NaN
1748   NaN
1749   NaN
1750   NaN
1751   NaN
1752   NaN
1753   NaN
1754   NaN
1755   NaN
1756   NaN
1757   NaN
1758   NaN
1759   NaN
1760   NaN
1761   NaN
1762   NaN
1763   NaN
1764   NaN
1765   NaN
1766   NaN
1767   NaN
1768   NaN
1769   NaN
1770   NaN
1771   NaN
1772   NaN
1773   NaN
1774   NaN
1775   NaN
1776   NaN
1777   NaN
1778   NaN
1779   NaN
1780   NaN
1781   NaN
1782   NaN
1783   NaN
1784   NaN
1785   NaN
1786   NaN
1787   NaN
1788   NaN
1789   NaN
1790   NaN
1791   NaN
1792   NaN
1793   NaN
1794   NaN
1795   NaN
1796   NaN
1797   NaN
1798   NaN
1799   NaN
1800   NaN
1801   NaN
1802   NaN
1803   NaN
1804   NaN
1805   NaN
1806   NaN
1807   NaN
1808   NaN
1809   NaN
1810   NaN
1811   NaN
1812   NaN
1813   NaN
1814   NaN
1815   NaN
1816   NaN
1817   NaN

In [ ]:
# 4.0 Refined Imputation with complete location list

# Define the full list of replacement locations including previously missing ones
add_location = [
    'Chicago, IL', 'Indianapolis, IN', 'Philadelphia, PA', 'Denver, CO',
    'Nashville, TN', 'Las Vegas, NV ', 'Louisville, KY', 'Nortfolk, VA',
    'Fargo, ND', 'Albuquerqu, NM', 'New York, NY', 'San Francisco, CA',
    'Dallas, TX', 'Austin, TX', 'Houston, TX', 'Huntsville, AL','Fort Collins, CO',
    'Salt Lake City, UT', 'Phoenix, AZ', 'Orlando, FL', 'Santa Fe, NW', 'Jackson, MS',
    'Detroit, MI', 'Atlanta, GA', 'Oklahoma, OK', 'New Orleans, LA', 'Columbus, OH'
]

# Identify rows where 'location' is null or just whitespace
bdata['location'] = bdata['location'].replace('', np.nan)
mask = bdata['location'].isna()

# Replace NaN values with random choices from the complete add_location list
if mask.any():
    bdata.loc[mask, 'location'] = [random.choice(add_location) for _ in range(mask.sum())]

# Verify that there are no more nulls in the location column
print(f"Null values remaining in location: {bdata['location'].isna().sum()}")

# Display top 10 location values to verify distribution
display(bdata['location'].value_counts().head(20))

Null values remaining in location: 0

/tmp/ipykernel_21978/2311630163.py:19: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Las Vegas, NV ', 'Atlanta, GA', 'Santa Fe, NW', 'Orlando, FL', 'Columbus, OH', 'Oklahoma, OK', 'Phoenix, AZ', 'Atlanta, GA', 'Las Vegas, NV ', 'Fort Collins, CO', 'Philadelphia, PA', 'Houston, TX', 'Albuquerqu, NM', 'Orlando, FL', 'Chicago, IL', 'San Francisco, CA', 'Indianapolis, IN', 'New Orleans, LA', 'New Orleans, LA', 'Nortfolk, VA', 'Santa Fe, NW', 'Houston, TX', 'Fort Collins, CO', 'Columbus, OH', 'Louisville, KY', 'New York, NY', 'Orlando, FL', 'Phoenix, AZ', 'New Orleans, LA', 'Houston, TX', 'Houston, TX', 'Philadelphia, PA', 'Louisville, KY', 'Chicago, IL', 'Dallas, TX', 'Salt Lake City, UT', 'Austin, TX', 'Nashville, TN', 'New York, NY', 'Louisville, KY', 'Fort Collins, CO', 'Atlanta, GA', 'Fort Collins, CO', 'Louisville, KY', 'Columbus, OH', 'Orlando, FL', 'Nashville, TN', 'Jackson, MS', 'New York, NY', 'New Orleans, LA', 'San Francisco, CA', 'Las Vegas, NV ', 'Houston, TX', 'Huntsville, AL', 'Oklahoma, OK', 'Las Vegas, NV ', 'Detroit, MI', 'Louisville, KY', 'Columbus, OH', 'Nashville, TN', 'Orlando, FL', 'Albuquerqu, NM', 'Huntsville, AL', 'Philadelphia, PA', 'Huntsville, AL', 'Austin, TX', 'Denver, CO', 'Las Vegas, NV ', 'Nortfolk, VA', 'Las Vegas, NV ', 'Orlando, FL', 'Detroit, MI', 'Nortfolk, VA', 'Santa Fe, NW', 'Santa Fe, NW', 'Houston, TX', 'Indianapolis, IN', 'Nashville, TN', 'Louisville, KY', 'New York, NY', 'Fargo, ND', 'Chicago, IL', 'Oklahoma, OK', 'Louisville, KY', 'New York, NY', 'Huntsville, AL', 'Las Vegas, NV ', 'Salt Lake City, UT', 'Philadelphia, PA', 'Columbus, OH', 'Austin, TX', 'Fargo, ND', 'Las Vegas, NV ', 'Jackson, MS', 'New York, NY', 'Atlanta, GA', 'New York, NY', 'Jackson, MS', 'Santa Fe, NW', 'Philadelphia, PA', 'Huntsville, AL', 'Oklahoma, OK', 'Louisville, KY', 'Nashville, TN', 'Philadelphia, PA', 'Atlanta, GA', 'Nortfolk, VA', 'Houston, TX', 'Chicago, IL', 'Austin, TX', 'Phoenix, AZ', 'Santa Fe, NW', 'Philadelphia, PA', 'Denver, CO', 'Indianapolis, IN', 'New Orleans, LA', 'San Francisco, CA', 'Fort Collins, CO', 'Nashville, TN', 'Philadelphia, PA', 'Detroit, MI', 'Albuquerqu, NM', 'Jackson, MS', 'Dallas, TX', 'Detroit, MI', 'Denver, CO', 'Houston, TX', 'Huntsville, AL', 'Columbus, OH', 'Louisville, KY', 'Oklahoma, OK', 'Albuquerqu, NM', 'Louisville, KY', 'Indianapolis, IN', 'Oklahoma, OK', 'Philadelphia, PA', 'Huntsville, AL', 'Indianapolis, IN', 'Huntsville, AL', 'Salt Lake City, UT', 'Oklahoma, OK', 'Oklahoma, OK', 'Denver, CO', 'Phoenix, AZ', 'Detroit, MI', 'San Francisco, CA', 'Philadelphia, PA', 'Orlando, FL', 'Columbus, OH', 'Columbus, OH', 'Chicago, IL', 'Louisville, KY', 'Houston, TX', 'Indianapolis, IN', 'Santa Fe, NW', 'Fargo, ND', 'Nortfolk, VA', 'Phoenix, AZ', 'Phoenix, AZ', 'Orlando, FL', 'Detroit, MI', 'Houston, TX', 'Chicago, IL', 'Denver, CO', 'Jackson, MS', 'San Francisco, CA', 'Detroit, MI', 'Las Vegas, NV ', 'Salt Lake City, UT', 'Denver, CO', 'Denver, CO', 'Nortfolk, VA', 'Orlando, FL', 'Denver, CO', 'Las Vegas, NV ', 'Houston, TX', 'Austin, TX', 'Fort Collins, CO', 'Indianapolis, IN', 'Fort Collins, CO', 'Huntsville, AL', 'Huntsville, AL', 'Columbus, OH', 'Fort Collins, CO', 'Santa Fe, NW', 'Nortfolk, VA', 'Las Vegas, NV ', 'Las Vegas, NV ', 'Oklahoma, OK', 'Santa Fe, NW', 'Huntsville, AL', 'Columbus, OH', 'Dallas, TX', 'Detroit, MI', 'Philadelphia, PA', 'Indianapolis, IN', 'Louisville, KY', 'Fort Collins, CO', 'Nashville, TN', 'Louisville, KY', 'Fargo, ND', 'New Orleans, LA', 'Orlando, FL', 'Huntsville, AL', 'Austin, TX', 'Salt Lake City, UT', 'Chicago, IL', 'Nortfolk, VA', 'Oklahoma, OK', 'Dallas, TX', 'Albuquerqu, NM', 'Huntsville, AL', 'Albuquerqu, NM', 'Albuquerqu, NM', 'Indianapolis, IN', 'Salt Lake City, UT', 'Houston, TX', 'Houston, TX', 'Philadelphia, PA', 'Las Vegas, NV ', 'Indianapolis, IN', 'Oklahoma, OK', 'Orlando, FL', 'Jackson, MS', 'Columbus, OH', 'New Orleans, LA', 'Detroit, MI', 'Chicago, IL', 'Phoenix, AZ', 'Nortfolk, VA', 'Detroit, MI', 'Atlanta, GA', 'Phoenix, AZ', 'Albuquerqu, NM', 'Dallas, TX', 'Dallas, TX', 'Houston, TX', 'Santa Fe, NW', 'Las Vegas, NV ', 'Louisville, KY', 'Salt Lake City, UT', 'Orlando, FL', 'Oklahoma, OK', 'San Francisco, CA', 'Huntsville, AL', 'Huntsville, AL', 'Jackson, MS', 'New York, NY', 'Nashville, TN', 'Atlanta, GA', 'Austin, TX', 'Philadelphia, PA', 'Fort Collins, CO', 'Jackson, MS', 'New York, NY', 'Louisville, KY', 'Atlanta, GA', 'Oklahoma, OK', 'Las Vegas, NV ', 'Oklahoma, OK', 'Detroit, MI', 'Louisville, KY', 'Denver, CO', 'Indianapolis, IN', 'Denver, CO', 'Louisville, KY', 'Houston, TX', 'Orlando, FL', 'Austin, TX', 'Chicago, IL', 'Salt Lake City, UT', 'Nortfolk, VA', 'Columbus, OH', 'Orlando, FL', 'Denver, CO', 'Nortfolk, VA', 'Austin, TX', 'Indianapolis, IN', 'Phoenix, AZ', 'Fort Collins, CO', 'Huntsville, AL', 'Denver, CO', 'New Orleans, LA', 'Philadelphia, PA', 'New Orleans, LA', 'Salt Lake City, UT', 'Oklahoma, OK', 'Indianapolis, IN', 'Jackson, MS', 'Orlando, FL', 'Denver, CO', 'Albuquerqu, NM', 'Dallas, TX', 'San Francisco, CA', 'Nortfolk, VA', 'New Orleans, LA', 'Philadelphia, PA', 'Santa Fe, NW', 'Nashville, TN', 'Dallas, TX', 'New York, NY', 'Dallas, TX', 'Atlanta, GA', 'Columbus, OH', 'Fargo, ND', 'Houston, TX', 'San Francisco, CA', 'Indianapolis, IN', 'Orlando, FL', 'Nashville, TN', 'Indianapolis, IN', 'Nashville, TN', 'Indianapolis, IN', 'Austin, TX', 'Oklahoma, OK', 'New York, NY', 'Austin, TX', 'Huntsville, AL', 'New Orleans, LA', 'Columbus, OH', 'Houston, TX', 'Chicago, IL', 'Chicago, IL', 'Indianapolis, IN', 'Santa Fe, NW', 'Phoenix, AZ', 'New York, NY', 'Louisville, KY', 'Huntsville, AL', 'Salt Lake City, UT', 'Austin, TX', 'Las Vegas, NV ', 'Orlando, FL', 'Houston, TX', 'Fort Collins, CO', 'Fargo, ND', 'Denver, CO', 'Phoenix, AZ', 'Columbus, OH', 'Austin, TX', 'Atlanta, GA', 'Houston, TX', 'Oklahoma, OK', 'Indianapolis, IN', 'New Orleans, LA', 'Austin, TX', 'Chicago, IL', 'Nortfolk, VA', 'Huntsville, AL', 'Jackson, MS', 'Atlanta, GA', 'Denver, CO', 'Oklahoma, OK', 'Salt Lake City, UT', 'Jackson, MS', 'Oklahoma, OK', 'Atlanta, GA', 'Fort Collins, CO', 'Jackson, MS', 'Louisville, KY', 'Chicago, IL', 'Columbus, OH', 'New York, NY', 'Salt Lake City, UT', 'Atlanta, GA', 'Santa Fe, NW', 'Santa Fe, NW', 'Philadelphia, PA', 'Fort Collins, CO', 'Fort Collins, CO', 'Santa Fe, NW', 'Chicago, IL', 'Santa Fe, NW', 'Nashville, TN', 'Nortfolk, VA', 'Salt Lake City, UT', 'New Orleans, LA', 'Nashville, TN', 'Atlanta, GA', 'Las Vegas, NV ', 'Las Vegas, NV ', 'Orlando, FL', 'Fort Collins, CO', 'Chicago, IL', 'Santa Fe, NW', 'Phoenix, AZ', 'Atlanta, GA', 'Huntsville, AL', 'New Orleans, LA', 'Detroit, MI', 'Salt Lake City, UT', 'Huntsville, AL', 'Denver, CO', 'Houston, TX', 'Huntsville, AL', 'Louisville, KY', 'Philadelphia, PA', 'Santa Fe, NW', 'Phoenix, AZ', 'Huntsville, AL', 'Oklahoma, OK', 'Louisville, KY', 'New Orleans, LA', 'Jackson, MS', 'Fort Collins, CO', 'Atlanta, GA', 'Nashville, TN', 'Austin, TX', 'Las Vegas, NV ', 'Nortfolk, VA', 'Chicago, IL', 'Atlanta, GA', 'Denver, CO', 'Detroit, MI', 'Austin, TX', 'Philadelphia, PA', 'Atlanta, GA', 'New York, NY', 'Columbus, OH', 'San Francisco, CA', 'Nashville, TN', 'Detroit, MI', 'Las Vegas, NV ', 'Nortfolk, VA', 'Louisville, KY', 'Chicago, IL', 'San Francisco, CA', 'Oklahoma, OK', 'Atlanta, GA', 'Detroit, MI', 'Nashville, TN', 'Louisville, KY', 'Phoenix, AZ', 'Huntsville, AL', 'Houston, TX', 'Salt Lake City, UT', 'Chicago, IL', 'Huntsville, AL', 'Philadelphia, PA', 'Nashville, TN', 'Indianapolis, IN', 'Atlanta, GA', 'Santa Fe, NW', 'Fargo, ND', 'Albuquerqu, NM', 'New Orleans, LA', 'Columbus, OH', 'Chicago, IL', 'Huntsville, AL', 'Fargo, ND', 'Santa Fe, NW', 'Albuquerqu, NM', 'Orlando, FL', 'Fargo, ND', 'San Francisco, CA', 'Huntsville, AL', 'Huntsville, AL', 'Huntsville, AL', 'Jackson, MS', 'Indianapolis, IN', 'New Orleans, LA', 'Oklahoma, OK', 'Nortfolk, VA', 'Oklahoma, OK', 'Fort Collins, CO', 'Oklahoma, OK', 'Austin, TX', 'Fort Collins, CO', 'Nashville, TN', 'New Orleans, LA', 'New York, NY', 'Detroit, MI', 'Jackson, MS', 'Orlando, FL', 'Fort Collins, CO', 'San Francisco, CA', 'Chicago, IL', 'Indianapolis, IN', 'New York, NY', 'New Orleans, LA', 'San Francisco, CA', 'Oklahoma, OK', 'Nashville, TN', 'Salt Lake City, UT', 'Philadelphia, PA', 'Orlando, FL', 'Fargo, ND', 'Fargo, ND', 'Nortfolk, VA', 'Detroit, MI', 'Jackson, MS', 'Detroit, MI', 'Austin, TX', 'San Francisco, CA', 'Las Vegas, NV ', 'Atlanta, GA', 'New Orleans, LA', 'Phoenix, AZ', 'Louisville, KY', 'Huntsville, AL', 'Philadelphia, PA', 'Fargo, ND', 'Huntsville, AL', 'Louisville, KY', 'Oklahoma, OK', 'Columbus, OH', 'Columbus, OH', 'Nortfolk, VA', 'Detroit, MI', 'Salt Lake City, UT', 'Atlanta, GA', 'Fort Collins, CO', 'Dallas, TX', 'Phoenix, AZ', 'Chicago, IL', 'Orlando, FL', 'Orlando, FL', 'Phoenix, AZ', 'San Francisco, CA', 'Las Vegas, NV ', 'Dallas, TX', 'Austin, TX', 'Columbus, OH', 'Dallas, TX', 'Nortfolk, VA', 'Austin, TX', 'Atlanta, GA', 'Austin, TX', 'Chicago, IL', 'Columbus, OH', 'Fargo, ND', 'Columbus, OH', 'Nortfolk, VA', 'Dallas, TX', 'Fargo, ND', 'Jackson, MS', 'Santa Fe, NW', 'Huntsville, AL', 'Indianapolis, IN', 'New York, NY', 'Fort Collins, CO', 'Phoenix, AZ', 'Salt Lake City, UT', 'Albuquerqu, NM', 'Detroit, MI', 'Phoenix, AZ', 'Huntsville, AL', 'Louisville, KY', 'Louisville, KY', 'Salt Lake City, UT', 'Oklahoma, OK', 'Atlanta, GA', 'New York, NY', 'Huntsville, AL', 'Jackson, MS', 'Denver, CO', 'Albuquerqu, NM', 'Orlando, FL', 'Chicago, IL', 'Orlando, FL', 'Columbus, OH', 'Houston, TX', 'Fargo, ND', 'New York, NY', 'Fargo, ND', 'Louisville, KY', 'Santa Fe, NW', 'Atlanta, GA', 'Detroit, MI', 'Philadelphia, PA', 'Nashville, TN', 'Austin, TX', 'Austin, TX', 'Denver, CO', 'Philadelphia, PA', 'Indianapolis, IN', 'Austin, TX', 'Santa Fe, NW', 'Dallas, TX', 'Austin, TX', 'Denver, CO', 'Nashville, TN', 'Oklahoma, OK', 'Oklahoma, OK', 'Salt Lake City, UT', 'Columbus, OH', 'Denver, CO', 'Huntsville, AL', 'Oklahoma, OK', 'New Orleans, LA', 'Detroit, MI', 'Santa Fe, NW', 'Atlanta, GA', 'Salt Lake City, UT', 'New Orleans, LA', 'Philadelphia, PA', 'Chicago, IL', 'Orlando, FL', 'Las Vegas, NV ', 'Phoenix, AZ', 'Indianapolis, IN', 'Chicago, IL', 'Atlanta, GA', 'Chicago, IL', 'Detroit, MI', 'Orlando, FL', 'Chicago, IL', 'Austin, TX', 'Las Vegas, NV ', 'Atlanta, GA', 'Atlanta, GA', 'San Francisco, CA', 'Louisville, KY', 'Dallas, TX', 'Detroit, MI', 'San Francisco, CA', 'Fort Collins, CO', 'Nortfolk, VA', 'Louisville, KY', 'Louisville, KY', 'Austin, TX', 'Detroit, MI', 'New Orleans, LA', 'Santa Fe, NW', 'Jackson, MS', 'Denver, CO', 'Denver, CO', 'Oklahoma, OK', 'Orlando, FL', 'Indianapolis, IN', 'Philadelphia, PA', 'Salt Lake City, UT', 'Las Vegas, NV ', 'Las Vegas, NV ', 'Salt Lake City, UT', 'Atlanta, GA', 'New Orleans, LA', 'Louisville, KY', 'Chicago, IL', 'Huntsville, AL', 'Houston, TX', 'Indianapolis, IN', 'Chicago, IL', 'New Orleans, LA', 'Phoenix, AZ', 'Albuquerqu, NM', 'Fargo, ND', 'Austin, TX', 'Atlanta, GA', 'Salt Lake City, UT', 'Las Vegas, NV ', 'Chicago, IL', 'Nashville, TN', 'Huntsville, AL', 'Fargo, ND', 'Louisville, KY', 'Columbus, OH', 'Orlando, FL', 'Columbus, OH', 'Houston, TX', 'Salt Lake City, UT', 'Nortfolk, VA', 'Dallas, TX', 'Orlando, FL', 'Columbus, OH', 'Philadelphia, PA', 'San Francisco, CA', 'Phoenix, AZ', 'Dallas, TX', 'Orlando, FL', 'Chicago, IL', 'Las Vegas, NV ', 'Orlando, FL', 'Orlando, FL', 'Las Vegas, NV ', 'Phoenix, AZ', 'Chicago, IL', 'Louisville, KY', 'Detroit, MI', 'Phoenix, AZ', 'Dallas, TX', 'Dallas, TX', 'Nortfolk, VA', 'Indianapolis, IN', 'Santa Fe, NW', 'San Francisco, CA', 'Orlando, FL', 'Louisville, KY', 'Huntsville, AL', 'Oklahoma, OK', 'New York, NY', 'Huntsville, AL', 'Oklahoma, OK', 'Las Vegas, NV ', 'Detroit, MI', 'Philadelphia, PA', 'Louisville, KY', 'Columbus, OH', 'Indianapolis, IN', 'Phoenix, AZ', 'Jackson, MS', 'Nashville, TN', 'Salt Lake City, UT', 'Denver, CO', 'Nortfolk, VA', 'Denver, CO', 'New York, NY', 'Nashville, TN', 'Philadelphia, PA', 'Denver, CO', 'Fort Collins, CO', 'Houston, TX', 'Houston, TX', 'Las Vegas, NV ', 'Albuquerqu, NM', 'San Francisco, CA', 'Santa Fe, NW', 'Louisville, KY', 'Las Vegas, NV ', 'New Orleans, LA', 'Columbus, OH', 'Detroit, MI', 'Philadelphia, PA', 'San Francisco, CA', 'Atlanta, GA', 'Nashville, TN', 'Atlanta, GA', 'Dallas, TX', 'Chicago, IL', 'Indianapolis, IN', 'Phoenix, AZ', 'Atlanta, GA', 'Albuquerqu, NM', 'Jackson, MS', 'Fort Collins, CO', 'Nashville, TN', 'Nortfolk, VA', 'Dallas, TX', 'Louisville, KY', 'Detroit, MI', 'Santa Fe, NW', 'Houston, TX', 'Nashville, TN', 'Fort Collins, CO', 'Atlanta, GA', 'Austin, TX', 'Dallas, TX', 'Houston, TX', 'Louisville, KY', 'Oklahoma, OK', 'Phoenix, AZ', 'Huntsville, AL', 'Louisville, KY', 'Detroit, MI', 'Houston, TX', 'Jackson, MS', 'Chicago, IL', 'Fargo, ND', 'Jackson, MS', 'Nortfolk, VA', 'Indianapolis, IN', 'Denver, CO', 'Detroit, MI', 'Detroit, MI', 'San Francisco, CA', 'Columbus, OH', 'Atlanta, GA', 'Las Vegas, NV ', 'Dallas, TX', 'Albuquerqu, NM', 'Austin, TX', 'Denver, CO', 'Orlando, FL', 'Austin, TX', 'Louisville, KY', 'New Orleans, LA', 'New York, NY', 'Louisville, KY', 'New Orleans, LA', 'Dallas, TX', 'Detroit, MI', 'Nortfolk, VA', 'Dallas, TX', 'San Francisco, CA', 'Nashville, TN', 'Nortfolk, VA', 'Nortfolk, VA', 'Houston, TX', 'Austin, TX', 'Nortfolk, VA', 'Fargo, ND', 'Nortfolk, VA', 'Albuquerqu, NM', 'Houston, TX', 'Louisville, KY', 'Fort Collins, CO', 'San Francisco, CA', 'Houston, TX', 'Fort Collins, CO', 'Nashville, TN', 'New York, NY', 'Santa Fe, NW', 'Huntsville, AL', 'Detroit, MI', 'Houston, TX', 'Santa Fe, NW', 'Dallas, TX', 'Nashville, TN', 'Detroit, MI', 'Santa Fe, NW', 'Phoenix, AZ', 'Houston, TX', 'Las Vegas, NV ', 'Nortfolk, VA', 'Huntsville, AL', 'Austin, TX', 'Columbus, OH', 'Philadelphia, PA', 'New York, NY', 'Fargo, ND', 'Atlanta, GA', 'Oklahoma, OK', 'Indianapolis, IN', 'Chicago, IL', 'Atlanta, GA', 'Dallas, TX', 'Indianapolis, IN', 'Santa Fe, NW', 'Dallas, TX', 'Austin, TX', 'Atlanta, GA', 'Dallas, TX', 'Austin, TX', 'Houston, TX', 'Phoenix, AZ', 'San Francisco, CA', 'Orlando, FL', 'Denver, CO', 'Santa Fe, NW', 'Fort Collins, CO', 'Fargo, ND', 'Columbus, OH', 'Orlando, FL', 'Jackson, MS', 'Las Vegas, NV ', 'Nortfolk, VA', 'Austin, TX', 'Nashville, TN', 'Fargo, ND', 'New York, NY', 'Las Vegas, NV ', 'Phoenix, AZ', 'Oklahoma, OK', 'Dallas, TX', 'Detroit, MI', 'Philadelphia, PA', 'Jackson, MS', 'Louisville, KY', 'New York, NY', 'Salt Lake City, UT', 'Louisville, KY', 'Albuquerqu, NM', 'Austin, TX', 'Detroit, MI', 'Philadelphia, PA', 'Phoenix, AZ', 'Austin, TX', 'Detroit, MI', 'Houston, TX', 'Salt Lake City, UT', 'Phoenix, AZ', 'Jackson, MS', 'Fort Collins, CO', 'Salt Lake City, UT', 'Louisville, KY', 'Chicago, IL', 'Houston, TX', 'Philadelphia, PA', 'Austin, TX', 'Huntsville, AL', 'Las Vegas, NV ', 'Santa Fe, NW', 'Columbus, OH', 'Philadelphia, PA', 'Columbus, OH', 'New York, NY', 'Phoenix, AZ', 'Jackson, MS', 'Santa Fe, NW', 'Nortfolk, VA', 'Salt Lake City, UT', 'Salt Lake City, UT', 'Nortfolk, VA', 'Nortfolk, VA', 'Dallas, TX', 'Albuquerqu, NM', 'Albuquerqu, NM', 'Houston, TX', 'San Francisco, CA', 'New York, NY', 'Austin, TX', 'Oklahoma, OK', 'Columbus, OH', 'Detroit, MI', 'Jackson, MS', 'Houston, TX', 'New Orleans, LA', 'Atlanta, GA', 'New Orleans, LA', 'Jackson, MS', 'Oklahoma, OK', 'Orlando, FL', 'Huntsville, AL', 'Salt Lake City, UT', 'Fort Collins, CO', 'Atlanta, GA', 'Denver, CO', 'Detroit, MI', 'Fort Collins, CO', 'Fargo, ND', 'Dallas, TX', 'New Orleans, LA', 'Albuquerqu, NM', 'Fargo, ND', 'Columbus, OH', 'Philadelphia, PA', 'New York, NY', 'Indianapolis, IN', 'Denver, CO', 'San Francisco, CA', 'Santa Fe, NW', 'Chicago, IL', 'Nashville, TN', 'Oklahoma, OK', 'Columbus, OH', 'Fargo, ND', 'Austin, TX', 'Fort Collins, CO', 'Denver, CO', 'Las Vegas, NV ', 'Atlanta, GA', 'New Orleans, LA', 'Nashville, TN', 'Indianapolis, IN', 'Austin, TX', 'Phoenix, AZ', 'Chicago, IL', 'Indianapolis, IN', 'Santa Fe, NW', 'Louisville, KY', 'New York, NY', 'Chicago, IL', 'Chicago, IL', 'Phoenix, AZ', 'Oklahoma, OK', 'Columbus, OH', 'Detroit, MI', 'Phoenix, AZ', 'Chicago, IL', 'Columbus, OH', 'Austin, TX', 'Santa Fe, NW', 'Fargo, ND', 'Chicago, IL', 'Santa Fe, NW', 'Louisville, KY', 'Nortfolk, VA', 'Phoenix, AZ', 'Nashville, TN', 'Las Vegas, NV ', 'Indianapolis, IN', 'Houston, TX', 'San Francisco, CA', 'Louisville, KY', 'Austin, TX', 'Indianapolis, IN', 'Fargo, ND', 'Santa Fe, NW', 'Salt Lake City, UT', 'Fort Collins, CO', 'Columbus, OH', 'Atlanta, GA', 'Louisville, KY', 'Chicago, IL', 'Detroit, MI', 'San Francisco, CA', 'Fargo, ND', 'Detroit, MI', 'Austin, TX', 'Santa Fe, NW', 'Nashville, TN', 'Albuquerqu, NM', 'Santa Fe, NW', 'Las Vegas, NV ', 'Las Vegas, NV ', 'Denver, CO', 'Phoenix, AZ', 'New Orleans, LA', 'New York, NY', 'Huntsville, AL', 'Jackson, MS', 'San Francisco, CA', 'Fargo, ND', 'Dallas, TX', 'Houston, TX', 'Houston, TX', 'Jackson, MS', 'Huntsville, AL', 'Columbus, OH', 'San Francisco, CA', 'Orlando, FL', 'Huntsville, AL', 'New York, NY', 'New York, NY', 'Orlando, FL', 'Chicago, IL', 'Chicago, IL', 'Austin, TX', 'Nashville, TN', 'Santa Fe, NW', 'Las Vegas, NV ', 'Louisville, KY', 'Phoenix, AZ', 'Fort Collins, CO', 'Louisville, KY', 'Fargo, ND', 'Detroit, MI', 'Austin, TX', 'Santa Fe, NW', 'Louisville, KY', 'Oklahoma, OK', 'New Orleans, LA', 'Nashville, TN', 'Oklahoma, OK', 'Nortfolk, VA', 'Fort Collins, CO', 'Chicago, IL', 'New Orleans, LA', 'Fargo, ND', 'Albuquerqu, NM', 'Jackson, MS', 'Orlando, FL', 'Fargo, ND', 'Phoenix, AZ', 'Houston, TX', 'Huntsville, AL', 'Phoenix, AZ', 'Austin, TX', 'Orlando, FL', 'Salt Lake City, UT', 'New York, NY', 'Fargo, ND', 'Detroit, MI', 'Santa Fe, NW', 'Phoenix, AZ', 'Huntsville, AL', 'Nortfolk, VA', 'Jackson, MS', 'Chicago, IL', 'Santa Fe, NW', 'Denver, CO', 'Huntsville, AL', 'Jackson, MS', 'New Orleans, LA', 'Fort Collins, CO', 'Salt Lake City, UT', 'Fort Collins, CO', 'Houston, TX', 'Philadelphia, PA', 'Jackson, MS', 'Indianapolis, IN', 'Las Vegas, NV ', 'Indianapolis, IN', 'Santa Fe, NW', 'Detroit, MI', 'Jackson, MS', 'Oklahoma, OK', 'Las Vegas, NV ', 'New Orleans, LA', 'Salt Lake City, UT', 'Philadelphia, PA', 'Santa Fe, NW', 'Las Vegas, NV ', 'Orlando, FL', 'Houston, TX', 'Albuquerqu, NM', 'New Orleans, LA', 'Oklahoma, OK', 'Nortfolk, VA', 'Philadelphia, PA', 'New York, NY', 'Houston, TX', 'Philadelphia, PA', 'Huntsville, AL', 'Nashville, TN', 'Phoenix, AZ', 'Chicago, IL', 'Detroit, MI', 'Detroit, MI', 'Louisville, KY', 'Dallas, TX', 'Chicago, IL', 'Nortfolk, VA', 'Nortfolk, VA', 'New York, NY', 'Salt Lake City, UT', 'Albuquerqu, NM', 'Salt Lake City, UT', 'Louisville, KY', 'Indianapolis, IN', 'Nortfolk, VA', 'Salt Lake City, UT', 'Phoenix, AZ', 'Oklahoma, OK', 'Fort Collins, CO', 'Atlanta, GA', 'New Orleans, LA', 'Santa Fe, NW', 'Albuquerqu, NM', 'Las Vegas, NV ', 'New York, NY', 'Albuquerqu, NM', 'Phoenix, AZ', 'Austin, TX', 'New Orleans, LA', 'Louisville, KY', 'Phoenix, AZ', 'Atlanta, GA', 'Nashville, TN', 'Columbus, OH', 'Atlanta, GA', 'Las Vegas, NV ', 'Oklahoma, OK', 'Atlanta, GA', 'Albuquerqu, NM', 'New Orleans, LA', 'Las Vegas, NV ', 'Austin, TX', 'Nashville, TN', 'Orlando, FL', 'San Francisco, CA', 'Denver, CO', 'Austin, TX', 'Austin, TX', 'Huntsville, AL', 'Fort Collins, CO', 'Louisville, KY', 'Jackson, MS', 'New Orleans, LA', 'Jackson, MS', 'Jackson, MS', 'Nashville, TN', 'Nortfolk, VA', 'Columbus, OH', 'Detroit, MI', 'Columbus, OH', 'Phoenix, AZ', 'Huntsville, AL', 'Nashville, TN', 'New York, NY', 'Oklahoma, OK', 'Philadelphia, PA', 'Philadelphia, PA', 'Santa Fe, NW', 'Santa Fe, NW', 'Houston, TX', 'Indianapolis, IN', 'Fargo, ND', 'Orlando, FL', 'Huntsville, AL', 'Albuquerqu, NM', 'Nashville, TN', 'Indianapolis, IN', 'Fargo, ND', 'Detroit, MI', 'Atlanta, GA', 'Indianapolis, IN', 'Las Vegas, NV ', 'Chicago, IL', 'Las Vegas, NV ', 'Jackson, MS', 'Columbus, OH', 'Salt Lake City, UT', 'Las Vegas, NV ', 'Orlando, FL', 'Nortfolk, VA', 'Atlanta, GA', 'Philadelphia, PA', 'Oklahoma, OK', 'Louisville, KY', 'Salt Lake City

location
Louisville, KY        112
Chicago, IL           108
Huntsville, AL        108
Nortfolk, VA          106
Columbus, OH          102
Las Vegas, NV         101
Detroit, MI            99
Austin, TX             98
Atlanta, GA            95
Oklahoma, OK           95
Houston, TX            94
Fargo, ND              93
Santa Fe, NW           92
Dallas, TX             92
Jackson, MS            91
Phoenix, AZ            91
Indianapolis, IN       90
New Orleans, LA        90
Salt Lake City, UT     87
New York, NY           86
Name: count, dtype: int64

In [ ]:
# Check the Tail of the dataset
bdata['location'].tail(250)

2250      Indianapolis, IN
2251           Chicago, IL
2252        Louisville, KY
2253           Phoenix, AZ
2254          Oklahoma, OK
2255          Columbus, OH
2256            Denver, CO
2257          New York, NY
2258          New York, NY
2259        Huntsville, AL
2260           Chicago, IL
2261           Atlanta, GA
2262            Dallas, TX
2263          Oklahoma, OK
2264          Columbus, OH
2265          Oklahoma, OK
2266    Salt Lake City, UT
2267     San Francisco, CA
2268          Columbus, OH
2269     San Francisco, CA
2270          New York, NY
2271      Indianapolis, IN
2272           Jackson, MS
2273          New York, NY
2274        Huntsville, AL
2275             Fargo, ND
2276          Santa Fe, NW
2277        Huntsville, AL
2278           Orlando, FL
2279        Albuquerqu, NM
2280           Orlando, FL
2281           Orlando, FL
2282    Salt Lake City, UT
2283        Huntsville, AL
2284          Columbus, OH
2285        Huntsville, AL
2286           Chicago, IL
2287           Atlanta, GA
2288          Santa Fe, NW
2289     San Francisco, CA
2290          New York, NY
2291           Chicago, IL
2292           Houston, TX
2293           Jackson, MS
2294         Nashville, TN
2295          Nortfolk, VA
2296          Columbus, OH
2297          Santa Fe, NW
2298      Indianapolis, IN
2299            Austin, TX
2300           Phoenix, AZ
2301          Oklahoma, OK
2302     San Francisco, CA
2303        Huntsville, AL
2304      Fort Collins, CO
2305        Las Vegas, NV
2306        Las Vegas, NV
2307        Las Vegas, NV
2308        Albuquerqu, NM
2309    Salt Lake City, UT
2310           Chicago, IL
2311      Indianapolis, IN
2312        Huntsville, AL
2313          Oklahoma, OK
2314          Columbus, OH
2315     San Francisco, CA
2316           Atlanta, GA
2317        Huntsville, AL
2318     San Francisco, CA
2319      Indianapolis, IN
2320    Salt Lake City, UT
2321           Detroit, MI
2322            Austin, TX
2323          Santa Fe, NW
2324            Austin, TX
2325     San Francisco, CA
2326    Salt Lake City, UT
2327           Chicago, IL
2328            Dallas, TX
2329          Oklahoma, OK
2330      Philadelphia, PA
2331          Santa Fe, NW
2332          Columbus, OH
2333           Orlando, FL
2334      Indianapolis, IN
2335       New Orleans, LA
2336            Dallas, TX
2337          New York, NY
2338           Chicago, IL
2339           Houston, TX
2340             Fargo, ND
2341           Houston, TX
2342           Atlanta, GA
2343           Chicago, IL
2344        Las Vegas, NV
2345           Chicago, IL
2346        Albuquerqu, NM
2347          Oklahoma, OK
2348    Salt Lake City, UT
2349      Philadelphia, PA
2350            Dallas, TX
2351           Phoenix, AZ
2352            Austin, TX
2353            Austin, TX
2354        Louisville, KY
2355           Orlando, FL
2356           Detroit, MI
2357          Nortfolk, VA
2358           Houston, TX
2359        Louisville, KY
2360          Columbus, OH
2361           Orlando, FL
2362            Austin, TX
2363       New Orleans, LA
2364           Detroit, MI
2365             Fargo, ND
2366            Denver, CO
2367           Detroit, MI
2368          Santa Fe, NW
2369     San Francisco, CA
2370           Houston, TX
2371       New Orleans, LA
2372         Nashville, TN
2373    Salt Lake City, UT
2374            Denver, CO
2375           Detroit, MI
2376     San Francisco, CA
2377            Dallas, TX
2378      Indianapolis, IN
2379     San Francisco, CA
2380             Fargo, ND
2381        Albuquerqu, NM
2382            Denver, CO
2383       New Orleans, LA
2384          Oklahoma, OK
2385            Dallas, TX
2386          Santa Fe, NW
2387        Albuquerqu, NM
2388           Jackson, MS
2389        Huntsville, AL
2390         Nashville, TN
2391           Orlando, FL
2392            Dallas, TX
2393     San Francisco, CA
2394           Detroit, MI
2395            Denver, CO
2396        Louisville, KY
2397          Columbus, OH
2398          Columbus, OH
2399    Salt Lake City, UT
2400        Huntsville, AL
2401        Louisville, KY
2402     San Francisco, CA
2403      Fort Collins, CO
2404         Nashville, TN
2405           Detroit, MI
2406            Dallas, TX
2407           Chicago, IL
2408        Las Vegas, NV
2409             Fargo, ND
2410           Phoenix, AZ
2411           Chicago, IL
2412      Fort Collins, CO
2413     San Francisco, CA
2414       New Orleans, LA
2415           Phoenix, AZ
2416           Phoenix, AZ
2417        Albuquerqu, NM
2418    Salt Lake City, UT
2419     San Francisco, CA
2420          Nortfolk, VA
2421           Jackson, MS
2422          New York, NY
2423          Oklahoma, OK
2424        Albuquerqu, NM
2425          Columbus, OH
2426        Las Vegas, NV
2427            Austin, TX
2428           Phoenix, AZ
2429          Nortfolk, VA
2430            Dallas, TX
2431           Phoenix, AZ
2432        Huntsville, AL
2433            Dallas, TX
2434            Dallas, TX
2435             Fargo, ND
2436      Philadelphia, PA
2437          Columbus, OH
2438           Houston, TX
2439          Columbus, OH
2440        Albuquerqu, NM
2441       New Orleans, LA
2442      Indianapolis, IN
2443            Dallas, TX
2444        Albuquerqu, NM
2445           Detroit, MI
2446           Detroit, MI
2447           Atlanta, GA
2448         Nashville, TN
2449           Chicago, IL
2450          Oklahoma, OK
2451          New York, NY
2452             Fargo, ND
2453            Dallas, TX
2454        Albuquerqu, NM
2455          Columbus, OH
2456            Dallas, TX
2457          Columbus, OH
2458          Santa Fe, NW
2459          New York, NY
2460          Columbus, OH
2461          Nortfolk, VA
2462        Albuquerqu, NM
2463        Louisville, KY
2464            Denver, CO
2465           Houston, TX
2466            Dallas, TX
2467            Dallas, TX
2468    Salt Lake City, UT
2469           Houston, TX
2470         Nashville, TN
2471          New York, NY
2472             Fargo, ND
2473    Salt Lake City, UT
2474        Las Vegas, NV
2475          Nortfolk, VA
2476           Orlando, FL
2477           Detroit, MI
2478          Oklahoma, OK
2479        Huntsville, AL
2480          Oklahoma, OK
2481          New York, NY
2482        Albuquerqu, NM
2483          New York, NY
2484           Houston, TX
2485           Detroit, MI
2486            Denver, CO
2487        Albuquerqu, NM
2488            Dallas, TX
2489           Jackson, MS
2490           Atlanta, GA
2491        Albuquerqu, NM
2492           Detroit, MI
2493          Nortfolk, VA
2494          Oklahoma, OK
2495           Chicago, IL
2496      Indianapolis, IN
2497          Nortfolk, VA
2498           Jackson, MS
2499           Orlando, FL
Name: location, dtype: object

## Problem 2: Remove Special Character from Job Title rows

In [ ]:
# Before Cleaning
bdata['job_title'].head(10)

0                       Sr.
1              DATA ANALYST
2              Data Analyst
3    Marketing Data Analyst
4           Data Analyst II
5       Senior Data Analyst
6       Senior Data Analyst
7          Sr. Data Analyst
8    Marketing Data Analyst
9              DATA ANALYST
Name: job_title, dtype: object

## Problem 3: Review job title column

Reviewing the `job_title`, found a couple of issue. It hasn't beeen cleaned
 1. Some job title are in all Caps `DATA ANALYST`
 2. Missing the actual job and just have the experince level `Sr.`

In [ ]:
# Before Cleaning
bdata.head(10)

,job_title,salary,location,remote_location,company_size,experience_level,employment_type,skills,experience_level_value,company_size_value,employment_type_value
0,Sr.,0,"Las Vegas, NV",C2C,Large,Excel;R,None,False,0,3,0
1,DATA ANALYST,65000,"Atlanta, GA",No,Huge,Sr,Freelance,"AWS, Python, Google Cloud, Power BI",3,4,6
2,Data Analyst,65000,"Santa Fe, NW",1,Large,Pr,Contract,"Python, , Excel",4,3,4
3,Marketing Data Analyst,0,"Orlando, FL",Yes,Unknown,None,Regular,"Tableau , Azure , R , Python ,",0,0,3
4,Data Analyst II,65000,"Columbus, OH",Hybrid,Unknown,Jr,Part-time,"Python , Tableau , Azure , Google Cloud , SQL",1,0,2
5,Senior Data Analyst,0,"Oklahoma, OK",Partial,Startup,Mi,Part-time,"Excel, R",2,1,2
6,Senior Data Analyst,95000,"Phoenix, AZ",False,Startup,Pr,Full-time,"Python, AWS",4,1,1
7,Sr. Data Analyst,65000,"Atlanta, GA",1,Medium,Jr,Regular,"Tableau, Power BI, Python, , AWS",1,2,3
8,Marketing Data Analyst,120000,"Las Vegas, NV",0,Large,Mi,Full-time,"Google Cloud, Azure, Excel, Python, SQL",2,3,1
9,DATA ANALYST,95000.0,"Fort Collins, CO",False,Unknown,Mi,Temporary,", Azure, Excel, SQL, R",2,0,5

In [ ]:
# View All the Unique entry that need to be clean and replaced
bdata['job_title'].unique()

array(['Sr.Data Analyst', 'Data Analyst', 'Marketing Data Analyst',
       'Data Analyst II', 'Senior Data Analyst', 'Sr. Data Analyst',
       'Product Data Analyst', 'BI Analyst', 'Junior Data Analyst',
       'Data Analytics Specialist', 'Jr. Data Analyst'], dtype=object)

In [ ]:
# Create non job title function to clean `job_title` column
def non_job_title(df_to_clean):
  # Create non title set to replace
  non_job_title_set = {
      'Data Analyst - Remote',
      "['New York, NY', 'San Francisco, CA', 'Dallas, TX', 'Remote', 'US', 'London, UK', 'Austin, TX', 'Anywhere', nan, 'Houston,TX', 'Huntsville,AL']",
      '85k - 105k', 'Unknown', 'C2C', "['Google Cloud', 'Power BI']", 'Power BI, SQL, Google Cloud, Azure, Python',
      'Senior', 'Contract', '0', 'EN', 'Freelance', 'Negotiable','Temporary',
      'Hybrid', 'FT', 'Temporarily Remote', 'nan', '0-2 years', np.nan # Added np.nan for actual NaN values
  }

  # Find all non job title in the set and replace them with 'Data Analyst`
  df_to_clean['job_title'] = df_to_clean['job_title'].replace(list(non_job_title_set), 'Data Analyst')
  return df_to_clean

In [ ]:
# Run the function
bdata = non_job_title(bdata)

In [ ]:
# Run .unique again - this time we want only the job title
bdata['job_title'].unique()

0                Sr.Data Analyst
1                   Data Analyst
2                   Data Analyst
3         Marketing Data Analyst
4                Data Analyst II
5            Senior Data Analyst
6            Senior Data Analyst
7               Sr. Data Analyst
8         Marketing Data Analyst
9                   Data Analyst
10          Product Data Analyst
11        Marketing Data Analyst
12                    BI Analyst
13                  Data Analyst
14                  Data Analyst
15           Junior Data Analyst
16                  Data Analyst
17                  Data Analyst
18                  Data Analyst
19           Senior Data Analyst
20           Senior Data Analyst
21                    BI Analyst
22                  Data Analyst
23                  Data Analyst
24                    BI Analyst
25           Senior Data Analyst
26        Marketing Data Analyst
27          Product Data Analyst
28        Marketing Data Analyst
29                    BI Analyst
30           Junior Data Analyst
31           Senior Data Analyst
32     Data Analytics Specialist
33                  Data Analyst
34               Data Analyst II
35                  Data Analyst
36                  Data Analyst
37                  Data Analyst
38                  Data Analyst
39              Sr. Data Analyst
40        Marketing Data Analyst
41           Junior Data Analyst
42              Jr. Data Analyst
43               Data Analyst II
44              Sr. Data Analyst
45           Senior Data Analyst
46                  Data Analyst
47              Jr. Data Analyst
48                  Data Analyst
49                  Data Analyst
50           Junior Data Analyst
51                  Data Analyst
52              Jr. Data Analyst
53              Jr. Data Analyst
54                  Data Analyst
55               Data Analyst II
56                  Data Analyst
57                  Data Analyst
58        Marketing Data Analyst
59     Data Analytics Specialist
60                    BI Analyst
61                  Data Analyst
62           Junior Data Analyst
63                  Data Analyst
64                    BI Analyst
65               Data Analyst II
66          Product Data Analyst
67                  Data Analyst
68              Jr. Data Analyst
69                  Data Analyst
70           Senior Data Analyst
71        Marketing Data Analyst
72                  Data Analyst
73                  Data Analyst
74          Product Data Analyst
75           Senior Data Analyst
76                  Data Analyst
77               Data Analyst II
78                  Data Analyst
79           Senior Data Analyst
80                  Data Analyst
81           Junior Data Analyst
82               Data Analyst II
83     Data Analytics Specialist
84          Product Data Analyst
85              Jr. Data Analyst
86              Sr. Data Analyst
87              Jr. Data Analyst
88              Jr. Data Analyst
89           Senior Data Analyst
90          Product Data Analyst
91               Data Analyst II
92        Marketing Data Analyst
93          Product Data Analyst
94          Product Data Analyst
95                  Data Analyst
96                  Data Analyst
97          Product Data Analyst
98              Sr. Data Analyst
99                    BI Analyst
100       Marketing Data Analyst
101          Senior Data Analyst
102             Sr. Data Analyst
103    Data Analytics Specialist
104          Junior Data Analyst
105              Data Analyst II
106         Product Data Analyst
107       Marketing Data Analyst
108                   BI Analyst
109          Senior Data Analyst
110         Product Data Analyst
111             Jr. Data Analyst
112                 Data Analyst
113                 Data Analyst
114                 Data Analyst
115          Senior Data Analyst
116                 Data Analyst
117                 Data Analyst
118             Jr. Data Analyst
119          Junior Data Analyst
120              Data Analyst II
121                 Data Analyst
122          Senior Data Analyst
123                 Data Analyst
124       Marketing Data Analyst
125             Jr. Data Analyst
126          Senior Data Analyst
127         Product Data Analyst
128    Data Analytics Specialist
129          Junior Data Analyst
130         Product Data Analyst
131    Data Analytics Specialist
132             Sr. Data Analyst
133              Data Analyst II
134             Sr. Data Analyst
135          Senior Data Analyst
136       Marketing Data Analyst
137                   BI Analyst
138                   BI Analyst
139              Data Analyst II
140       Marketing Data Analyst
141                 Data Analyst
142          Junior Data Analyst
143                 Data Analyst
144          Junior Data Analyst
145             Jr. Data Analyst
146          Senior Data Analyst
147             Sr. Data Analyst
148                   BI Analyst
149    Data Analytics Specialist
150                 Data Analyst
151                 Data Analyst
152                 Data Analyst
153                 Data Analyst
154             Sr. Data Analyst
155         Product Data Analyst
156             Sr. Data Analyst
157                 Data Analyst
158         Product Data Analyst
159          Junior Data Analyst
160                 Data Analyst
161                 Data Analyst
162          Junior Data Analyst
163          Junior Data Analyst
164                 Data Analyst
165    Data Analytics Specialist
166                   BI Analyst
167              Data Analyst II
168                   BI Analyst
169                 Data Analyst
170         Product Data Analyst
171       Marketing Data Analyst
172                 Data Analyst
173         Product Data Analyst
174                   BI Analyst
175                 Data Analyst
176              Data Analyst II
177                 Data Analyst
178         Product Data Analyst
179             Jr. Data Analyst
180                 Data Analyst
181              Data Analyst II
182          Junior Data Analyst
183             Sr. Data Analyst
184    Data Analytics Specialist
185                 Data Analyst
186       Marketing Data Analyst
187       Marketing Data Analyst
188              Data Analyst II
189                   BI Analyst
190                 Data Analyst
191             Sr. Data Analyst
192                   BI Analyst
193                 Data Analyst
194         Product Data Analyst
195              Data Analyst II
196         Product Data Analyst
197                   BI Analyst
198                 Data Analyst
199          Senior Data Analyst
200             Sr. Data Analyst
201             Jr. Data Analyst
202                 Data Analyst
203             Sr. Data Analyst
204                   BI Analyst
205                 Data Analyst
206                   BI Analyst
207                 Data Analyst
208                 Data Analyst
209             Jr. Data Analyst
210    Data Analytics Specialist
211                 Data Analyst
212                 Data Analyst
213             Jr. Data Analyst
214                 Data Analyst
215              Data Analyst II
216          Senior Data Analyst
217                 Data Analyst
218          Senior Data Analyst
219                 Data Analyst
220                 Data Analyst
221                 Data Analyst
222       Marketing Data Analyst
223    Data Analytics Specialist
224                 Data Analyst
225                 Data Analyst
226                   BI Analyst
227                 Data Analyst
228             Sr. Data Analyst
229             Sr. Data Analyst
230         Product Data Analyst
231    Data Analytics Specialist
232                   BI Analyst
233             Sr. Data Analyst
234              Data Analyst II
235                   BI Analyst
236                 Data Analyst
237          Junior Data Analyst
238          Senior Data Analyst
239                   BI Analyst
240                 Data Analyst
241       Marketing Data Analyst
242       Marketing Data Analyst
243          Senior Data Analyst
244       Marketing Data Analyst
245              Data Analyst II
246          Junior Data Analyst
247         Product Data Analyst
248         Product Data Analyst
249             Jr. Data Analyst
250    Data Analytics Specialist
251                   BI Analyst
252    Data Analytics Specialist
253                 Data Analyst
254          Senior Data Analyst
255          Senior Data Analyst
256                 Data Analyst
257             Jr. Data Analyst
258                 Data Analyst
259                 Data Analyst
260                   BI Analyst
261          Senior Data Analyst
262                 Data Analyst
263          Senior Data Analyst
264                 Data Analyst
265                 Data Analyst
266       Marketing Data Analyst
267         Product Data Analyst
268                 Data Analyst
269          Senior Data Analyst
270                 Data Analyst
271                 Data Analyst
272             Jr. Data Analyst
273                 Data Analyst
274                   BI Analyst
275          Senior Data Analyst
276              Data Analyst II
277         Product Data Analyst
278    Data Analytics Specialist
279          Senior Data Analyst
280                   BI Analyst
281             Sr. Data Analyst
282       Marketing Data Analyst
283                 Data Analyst
284                 Data Analyst
285    Data Analytics Specialist
286          Senior Data Analyst
287                 Data Analyst
288    Data Analytics Specialist
289                 Data Analyst
290          Junior Data Analyst
291          Senior Data Analyst
292                 Data Analyst
293                 Data Analyst
294         Product Data Analyst
295          Junior Data Analyst
296             Jr. Data Analyst
297          Junior Data Analyst
298          Junior Data Analyst
299    Data Analytics Specialist
300       Marketing Data Analyst
301                 Data Analyst
302         Product Data Analyst
303         Product Data Analyst
304         Product Data Analyst
305                 Data Analyst
306                 Data Analyst
307          Junior Data Analyst
308       Marketing Data Analyst
309             Jr. Data Analyst
310                 Data Analyst
311                 Data Analyst
312          Senior Data Analyst
313          Senior Data Analyst
314          Senior Data Analyst
315                   BI Analyst
316    Data Analytics Specialist
317             Sr. Data Analyst
318          Junior Data Analyst
319             Sr. Data Analyst
320              Data Analyst II
321    Data Analytics Specialist
322          Senior Data Analyst
323                 Data Analyst
324    Data Analytics Specialist
325                 Data Analyst
326                   BI Analyst
327                 Data Analyst
328                 Data Analyst
329         Product Data Analyst
330                   BI Analyst
331                 Data Analyst
332                 Data Analyst
333                 Data Analyst
334          Senior Data Analyst
335             Sr. Data Analyst
336          Junior Data Analyst
337    Data Analytics Specialist
338    Data Analytics Specialist
339          Senior Data Analyst
340          Junior Data Analyst
341                 Data Analyst
342             Sr. Data Analyst
343          Junior Data Analyst
344                 Data Analyst
345          Junior Data Analyst
346              Data Analyst II
347                 Data Analyst
348                 Data Analyst
349    Data Analytics Specialist
350              Data Analyst II
351          Junior Data Analyst
352       Marketing Data Analyst
353       Marketing Data Analyst
354                 Data Analyst
355                   BI Analyst
356         Product Data Analyst
357       Marketing Data Analyst
358    Data Analytics Specialist
359             Sr. Data Analyst
360          Senior Data Analyst
361              Data Analyst II
362          Senior Data Analyst
363                 Data Analyst
364                 Data Analyst
365       Marketing Data Analyst
366                   BI Analyst
367                 Data Analyst
368       Marketing Data Analyst
369             Jr. Data Analyst
370                 Data Analyst
371                 Data Analyst
372                 Data Analyst
373    Data Analytics Specialist
374                   BI Analyst
375                   BI Analyst
376             Sr. Data Analyst
377                 Data Analyst
378                   BI Analyst
379                 Data Analyst
380             Sr. Data Analyst
381                 Data Analyst
382                 Data Analyst
383                 Data Analyst
384         Product Data Analyst
385          Senior Data Analyst
386          Junior Data Analyst
387                 Data Analyst
388                 Data Analyst
389          Senior Data Analyst
390                 Data Analyst
391                 Data Analyst
392                 Data Analyst
393                 Data Analyst
394                 Data Analyst
395          Junior Data Analyst
396         Product Data Analyst
397                 Data Analyst
398                 Data Analyst
399                   BI Analyst
400             Jr. Data Analyst
401              Data Analyst II
402          Senior Data Analyst
403         Product Data Analyst
404       Marketing Data Analyst
405             Jr. Data Analyst
406          Senior Data Analyst
407              Data Analyst II
408          Junior Data Analyst
409             Sr. Data Analyst
410         Product Data Analyst
411         Product Data Analyst
412              Data Analyst II
413    Data Analytics Specialist
414             Jr. Data Analyst
415                 Data Analyst
416                 Data Analyst
417                 Data Analyst
418    Data Analytics Specialist
419                 Data Analyst
420                 Data Analyst
421                 Data Analyst
422                 Data Analyst
423                   BI Analyst
424          Senior Data Analyst
425                   BI Analyst
426              Data Analyst II
427             Sr. Data Analyst
428             Jr. Data Analyst
429                 Data Analyst
430          Senior Data Analyst
431             Jr. Data Analyst
432              Data Analyst II
433             Sr. Data Analyst
434    Data Analytics Specialist
435                   BI Analyst
436       Marketing Data Analyst
437              Data Analyst II
438                 Data Analyst
439                 Data Analyst
440         Product Data Analyst
441                   BI Analyst
442                 Data Analyst
443         Product Data Analyst
444                   BI Analyst
445              Data Analyst II
446         Product Data Analyst
447                 Data Analyst
448             Sr. Data Analyst
449              Data Analyst II
450                 Data Analyst
451                 Data Analyst
452       Marketing Data Analyst
453                   BI Analyst
454             Sr. Data Analyst
455              Data Analyst II
456              Data Analyst II
457                 Data Analyst
458          Senior Data Analyst
459       Marketing Data Analyst
460             Jr. Data Analyst
461          Senior Data Analyst
462         Product Data Analyst
463         Product Data Analyst
464              Data Analyst II
465                   BI Analyst
466    Data Analytics Specialist
467              Data Analyst II
468                 Data Analyst
469                 Data Analyst
470         Product Data Analyst
471          Junior Data Analyst
472              Data Analyst II
473                 Data Analyst
474                 Data Analyst
475             Jr. Data Analyst
476                 Data Analyst
477             Sr. Data Analyst
478         Product Data Analyst
479              Data Analyst II
480                 Data Analyst
481       Marketing Data Analyst
482    Data Analytics Specialist
483                   BI Analyst
484       Marketing Data Analyst
485          Junior Data Analyst
486                   BI Analyst
487                 Data Analyst
488                 Data Analyst
489                 Data Analyst
490       Marketing Data Analyst
491             Sr. Data Analyst
492                   BI Analyst
493                 Data Analyst
494             Jr. Data Analyst
495                 Data Analyst
496                   BI Analyst
497             Sr. Data Analyst
498          Junior Data Analyst
499             Sr. Data Analyst
Name: job_title, dtype: object

In [ ]:
# After Cleaning
bdata.head(10)

,job_title,salary,location,remote_location,company_size,experience_level,employment_type,skills,experience_level_value,company_size_value,employment_type_value
0,Sr.Data Analyst,0,"Las Vegas, NV",C2C,Large,Excel;R,None,False,0,3,0
1,Data Analyst,65000,"Atlanta, GA",No,Huge,Sr,Freelance,"AWS, Python, Google Cloud, Power BI",3,4,6
2,Data Analyst,65000,"Santa Fe, NW",1,Large,Pr,Contract,"Python, , Excel",4,3,4
3,Marketing Data Analyst,0,"Orlando, FL",Yes,Unknown,None,Regular,"Tableau , Azure , R , Python ,",0,0,3
4,Data Analyst II,65000,"Columbus, OH",Hybrid,Unknown,Jr,Part-time,"Python , Tableau , Azure , Google Cloud , SQL",1,0,2
5,Senior Data Analyst,0,"Oklahoma, OK",Partial,Startup,Mi,Part-time,"Excel, R",2,1,2
6,Senior Data Analyst,95000,"Phoenix, AZ",False,Startup,Pr,Full-time,"Python, AWS",4,1,1
7,Sr. Data Analyst,65000,"Atlanta, GA",1,Medium,Jr,Regular,"Tableau, Power BI, Python, , AWS",1,2,3
8,Marketing Data Analyst,120000,"Las Vegas, NV",0,Large,Mi,Full-time,"Google Cloud, Azure, Excel, Python, SQL",2,3,1
9,Data Analyst,95000.0,"Fort Collins, CO",False,Unknown,Mi,Temporary,", Azure, Excel, SQL, R",2,0,5

## Problem 4: Review Experience Level

To clean the `experience_level` we will use the same function from `job_title` to clean the column and then run the function, for now we replaced with `None`.

In [ ]:
# View Experience Level
bdata['experience_level'].head(500)

0      Excel;R
1           Sr
2           Pr
3         None
4           Jr
5           Mi
6           Pr
7           Jr
8           Mi
9           Mi
10          Sr
11          Sr
12          Mi
13          Mi
14          Jr
15          Sr
16          Jr
17          Mi
18          Mi
19          Pr
20          Jr
21          Mi
22        None
23          Jr
24        None
25          Sr
26          Mi
27          Jr
28          Jr
29          Mi
30        None
31          Sr
32          Sr
33          Sr
34          Pr
35          Jr
36          Jr
37          Mi
38          Jr
39          Pr
40          Jr
41          Jr
42          Jr
43          Pr
44          Mi
45          Jr
46          Jr
47          Sr
48          Jr
49          Pr
50          Mi
51          Jr
52          Jr
53          Pr
54        None
55          Mi
56          Jr
57          Pr
58          Jr
59          Jr
60          Sr
61        None
62          Sr
63          Mi
64          Mi
65          Jr
66          Pr
67          Jr
68          Jr
69          Sr
70          Jr
71          Jr
72          Jr
73        None
74        None
75          Sr
76          Sr
77          Jr
78          Sr
79          Sr
80          Sr
81          Jr
82          Jr
83          Sr
84          Sr
85          Jr
86          Mi
87        None
88          Sr
89          Jr
90          Jr
91          Jr
92          Jr
93          Jr
94          Jr
95          Jr
96          Sr
97          Jr
98          Jr
99          Mi
100         Sr
101         Jr
102         Sr
103       None
104       None
105         Jr
106         Sr
107         Sr
108         Sr
109         Jr
110         Jr
111         Mi
112         Sr
113         Jr
114         Jr
115         Mi
116         Sr
117       None
118         Mi
119         Jr
120         Pr
121         Jr
122         Pr
123         Jr
124         Sr
125         Mi
126       None
127         Jr
128         Sr
129         Jr
130         Jr
131         Jr
132         Pr
133         Jr
134         Mi
135         Jr
136         Jr
137         Jr
138         Mi
139         Jr
140         Jr
141         Jr
142         Mi
143         Jr
144         Mi
145         Jr
146         Jr
147         Jr
148         Sr
149         Jr
150         Jr
151         Pr
152         Mi
153         Mi
154         Mi
155         Jr
156         Jr
157         Jr
158         Jr
159         Jr
160         Mi
161       None
162         Jr
163         Jr
164         Jr
165         Jr
166       None
167         Jr
168         Jr
169         Jr
170         Jr
171         Jr
172         Jr
173         Mi
174         Jr
175         Sr
176         Jr
177       None
178         Pr
179         Jr
180         Pr
181         Mi
182         Jr
183         Jr
184         Mi
185         Jr
186         Jr
187         Mi
188         Jr
189         Sr
190         Jr
191         Sr
192         Sr
193         Jr
194         Mi
195         Jr
196         Mi
197       None
198         Jr
199         Mi
200         Sr
201         Mi
202         Sr
203         Mi
204         Sr
205         Jr
206       None
207         Jr
208     10000+
209         Jr
210         Jr
211         Jr
212         Sr
213         Jr
214       None
215         Sr
216         Mi
217         Pr
218         Jr
219         Pr
220         Pr
221         Jr
222         Jr
223         Mi
224         Jr
225         Sr
226       None
227         Pr
228         Mi
229         Jr
230         Jr
231         Mi
232       None
233         Jr
234         Jr
235         Sr
236         Pr
237         Jr
238         Pr
239         Mi
240       None
241         Jr
242         Sr
243       None
244         Sr
245         Mi
246         Sr
247         Sr
248         Jr
249         Sr
250         Sr
251         Jr
252         Sr
253         Sr
254         Jr
255         Jr
256         Mi
257         Sr
258         Pr
259         Pr
260         Jr
261         Jr
262         Jr
263         Jr
264       None
265         Pr
266         Pr
267         Jr
268         Jr
269         Jr
270         Jr
271         Jr
272         Mi
273         Jr
274         Sr
275         Jr
276         Sr
277         Jr
278         Pr
279         Jr
280         Sr
281         Jr
282         Sr
283         Jr
284         Jr
285         Pr
286         Pr
287         Pr
288         Mi
289         Mi
290         Jr
291         Jr
292         Sr
293         Sr
294         Jr
295         Mi
296       None
297         Sr
298         Pr
299         Jr
300         Sr
301         Jr
302         Sr
303         Jr
304         Pr
305         Sr
306         Sr
307         Mi
308         Pr
309         Mi
310         Jr
311         Jr
312         Mi
313         Jr
314         Mi
315         Sr
316         Sr
317         Jr
318         Jr
319       None
320         Pr
321         Mi
322       None
323         Mi
324         Jr
325         Jr
326         Jr
327         Sr
328         Mi
329         Jr
330         Jr
331       None
332         Jr
333         Mi
334         Sr
335         Jr
336         Sr
337         Jr
338       None
339         Jr
340         Jr
341         Sr
342         Pr
343         Mi
344         Jr
345       None
346         Sr
347         Sr
348         Jr
349       None
350         Jr
351         Sr
352         Jr
353         Jr
354         Jr
355         Mi
356         Sr
357         Jr
358         Jr
359         Jr
360         Jr
361         Sr
362         Sr
363       None
364         Jr
365         Sr
366         Jr
367         Mi
368       None
369       None
370         Sr
371         Jr
372         Pr
373         Sr
374         Pr
375         Pr
376         Jr
377         Sr
378         Jr
379         Mi
380         Sr
381         Jr
382         Sr
383       None
384         Jr
385         Mi
386         Pr
387         Mi
388       None
389         Jr
390         Mi
391         Jr
392         Pr
393         Sr
394         Jr
395         Jr
396         Mi
397       None
398         Jr
399         Mi
400         Sr
401         Jr
402       None
403         Mi
404         Sr
405         Jr
406         Jr
407         Pr
408         Jr
409         Jr
410         Jr
411         Mi
412         Jr
413         Jr
414         Mi
415         Jr
416         Mi
417         Jr
418         Mi
419         Jr
420         Jr
421         Sr
422         Mi
423         Sr
424         Sr
425         Jr
426         Sr
427         Jr
428         Sr
429         Mi
430       None
431         Jr
432         Jr
433         Jr
434         Jr
435         Jr
436         Pr
437         Pr
438       None
439         Jr
440         Jr
441         Jr
442         Mi
443         Jr
444         Mi
445         Sr
446         Sr
447         Mi
448         Sr
449         Sr
450         Jr
451         Pr
452         Pr
453         Mi
454         Sr
455         Jr
456         Jr
457         Sr
458         Sr
459         Pr
460         Jr
461         Mi
462         Jr
463         Jr
464         Jr
465         Mi
466         Jr
467         Jr
468       None
469         Sr
470         Jr
471         Jr
472         Jr
473         Pr
474         Jr
475         Mi
476         Mi
477         Sr
478         Jr
479         Sr
480         Jr
481       None
482         Mi
483         Jr
484         Sr
485         Mi
486         Jr
487         Jr
488         Sr
489         Jr
490         Jr
491         Jr
492         Sr
493         Mi
494         Jr
495         Sr
496         Jr
497         Jr
498         Mi
499         Jr
Name: experience_level, dtype: object

In [ ]:
# Find all the unique entry
bdata['experience_level'].unique()

array(['Excel;R', 'Sr', 'Pr', 'None', 'Jr', 'Mi', '10000+', 'Part-time',
       "['New York, NY', 'San Francisco, CA', 'Dallas, TX', 'Remote', 'US', 'London, UK', 'Austin, TX', 'Anywhere', nan, 'Houston,TX', 'Huntsville,AL']",
       'True', 'Full-time', 'No', 'Tableau |  | Excel | Python',
       'DATA ANALYST', 'False', 'Python;AWS;Tableau;Excel;Power BI',
       '65000Competitive', 'Medium', 'DOE', 'Data Analytics Specialist',
       'PT', 'Startup', "['R', 'SQL', '', 'Excel']", 'Data Analyst II'],
      dtype=object)

In [ ]:
# Create non job title function to clean `experience_level` column
def non_experience_level(df_to_clean):

  # Create non title set to replace
  non_experience_level_set = {
      'Excel;R', '10000+', 'Part-time',
      "['New York, NY', 'San Francisco, CA', 'Dallas, TX', 'Remote', 'US', 'London, UK', 'Austin, TX', 'Anywhere', nan, 'Houston,TX', 'Huntsville,AL']",
      'True', 'Full-time', 'No', 'Tableau |  | Excel | Python',
       'DATA ANALYST', 'False', 'Python;AWS;Tableau;Excel;Power BI',
       '65000Competitive', 'Medium', 'DOE', 'Data Analytics Specialist',
       'PT', 'Startup', "['R', 'SQL', '', 'Excel']", 'Data Analyst II',
  }

  # Find all non experience level entry in the set and replace them with 'None` -- For Now
  df_to_clean['experience_level'] = df_to_clean['experience_level'].replace(list(non_experience_level_set), 'None')
  return df_to_clean

In [ ]:
# Run the Experience_level function
bdata = non_experience_level(bdata)

In [ ]:
# Find all the unique entry Again
bdata['experience_level'].unique()

array(['None', 'Sr', 'Pr', 'Jr', 'Mi'], dtype=object)

# View the Completed Dataset

In [ ]:
# We should now be able view the full cleaned dataset
bdata.head(100)

,job_title,salary,location,remote_location,company_size,experience_level,employment_type,skills,experience_level_value,company_size_value,employment_type_value
0,Sr.Data Analyst,0,"Las Vegas, NV",C2C,Large,None,None,False,0,3,0
1,Data Analyst,65000,"Atlanta, GA",No,Huge,Sr,Freelance,"AWS, Python, Google Cloud, Power BI",3,4,6
2,Data Analyst,65000,"Santa Fe, NW",1,Large,Pr,Contract,"Python, , Excel",4,3,4
3,Marketing Data Analyst,0,"Orlando, FL",Yes,Unknown,None,Regular,"Tableau , Azure , R , Python ,",0,0,3
4,None,65000,"Columbus, OH",Hybrid,Unknown,Jr,Part-time,"Python , Tableau , Azure , Google Cloud , SQL",1,0,2
5,Senior Data Analyst,0,"Oklahoma, OK",Partial,Startup,Mi,Part-time,"Excel, R",2,1,2
6,Senior Data Analyst,95000,"Phoenix, AZ",False,Startup,Pr,Full-time,"Python, AWS",4,1,1
7,Sr. Data Analyst,65000,"Atlanta, GA",1,Medium,Jr,Regular,"Tableau, Power BI, Python, , AWS",1,2,3
8,Marketing Data Analyst,120000,"Las Vegas, NV",0,Large,Mi,Full-time,"Google Cloud, Azure, Excel, Python, SQL",2,3,1
9,Data Analyst,95000.0,"Fort Collins, CO",False,Unknown,Mi,Temporary,", Azure, Excel, SQL, R",2,0,5
10,Product Data Analyst,110000,"Philadelphia, PA",False,Large,Sr,Regular,"Excel , Azure , R , Google Cloud , Tableau",3,3,3
11,Marketing Data Analyst,0,"Houston, TX",False,Small,Sr,Full-time,"Tableau,Azure,SQL,Power BI",3,0,1
12,BI Analyst,70000,"Albuquerqu, NM",Temporarily Remote,Startup,Mi,Contract,"SQL, R, Tableau, Power BI, Google Cloud",2,1,4
13,Data Analyst,0,"Orlando, FL",1,Large,Mi,Contract,"AWS, Python, Google Cloud, Tableau, R",2,3,4
14,Data Analyst,110000,"Chicago, IL",0,Large,Jr,Part-time,"AWS, Azure, Excel",1,3,2
15,Junior Data Analyst,0,"San Francisco, CA",Hybrid,Large,Sr,Full-time,None,3,3,1
16,Data Analyst,50,"Indianapolis, IN",1,Medium,Jr,Part-time,"Excel,",1,2,2
17,Data Analyst,110000,"New Orleans, LA",Partial,Startup,Mi,Full-time,"Python, AWS, R",2,1,1
18,Data Analyst,0,"New Orleans, LA",Hybrid,Large,Mi,Part-time,"Python, Power BI, AWS, Azure,",2,3,2
19,Senior Data Analyst,0,"Nortfolk, VA",Temporarily Remote,Startup,Pr,Freelance,"Python, Excel, R",4,1,6
20,Senior Data Analyst,70000,"Santa Fe, NW",Partial,Large,Jr,Regular,"Azure,",1,3,3
21,BI Analyst,70000,"Houston, TX",Yes,Startup,Mi,Part-time,"Azure, SQL, Excel, Python",2,1,2
22,Data Analyst,50,"Fort Collins, CO",True,Large,None,Contract,"Azure,AWS,Power BI",0,3,4
23,Data Analyst,50000,"Columbus, OH",Hybrid,Huge,Jr,Part-time,", R, Python, Azure",1,4,2
24,BI Analyst,120000,"Louisville, KY",Yes,Startup,None,Contract,"SQL,Google Cloud,Python,Excel,Azure",0,1,4
25,Senior Data Analyst,65000,"New York, NY",True,Startup,Sr,Freelance,"Google Cloud, Tableau, Excel, SQL, Power BI",3,1,6
26,Marketing Data Analyst,95000.0,"Orlando, FL",Hybrid,Unknown,Mi,Full-time,"Google Cloud,",2,0,1
27,Product Data Analyst,50000,"Phoenix, AZ",Yes,Startup,Jr,Contract,", AWS , Google Cloud",1,1,4
28,Marketing Data Analyst,95000,"New Orleans, LA",Partial,Startup,Jr,Part-time,"R , Azure , Tableau",1,1,2
29,BI Analyst,70000.0,"Houston, TX",False,Unknown,Mi,Contract,None,2,0,4
30,Junior Data Analyst,50,"Houston, TX",Hybrid,Startup,None,Contract,"Azure,SQL,AWS,R",0,1,4
31,Senior Data Analyst,50,"Philadelphia, PA",Partial,Medium,Sr,Part-time,"SQL,Power BI,R",3,2,2
32,None,0,"Louisville, KY",0,Medium,Sr,Full-time,"Google Cloud, SQL, Azure, R",3,2,1
33,Data Analyst,95000.0,"Chicago, IL",No,Startup,Sr,Full-time,"R, , Power BI",3,1,1
34,None,110000,"Dallas, TX",Partial,Large,Pr,Part-time,", AWS, Tableau, Python, Excel",4,3,2
35,Data Analyst,110000,"Salt Lake City, UT",Yes,Medium,Jr,Full-time,"Azure,Power BI,AWS",1,2,1
36,Data Analyst,0,"Austin, TX",Partial,Small,Jr,Freelance,"R, AWS",1,0,6
37,Data Analyst,14000000,"Nashville, TN",1,Startup,Mi,Full-time,"Excel, Azure, R, Google Cloud",2,1,1
38,Data Analyst,95000,"New York, NY",Temporarily Remote,Medium,Jr,Contract,"Excel, , AWS, Power BI, Python",1,2,4
39,Sr. Data Analyst,8090000,"Louisville, KY",Partial,Large,Pr,Regular,"Python, Tableau, , Power BI",4,3,3
40,Marketing Data Analyst,8090000,"Fort Collins, CO",Partial,Huge,Jr,Part-time,"Azure, Power BI, AWS, Google Cloud,",1,4,2
41,Junior Data Analyst,110000,"Atlanta, GA",Partial,Startup,Jr,Part-time,"Power BI,Tableau,SQL,Python",1,1,2
42,Jr. Data Analyst,95000.0,"Fort Collins, CO",No,Startup,Jr,Contract,"Python, Google Cloud",1,1,4
43,None,0,"Louisville, KY",Hybrid,Startup,Pr,Contract,None,4,1,4
44,Sr. Data Analyst,110000,"Columbus, OH",No,Startup,Mi,Part-time,", Tableau, Power BI, AWS",2,1,2
45,Senior Data Analyst,0,"Orlando, FL",1,Unknown,Jr,Freelance,"Power BI, Python, R, Excel, Tableau",1,0,6
46,Data Analyst,0,"Nashville, TN",No,Small,Jr,Contract,"Tableau,Excel",1,0,4
47,Jr. Data Analyst,50,"Jackson, MS",True,Small,Sr,Temporary,"Google Cloud , Azure , Python , , Tableau",3,0,5
48,Data Analyst,95000.0,"New York, NY",False,Large,Jr,Part-time,None,1,3,2
49,Data Analyst,70000,"New Orleans, LA",Hybrid,Large,Pr,Part-time,"Excel, Python, Power BI, AWS",4,3,2
50,Junior Data Analyst,95000.0,"San Francisco, CA",Hybrid,Unknown,Mi,Part-time,"AWS, Azure, Python, R, Power BI",2,0,2
51,Data Analyst,8090000,"Las Vegas, NV",Temporarily Remote,Medium,Jr,Part-time,"Google Cloud, SQL, Power BI",1,2,2
52,Jr. Data Analyst,90000,"Houston, TX",False,Startup,Jr,Part-time,"AWS,Excel,Azure,Google Cloud",1,1,2
53,Jr. Data Analyst,120000,"Huntsville, AL",True,Large,Pr,Contract,"AWS, SQL, R, , Power BI",4,3,4
54,Data Analyst,95000.0,"Oklahoma, OK",Yes,Startup,None,Part-time,"Power BI, , Excel, Python, Tableau",0,1,2
55,None,0,"Las Vegas, NV",Temporarily Remote,Startup,Mi,Part-time,"Azure,R,AWS,Excel",2,1,2
56,Data Analyst,70000,"Detroit, MI",Hybrid,Startup,Jr,Regular,"Excel,Azure,Google Cloud",1,1,3
57,Data Analyst,70000,"Louisville, KY",0,Unknown,Pr,Contract,"R, SQL, Excel, AWS, Azure",4,0,4
58,Marketing Data Analyst,0,"Columbus, OH",No,Startup,Jr,Freelance,"Tableau,Python,Google Cloud",1,1,6
59,None,50000,"Nashville, TN",True,Startup,Jr,Full-time,"R,",1,1,1
60,BI Analyst,50,"Orlando, FL",Partial,Small,Sr,Freelance,"SQL , Azure , Tableau , R , AWS",3,0,6
61,Data Analyst,0,"Albuquerqu, NM",No,Unknown,None,Contract,"Power BI,",0,0,4
62,Junior Data Analyst,110000,"Huntsville, AL",1,Small,Sr,Contract,"AWS, Google Cloud, Excel, Tableau, R",3,0,4
63,Data Analyst,65000,"Philadelphia, PA",Yes,Unknown,Mi,Contract,"Power BI, AWS, Excel, R, SQL",2,0,4
64,BI Analyst,65000,"Huntsville, AL",False,Startup,Mi,Freelance,"R, Power BI, Tableau",2,1,6
65,None,65000,"Austin, TX",No,Startup,Jr,Part-time,"Azure,Python,Excel",1,1,2
66,Product Data Analyst,95000.0,"Denver, CO",0,Large,Pr,Temporary,"SQL, Power BI, Python",4,3,5
67,Data Analyst,0,"Las Vegas, NV",1,Unknown,Jr,Regular,None,1,0,3
68,Jr. Data Analyst,110000,"Nortfolk, VA",No,Unknown,Jr,Contract,"AWS, Power BI, Google Cloud",1,0,4
69,Data Analyst,70000,"Las Vegas, NV",1,Small,Sr,Part-time,"SQL, Azure, Excel, AWS",3,0,2
70,Senior Data Analyst,95000.0,"Orlando, FL",Hybrid,Small,Jr,Full-time,"Excel, , R, Tableau, AWS",1,0,1
71,Marketing Data Analyst,70000,"Detroit, MI",Yes,Large,Jr,Temporary,"Google Cloud,Excel,AWS,Python",1,3,5
72,Data Analyst,0,"Nortfolk, VA",No,Unknown,Jr,Temporary,"Azure , Google Cloud",1,0,5
73,Data Analyst,90000,"Santa Fe, NW",Partial,Large,None,Full-time,"AWS,SQL",0,3,1
74,Product Data Analyst,70000.0,"Santa Fe, NW",Partial,Unknown,None,Freelance,"Google Cloud, Excel",0,0,6
75,Senior Data Analyst,110000,"Houston, TX",Partial,Large,Sr,Full-time,"Tableau, Excel, SQL, Azure, Python",3,3,1
76,Data Analyst,90000,"Indianapolis, IN",False,Large,Sr,Full-time,"AWS, Excel, Python",3,3,1
77,None,65000,"Nashville, TN",Yes,Large,Jr,Temporary,"Power BI,Tableau",1,3,5
78,Data Analyst,65000,"Louisville, KY",1,Startup,Sr,Regular,"R,Tableau",3,1,3
79,Senior Data Analyst,8090000,"New York, NY",Yes,Huge,Sr,Full-time,"Azure, Power BI, , Tableau",3,4,1
80,Data Analyst,70000.0,"Fargo, ND",Partial,Large,Sr,Full-time,"Tableau, Excel, AWS, Azure, Python",3,3,1
81,Junior Data Analyst,95000,"Chicago, IL",1,Huge,Jr,Temporary,", Google Cloud , Python , Azure",1,4,5
82,None,0,"Oklahoma, OK",Hybrid,Startup,Jr,Temporary,"SQL, Excel, Azure, Tableau,",1,1,5
83,None,0,"Louisville, KY",True,Small,Sr,Contract,"Azure , Google Cloud , Python , , Tableau",3,0,4
84,Product Data Analyst,95000,"New York, NY",Yes,Startup,Sr,Contract,"Excel , , SQL",3,1,4
85,Jr. Data Analyst,50000,"Huntsville, AL",False,Large,Jr,Freelance,"AWS, SQL, Tableau, Python",1,3,6
86,Sr. Data Analyst,14000000,"Las Vegas, NV",1,Huge,Mi,Part-time,",Google Cloud,Azure,Excel,R",2,4,2
87,Jr. Data Analyst,0,"Salt Lake City, UT",Yes,Startup,None,Part-time,"Azure , R , Excel , Python",0,1,2
88,Jr. Data Analyst,0,"Philadelphia, PA",No,Startup,Sr,Contract,"Tableau,SQL",3,1,4
89,Senior Data Analyst,110000,"Columbus, OH",Temporarily Remote,Startup,Jr,Contract,"Python,R,Tableau,SQL",1,1,4
90,Product Data Analyst,90000,"Austin, TX",0,Medium,Jr,Full-time,",Python,SQL",1,2,1
91,None,70000,"Fargo, ND",No,Small,Jr,Freelance,"SQL, Python, Power BI, Azure",1,0,6
92,Marketing Data Analyst,0,"Las Vegas, NV",0,Startup,Jr,Full-time,"SQL, Tableau,",1,1,1
93,Product Data Analyst,8090000,"Jackson, MS",False,Unknown,Jr,Regular,",Google Cloud,Python",1,0,3
94,Product Data Analyst,95000,"New York, NY",Hybrid,Large,Jr,Full-time,"Excel,",1,3,1
95,Data Analyst,0,"Atlanta, GA",True,Large,Jr,Contract,"AWS,Google Cloud,Excel,SQL,",1,3,4
96,Data Analyst,65000,"New York, NY",0,Large,Sr,Freelance,"Python, AWS",3,3,6
97,Product Data Analyst,0,"Jackson, MS",No,Huge,Jr,Part-time,"Python, SQL",1,4,2
98,Sr. Data Analyst,95000.0,"Santa Fe, NW",Yes,Startup,Jr,Full-time,"Tableau, , Azure, SQL, Excel",1,1,1
99,BI Analyst,0,"Philadelphia, PA",True,Large,Mi,Temporary,"Azure , SQL , Excel",2,3,5

## Save Cleaned data to CSV file

In [ ]:
# Save to CSV
# df.to_csv("messy_data_analyst_jobs.csv", index=False)

bdata.to_csv('Cleaned_data_analyst_jobs.csv', index=False)
print("Dataset saved")